### ISSUE TITLE
[JS-only] Support <react-navigation>

### ISSUE THREAD

**Issue by robertev** [microsoft/react-native-windows#4141] opened 2020-02-20 19:48 UTC
# Support react-navigation on RNW vNext
## Basic Info
- Module Repo URL: https://github.com/react-navigation/react-navigation
- Target version: ^4.0.7
## Overview of Required Functionality
Navigation

**Comment by harinikmsft** [comment] 2020-02-20 22:31
Dupe of #3884

**Closed by harinikmsft** 2020-02-20 22:31 UTC
Labels: Extensions, Needs: Triage :mag:, vnext
