### ISSUE TITLE
How to see logs when using react-native run-windows?

### ISSUE THREAD

**Issue by joewood** [Microsoft/react-native-windows#703] opened 2016-09-16 22:59 UTC
I notice that the plugin doesn't support `react-native log-windows` yet. There is some mention of ETW in the issue list. How can you view the `console.log` output now without opening the solution in Visual Studio.

**Comment by rozele** [comment] 2016-09-17 09:28
Thanks @joewood.  We do have plans for this, and @mpodwysocki created some great tools for consuming ETW logs from Node.js.  I believe at this point we just have to create a new LoggingChannel or EventSource specific to the JavaScript console and create a little wrapper to connect to Matt's Node tooling.

**Comment by rozele** [comment] 2017-10-18 18:11
Another option for this in the near term would be to continue to use OutputDebugString (i.e., System.Diagnostics.Debug.WriteLine) and use something like this -
 https://stackoverflow.com/questions/1520119/replicate-functionality-of-dbgview-in-net-global-win32-debug-hooks - to read them to the console.

**Comment by rozele** [comment] 2018-07-23 20:06
Closing as roughly dupe of #505

**Closed by rozele** 2018-07-23 20:06 UTC
Labels: medium, p1
