### ISSUE TITLE
Move CLI out of vCurrent

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#4035] opened 2020-02-05 00:55 UTC
The CLI is shared between `vnext` and `current`, but the code lives under `current`'s folders structure. As we want to retire `current` (see #4034), we'll want to extract the CLI to a more neutral location.

**Comment by harinikmsft** [comment] 2020-02-06 19:13
Dupe of #4032

**Closed by harinikmsft** 2020-02-06 19:13 UTC
Labels: Area: CLI, Needs: Triage :mag:, Proposal, vnext
