### ISSUE TITLE
Deprecate "acceptsKeyboardFocus" in favor of "focusable"

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#2784] opened 2019-07-17 18:11 UTC
# Proposal: Need APIs for custom tab navigation

## Summary
This proposal tracks the need to expose new APIs for apps to customize tab navigation and focus management when the default behaviors are not sufficient for their scenarios.

## Motivation

Native controls support default tab navigation and focus visuals. We also just introduced Keyboard events and some default key stroke behaviors in Milestone 2. The next scenarios that need to be enabled to complete this story are around customizing tab navigation when the default behaviors are not sufficient.  

## Proposed solution(s)
Introduce the following APIs:
1.  `tabIndex` : specifies the tab order of the element in integer values. 
   - If this value is 0, the default tab order will be followed.
   - If this is set to <0, that element will be ignored in tab-order. 
See [HTML-tabIndex](https://www.w3schools.com/tags/att_tabindex.asp) and [XAML-TabIndex](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.tabindex) for reference. We should deprecate the Windows-only API `acceptsKeyboardFocus` once this prop is added since negative values for tabIndex serve all the scenarios that this separate property used to.

~~Alternate option: We can introduce tabIndex without the "-1" behavior and retain `acceptsKeyboardFocus` as a separate property. This matches more closely with Windows behavior. It also supports scenarios where dynamically enabling tabbing on a View can be done independent of the tab order of that View.~~

2. `focusZone` and `focusTrapZone` components will be created in a separate package. These will follow the pattern of fabric React [focusTrapZone](https://developer.microsoft.com/en-us/fabric/#/controls/web/focustrapzone) and [focusZone](https://developer.microsoft.com/en-us/fabric/#/controls/web/focuszone) APIs and will be implemented using the native [XAML Control.TabNavigation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.tabnavigation) APIs.

~~Alternate option: Add tabNavigation prop similar to the XAML approach.~~

### Not in scope:

-  `nextFocusForward` : specifies the next element in the tab order. This is a currently supported API in RN only for [Android](https://developer.android.com/reference/android/view/View.html#attr_android:nextFocusForward) and helps with the scenario where default tabbing mostly works and apps need one or two places where they want to customize the next element in the tab order.

We are not adding this property since there is a lot of collision behaviors with tabIndex and tabIndex seems to be more useful and solves all the scenarios that nextFocusForward supports.

**Comment by RobMeyer** [comment] 2019-07-17 18:46
A coworker and I have been prototyping Tab and F6 focus loop order in our app this week. We were able to get tab (and F6!) order working as required using a combination of tabIndex, tabNavigation, and implementing a custom focus manager (which requires focus and onFocus). Our general strategy was to let the platform handle the vast majority of tabs (in situations where our focus movement respects the "natural order") and only use tabNavigation and our CustomFocusManager interventions in specific scenarios that need custom behavior.
 
All this to say, our experience supports the proposed solutions.
 
Regarding your open question of whether tabIndex and nextFocusForward are both required, I think having all three: tabIndex + tabNavigation + nextForwardFocus will allow us to remove our CustomFocusManager implementation, which would be quite nice. tabIndex + tabNavigation would be preferable over tabIndex + nextForwardFocus for convenience of implementation, however we have a situation where focus needs to move between two ScrollViewers which isn't currently supported using tabIndex + tabNavigation alone.

**Comment by aschultz** [comment] 2019-10-01 23:22
Is there a proposal for handling directional navigation with arrow keys or gamepad? nextFocusUp/Down/Left/Right seems like they would map to the Control.XYFocusUp/Down/Left/Right properties in XAML for this.

**Comment by harinikmsft** [comment] 2019-10-24 16:52
@aschultz - the directional navigation work is being handled through #2197 which is in our backlog for future. Gamepad directional navigation will "just work" with the default behaviors in the native platform today. The work tracked in #2197 is to enable APIs to customize the default behaviors - from the preliminary testing done by the Xbox team on the console, it appears the default behaviors are adequate. So, we haven't prioritized that aspect. 

This current issue is scoped to introducing tabIndex only at this time.

**Comment by chrisglein** [comment] 2020-04-14 17:44
@harinikmsft Something to move to the discussions/proposals repo?

**Comment by harinikmsft** [comment] 2020-04-27 22:42
Consensus after latest design discussion - there is value in a simple boolean prop and this aligns now with the new prop introduced in v0.62 anyway. TabIndex is still good to have, but can be treated as an advanced API and proposed to RN separately after gathering evidence of usage in Windows and other platforms.

Work to be completed here:
- Change `acceptsKeyboardFocus` prop name to `focusable` to align with the [new prop](https://reactnative.dev/docs/view#focusable) introduced on View in v0.62. 
- `focusable` should default to true for elements that can take keyboard input by default (Pressable, TouchableXXX, TextInput, Button etc.,)
- Remove the logic for `tabIndex = -1` since that is web-only behavior that conflicts with the boolean prop. After this change,`tabIndex` can only be >=0.

All these changes will be made as part of breaking changes for v0.62. 

#4703 is related.

**Comment by NickGerleman** [comment] 2020-05-18 07:27
The tabIndex fix was merged into 0.62. Focusable hasn't made it yet, but there is enough code still using it that it would be nice to do a phased deprecation. E.g. 0.63 marks acceptsKeyboardInput as deprecated, 0.64 removes it.

**Comment by aschultz** [comment] 2020-12-01 23:57
@harinikmsft It'd be good to get a final update on here as to the expected behaviors for tab nav. Originally the desire was to match web behavior:
- tabIndex=-1 to disable tabbing
- tabIndex=0 to enable tabbing with default order
- tabIndex=N to enable tabbing and use specific ordering

The behavior as implemented (and presumably by design) is now:
- `tabIndex=-1` is an error
- `tabIndex=N` (including zero) for specific ordering
- `tabIndex=undefined` or `tabIndex=Int32.MaxValue` for default ordering
- `focusable` prop to toggle whether tabbing is enabled

**Comment by aschultz** [comment] 2021-07-29 21:59
Related: https://github.com/MicrosoftDocs/windows-uwp/issues/3270

The default TabIndex in XAML (as born out by testing) is Int32.MaxValue. This means setting TabIndex to any other value, including 0, will take an element out of the normal tab order and place it before the set of default TabIndex elements. There's no way to move an element to "after" default elements.

**Comment by rectified95** [comment] 2021-11-24 20:18
Looks like this was done in 2020, both deprecation and then removal - closing this issue.

https://github.com/microsoft/react-native-windows/pull/5047
https://github.com/microsoft/react-native-windows/pull/5844

**Closed by rectified95** 2021-11-24 20:18 UTC
Labels: enhancement, Area: Keyboard, Partner: Xbox, Partner: Office, Partner: Stream, Deliverable, Breaking Change
