### ISSUE TITLE
I am receiving the following error when trying to display the Modal:

### ISSUE THREAD

**Issue by sachin9990** [microsoft/react-native-windows#11047] opened 2022-12-28 07:25 UTC
I am receiving the following error when trying to display the Modal:

![image](https://user-images.githubusercontent.com/2465503/101775994-4baed380-3b16-11eb-9362-7cc4d74b91d1.png)

React Native version: 0.63.3

Adding log from browser console:

This error is located at:
    in RCTModalHostView (at Modal.js:228)
    in Modal (at InvitelessShareView.windows.tsx:166)
    in InvitelessShareView
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.windows.js:44)
    in View (at CardContainer.tsx:222)
    in RCTView (at View.windows.js:44)
    in View (at CardContainer.tsx:221)
    in RCTView (at View.windows.js:44)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at View.windows.js:44)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)
    in Dummy (at Card.tsx:549)
    in RCTView (at View.windows.js:44)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in RCTView (at View.windows.js:44)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:190)
    in CardContainer (at CardStack.tsx:623)
    in RCTView (at View.windows.js:44)
    in View (at Screens.tsx:84)
    in MaybeScreen (at CardStack.tsx:616)
    in RCTView (at View.windows.js:44)
    in View (at Screens.tsx:54)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in RCTView (at View.windows.js:44)
    in View (at CompatNativeSafeAreaProvider.tsx:28)
    in CompatNativeSafeAreaProvider (at SafeAreaContext.tsx:74)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.windows.js:44)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at App.tsx:41)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:396)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at App.tsx:40)
    in App (at renderApplication.js:45)
    in RCTView (at View.windows.js:44)
    in View (at AppContainer.js:106)
    in RCTView (at View.windows.js:44)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)

Could you let me know if I am missing anything here ?

_Originally posted by @aRajeshKumar in https://github.com/microsoft/react-native-windows/issues/1978#issuecomment-742508617_
      

I have the same issue, Has this been resolved?

**Comment by chrisglein** [comment] 2023-01-05 19:12
The Modal component is not yet implemented, as tracked by this issue: #2989

**Comment by chrisglein** [comment] 2023-01-05 19:12
Duplicate of #2989

**Closed** 2023-01-05 19:12 UTC
Labels: Needs: Triage :mag:
