### ISSUE TITLE
Opening solution in vs2022 breaks autolinking

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#9460] opened 2022-02-03 01:58 UTC
Looks like opening a solution in vs2022 adds back ARM (and revs the VS version in the sln)

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/22989529/152268640-4e9336f7-3a04-40f2-9136-c34cf24aadce.png">

**Comment by chrisglein** [comment] 2022-02-03 19:43
Duplicate of #9459

**Closed by chrisglein** 2022-02-03 19:43 UTC
Labels: Needs: Triage :mag:
