### ISSUE TITLE
Payload contains two or more files with the same destination path 'Microsoft.ReactNative.pdb', but they are different sizes.

### ISSUE THREAD

**Issue by mrousavy** [microsoft/react-native-windows#5911] opened 2020-09-03 19:09 UTC
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.12.0
2. `npx react-native run-windows --info`:
```
(node:9424) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9424) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:9424) Warning: Accessing non-existent property 'which' of module exports inside circular dependency

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 23.69 GB / 31.96 GB
  Binaries:
    Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react-native: ^0.62.2 => 0.62.2
    react-native-windows: ^0.62.6 => 0.62.6
  Installed UWP SDKs:
    10.0.14393.0
    10.0.16299.0
    10.0.17134.0
    10.0.18362.0
```
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create native module to existing iOS/Android module folder
2. Creat example app to existing iOS/Android example folder
3. Link library
4. Build
5. See following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	APPX1111	Payload contains two or more files with the same destination path 'Microsoft.ReactNative.pdb', but they are different sizes. Source files: 
D:\B\example\node_modules\react-native-blurhash\node_modules\react-native-windows\target\x64\Debug\Microsoft.ReactNative\Microsoft.ReactNative.pdb
D:\B\example\node_modules\react-native-windows\target\x64\Debug\Microsoft.ReactNative\Microsoft.ReactNative.pdb	example	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets	1947	
```

![devenv_2020-09-03_21-09-10](https://user-images.githubusercontent.com/15199031/92156561-7a3b5500-ee29-11ea-964f-23803118c566.png)
> Screenshot of the Error List window in VS

![devenv_2020-09-03_21-09-22](https://user-images.githubusercontent.com/15199031/92156575-7f000900-ee29-11ea-85bd-57553eaa2738.png)
> Screenshot of the line causing those problems

### Note

If I delete `react-native-blurhash/node_modules` (which is the same as `react-native-blurhash/example/node_modules/react-native-blurhash/node_modules` because it's being linked there by yarn), I'm getting the following errors:

![devenv_2020-09-03_20-55-43](https://user-images.githubusercontent.com/15199031/92156750-bff81d80-ee29-11ea-9679-e1ea3445aa23.png)

## Expected Results

I expect the build to succeed.

## Snack, code example, screenshot, or link to a repository:

Here's the repo: https://github.com/mrousavy/react-native-blurhash/tree/support-windows
It's the native module [**react-native-blurhash**](https://github.com/mrousavy/react-native-blurhash) I'm trying to add windows support to. Any help would be appreciated, as I can't even build that thing anymore...

**Comment by chrisglein** [comment] 2020-09-10 18:29
First problem is that you ended up with two copies of react-native-windows. One in the blurhash node_modules and one hoisted to the root.
Build error seems to be that it can't find the winmd. The project may have hardcoded paths to the wrong node_modules location. So that link will need to be fixed.
@stmoy Another issue to the list to look at for native module documentation.
@jonthysell We have someone here trying to add Windows support to blurhash, can you look at what's going on (repo link above) and see if you can figure out where it went wrong.

**Comment by acoates-ms** [comment] 2020-09-10 18:44
Its not clear to me exactly how you want the example in this repo to work.  But it looks like there is a postInstall script on the examples package that tried to delete "rm -rf node_modules/react-native-blurhash/node_modules", which should have removed one of the copies you are hitting.

**Comment by mrousavy** [comment] 2020-09-12 12:13
@chrisglein Okay, I'll take a look at the hardcoded paths again, I'll try if I can fix that.

@acoates-ms Yeah, it should have removed that. I've got that script there because metro doesn't support symlinks, that's a workaround for that. And what exactly do you mean with `"Its not clear to me exactly how you want the example in this repo to work."`?

**Comment by jonthysell** [comment] 2020-11-18 01:10
@mrousavy I have a fix for the native build which gets your example app up and running, but I'm still getting JS/metro errors loading your module. I'll push a PR to your support-windows branch tomorrow morning.

**Comment by jonthysell** [comment] 2020-11-18 19:26
@mrousavy Draft PR here: https://github.com/mrousavy/react-native-blurhash/pull/94

I have some questions for you in that PR.

**Comment by jonthysell** [comment] 2020-11-18 23:40
Closing this.

For future devs who may find this bug - the general fix for having an example app with its own pacakage.json/node_modules in the same repo as their module, and therefore ending up with two copies of react-native-windows - is to update the `ReactNativeWindowsDir` property in the module's project:

```diff
<PropertyGroup>
-  <ReactNativeWindowsDir Condition="'$(ReactNativeWindowsDir)' == ''">$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), 'node_modules\react-native-windows\package.json'))\node_modules\react-native-windows\</ReactNativeWindowsDir>
+  <ReactNativeWindowsDir Condition="'$(ReactNativeWindowsDir)' == ''">$([MSBuild]::GetDirectoryNameOfFileAbove($(SolutionDir), 'node_modules\react-native-windows\package.json'))\node_modules\react-native-windows\</ReactNativeWindowsDir>	
</PropertyGroup>
```

**Closed by jonthysell** 2020-11-18 23:40 UTC
Labels: Area: Native Modules, Documentation, bug

**Comment by NickGerleman** [comment] 2020-11-18 23:50
If there are two copies of react-native-windows in the repo, dependencies somewhere in the tree are not configured correctly. Depending on the root cause of this, it's possible the module will not work correctly when used outside of the repo. We need to be very careful about this.

We should take a look at the lockfile to see why we have two RNW versions. Going to check that quickly.

**Comment by NickGerleman** [comment] 2020-11-19 00:02
Oh I see, we have a nested package inside of another, and instead of using yarn workspaces, we are symlinking dependencies. So there are two entirely different sets of resolved modules that are being symlinked together.

So, no module issues like some other repos, where we were doing things like having the module delcare a dependency instead of peer dependency, but the pattern of linking into a separate folder with separate resolved node_modules breaks a lot of assumptions. Some dependencies, like `react`, assume only a single version of it is ever included, so having two separate trees of node_modules could break other things.

So, yep, not a problem with RNW, and not a problem with the community module itself, but a repo set up with this pattern is likely to run into issues.
