### ISSUE TITLE
[0.66+] App freeze on UWP resume after 5 min of suspension

### ISSUE THREAD

**Issue by Chris-Guy** [microsoft/react-native-windows#11070] opened 2023-01-10 17:33 UTC
### Problem Description

Hello,

After the upgrade from 0.64 to 0.70 of the PowerApps Windows app, Windows 10 devices would experience a freeze for the application during several minutes or hours on UWP resume. It does not reproduce on the latest Windows 11 version, even if it looks like old versions of W11 might have it (to be checked)
See video (MSFT internals only) for a simple Power App: [demo](https://microsofteur-my.sharepoint.com/:v:/g/personal/chguy_microsoft_com/ETSH1fQ1uhtGlthvFmE90JEBjUgTz6Zumpboq7JngdfTaQ?e=hpOGDo)- At the beginning, I minimize the UWP app for suspension
- At 5:34, I resume the app. You can see that the UI is not responsive to the windows, and no button is working. Double clicking anywhere on the app expand it.
- At 9:55, the app finally come back from the freeze.

Remark: PowerApps production version has reverted the upgrade since then to 0.64, but we have some features relying on this new version. Also, the master branch is now forked due to that, reducing our release velocity there.

I am trying to get a minimal reproduction, but currently I cannot build the react-native-gallery app, so looking at fixing my issues there.

### Steps To Reproduce

1. Get the latest version of the Power Apps Windows app (from App Center)
2. Open a Power App (which leverages a react-native full window control)
3. Minimize the app to go to suspension
4. Expand and resume the app after 5 minutes

### Expected Results

No app freeze

### CLI version

9.2.1

### Environment

```markdown
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
    Memory: 18.78 GB / 31.92 GB
  Binaries:
    Node: 14.21.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0, 10.0.20348.0, 10.0.22000.0, 10.0.22621.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.4.33205.214 (Visual Studio Enterprise 2022), 16.11.33130.400 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: 9.2.1 => 9.2.1
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-windows: 0.70.4 => 0.70.4
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

DebugBundle

**Comment by chrisglein** [comment] 2023-01-12 19:15
In your repro video it looks like you've got a yellow box warning and some redux tools running. So this is a debug build (as you say, DebugBundle)... does it show the exact same behavior in release builds? Same timing and such? 

Have you broken into the debugger on this to see if there is any odd behavior on the main thread or others? For those 5 minutes, what are the main threads doing?

FWIW it looks like you're using VS2022 on version 0.70. That's only officially supported in 0.71+ (currently in preview). Probably not the issue here, but just an FYI.

It's a huge jump from 0.64 to 0.70 so it's hard to narrow down what could have happened between there (multiple years of releases). Some debugging information from your end may help narrow this down.

**Comment by Chris-Guy** [comment] 2023-01-13 15:46
Hello, the issue was first raised by a customer with the app from the Microsoft Store, so it happens also in release builds with the same timing.

So, due to the Sev 0 on Windows my VS setup is all messed up (I am trying to repair it). I am currently trying to get as much information as possible and also a minimum repro in parallel, I'll get back to you on that. 

We are using a mono repo with multiple RN apps and libraries, that is why it is not easy for us to do the upgrade, and due to that we generally perform big jumps. 

I was wondering if you had any verbose logging parameter so that we can see what RNW is potentially doing during this freeze?

**Comment by Chris-Guy** [comment] 2023-01-17 14:56
I had some time today:
- when attaching the native debugger during the freeze, it will actually "unblock" the freezing, resulting in the app working again :/
- when debugging only the Managed code, the main thread is in "External Code" (which probably means the native code).

I tried to repro on a C#-based RNW 0.70 app, effectively I don't manage to get the same issue.
Right now we are trying to downgrade RNW to close previous versions that wouldn't have this issue (0.69, 0.68, etc.), but it is tedious and requires some time for us. I'll keep you in touch!

**Comment by Chris-Guy** [comment] 2023-01-20 16:00
> Can you have it attached from the beginning so that you can break in at the time of the freeze rather than attaching? (disrupting the state less)
No, probably because it might be related to UWP lifecycle events (Suspension event with debugger attached is not a real suspension).

I was able to pinpoint the regression from 0.65.14 to 0.66.25 update. I am trying to track down the commits (0.66.0 still has the issue). Do you have any idea of possible changes from this version range?

**Comment by chrisglein** [comment] 2023-02-06 18:40
> I am trying to track down the commits (0.66.0 still has the issue). Do you have any idea of possible changes from this version range?

Not off the top of my head. That was a couple years ago at this point? Great that you were able to narrow down what was causing the change in behavior for you, but we've paged out the details of that window at this point.

**Comment by tero-paananen** [comment] 2023-02-15 07:07
I have noted this case also now. Our app freezes when activated from minimized state about 3-10 seconds or forever. We are using RNW 0.70.10

**Comment by Chris-Guy** [comment] 2023-02-15 13:16
Thanks for sharing the concern @tero-paananen ! One quick question: do you have any specific usage (list of RN packages you use, or for example if you use the WebView2 component?).
This would help me try to reduce the scope of the root cause and find the right culprit here. I am still investigating :)

**Comment by tero-paananen** [comment] 2023-02-15 13:35
> Thanks for sharing the concern @tero-paananen ! One quick question: do you have any specific usage (list of RN packages you use, or for example if you use the WebView2 component?). This would help me try to reduce the scope of the root cause and find the right culprit here. I am still investigating :)

I am using WebView2 but after disabling usage of it i have still that issue. We have quite many modules in use. I try to investigate this also more. I can re-produce this issue only with release build store package (Publish->Create app packages)

**Comment by tero-paananen** [comment] 2023-02-15 13:43
App have to be really get as suspended state and then to back to running to reproduce it (see state for example from Task Manager's Details tab)

**Comment by tero-paananen** [comment] 2023-02-16 05:53
`grep -R "AppState.addEventListener(" *`

```
@react-native-community/hooks/lib/useAppState.js:        var subscription = react_native_1.AppState.addEventListener('change', onChange);
@react-native-community/netinfo/README.md:    const subAppState = AppState.addEventListener("change", async (nextAppState) => {
react-native-inappbrowser-reborn/utils.js:    appStateEventSubscription = AppState.addEventListener(
react-native-permissions/README.md:  const listener = AppState.addEventListener('change', (status) => {
react-native-push-notification/index.js:  AppState.addEventListener('change', handlePopInitialNotification.bind(this));
```

**Comment by Chris-Guy** [comment] 2023-02-16 10:15
@tero-paananen this is interesting. 
We have @react-native-community/netinfo and react-native-permissions, but patching these dependencies not to register any listeners through AppState (I commented all the lines with AppState.addEventListener) still reproduce the issue for me. 
You created the app with the react-native CLI? Are you using the C# or the C++ template?
Because what is surprising for us is that we are an hybrid UWP/RN app (we have a full screen RN page, but there are other pages that are not RN), but we also have a custom top bar with the RN page that seems to be affected by the UI freeze.
So it probably means that something is blocking in the UI thread. 

The RN Gallery app seems to work fine (I cannot the reproduce the issue there).

**Comment by tero-paananen** [comment] 2023-02-16 11:57
We have C# template app (RNW 0.70.10) created years ago via react-native init.

NetInfo may do something that causes this issue i think. How about this continues running timer in it:
https://github.com/react-native-netinfo/react-native-netinfo/blob/3e251ab08a4b6d9cbe4709c5fa24dbdfc96eced6/src/internal/internetReachability.ts#L71

We have patch to remove this line from C++ side:
https://github.com/react-native-netinfo/react-native-netinfo/blob/3e251ab08a4b6d9cbe4709c5fa24dbdfc96eced6/windows/RNCNetInfoCPP/RNCNetInfo.cpp#L169
But putting this line back may not help. This line stuck app startup on Windows 11 read more from https://github.com/react-native-netinfo/react-native-netinfo/issues/647

**Comment by Chris-Guy** [comment] 2023-02-16 18:11
I tried to remove netinfo package and I replaced it with a mock returning Connected in Wifi, it looks like the freeze last few seconds only now, so that might be the root cause.
Have you tried to do the same @tero-paananen ?

**Comment by tero-paananen** [comment] 2023-02-16 19:09
> I tried to remove netinfo package and I replaced it with a mock returning Connected in Wifi, it looks like the freeze last few seconds only now, so that might be the root cause.
> Have you tried to do the same @tero-paananen ?

I tried the same and it freezes mainly about 3 seconds but there was longer freeze also. I have to test it again and validate that Netinfo module is not even loaded.

**Comment by tero-paananen** [comment] 2023-02-16 19:11
I would like to try without previousRequest and without this lock

https://github.com/react-native-netinfo/react-native-netinfo/blob/3e251ab08a4b6d9cbe4709c5fa24dbdfc96eced6/windows/RNCNetInfoCPP/RNCNetInfo.cpp#L159

**Comment by tero-paananen** [comment] 2023-02-17 07:26
Without Netinfo module in my project i manage to get UI to freeze still

**Comment by Chris-Guy** [comment] 2023-02-17 09:31
Looks tedious. Have you tried to bundle the package? I am able to reproduce in Debug, and to trigger suspension I just need to minimize the UWP app window explicitly. Then from the Task Manager you can see that from the icon that the process is suspended: 
![image](https://user-images.githubusercontent.com/6816661/219606806-8adcd18e-ee24-4820-aa03-666a07db707e.png)

**Comment by Chris-Guy** [comment] 2023-02-17 09:32
Concerning NetInfo, because we still have a freeze of few seconds I don't think this is the root cause in the end.

**Comment by Chris-Guy** [comment] 2023-02-17 15:05
@tero-paananen , trying to know if the JS engine was frozen or executing something else, I have made a setInterval call with a console log, it looks like I don't reproduce the freeze anymore.
Based on that, I have built a "workaround" building the following code:
```
AppState.addEventListener('change', (nextAppState: AppStateStatus) => {
      console.log("AppState " + nextAppState);
      if (nextAppState != "active"){
      this.intervalPing = setInterval(() => { console.log("interval check");}, 1000);
    } else {
      if (this.intervalPing !== undefined) {
        clearInterval(this.intervalPing);
        this.intervalPing = undefined;
      }
    }
  });
```
And, it's been my third try with a minimize/restore and I don't reproduce the freeze anymore. Can you try if it solve your issue? If it is the same, it means it is either linked to the JS timer (setInterval) or the console.log doing something wrong...

**Comment by tero-paananen** [comment] 2023-02-17 15:19
Very interesting. Your code keeps somehow js engine running on suspend state (really possible?) I will continue with this issue on next week and test your hack also.

Our app has by the way Hermes enabled....i will test without it also.

**Comment by Chris-Guy** [comment] 2023-02-17 15:30
Not really @tero-paananen , because if you just test with `setInterval(() => console.log("test"), 1000)`, what you will see in the console logs is that on UWP suspension, the JS engine is paused as test logs are not appearing in the Metro console.
I think we just have a nice side-effect with setInterval, which removes the freeze here. Maybe RNW timer code is waking up the different threads / executing code that avoids our issue.

**Comment by tero-paananen** [comment] 2023-02-17 20:22
@Chris-Guy quess what!!! That issue does not exist on Windows 11 22H2

**Comment by Chris-Guy** [comment] 2023-02-17 20:47
@tero-paananen so when you are saying that, you mean without doing any code change?

**Comment by tero-paananen** [comment] 2023-02-17 20:55
> @tero-paananen so when you are saying that, you mean without doing any code change?

Without any code change. There is even no that bottom of app window flickering

**Comment by tero-paananen** [comment] 2023-02-20 07:57
When i activate our app on release build connected with Visual Studio i can see output log `WinRT originate error - 0x8001010E : 'DispatcherQueueController is already created on this thread.'.` When doing same with HelloWorld there is no that kind of log.

**Comment by tero-paananen** [comment] 2023-02-20 11:54
It is challenging to try to build tester HelloWorld app that get stuck also on suspend to active state. I did some but did not manage to stuck it still. 

Tester has:
- 2 WebViews and another uses webview2
- Hermes enabled
- Listens AppState changes
- On active state makes fetch request
- On background state makes fetch request
- Creates 200 test Views into ScrollView

**Comment by Chris-Guy** [comment] 2023-02-20 13:05
@tero-paananen You're still searching but with older Windows versions (Windows 10)?

**Comment by tero-paananen** [comment] 2023-02-21 08:18
@Chris-Guy  Currenlty i have not found for solution for this. Your workaround seems to help us at least currently.

**Comment by Chris-Guy** [comment] 2023-02-21 09:34
@tero-paananen Thanks for confirming the workaround. @jonthysell from RNW team will investigate to find the root cause here (btw @jonthysell feel free to reach out to me if you need help to repro), while I think having this workaround in the meantime is good.

**Comment by jonthysell** [comment] 2023-04-26 23:18
Since we have a workaround and there's no easy way to debug this, moving to the backlog

**Closed** 2024-10-21 22:50 UTC
Labels: bug, Partner: Microsoft, Recommend: Not Planned
