### ISSUE TITLE
Add SourceLink support to vnext for automatic symbol and source loading while debugging

### ISSUE THREAD

**Issue by RobMeyer** [microsoft/react-native-windows#3766] opened 2019-12-12 18:12 UTC
[Source Link](https://github.com/dotnet/sourcelink) is a technology built by VS and officially supported by Microsoft to enable automatic source loading while debugging. 

RNW should integrate Source Link to improve the debugging experience for projects consuming RNW. 

For reference, it was integrated into winui in this pull request https://github.com/microsoft/microsoft-ui-xaml/pull/606

**Comment by licanhua** [comment] 2019-12-12 21:46
Example to publish symbols: https://github.com/microsoft/microsoft-ui-xaml/blob/master/tools/PublishSymbols

**Comment by chrisglein** [comment] 2019-12-13 19:12
This specifically would be for the nuget, because otherwise we ship as source. At least for now.

**Comment by asklar** [comment] 2020-04-13 09:12
@chrisglein this is a dupe of #4551 which is a dupe of #4377

**Comment by chrisglein** [comment] 2020-04-13 16:55
@asklar #4377 is a bit broad where this issue at least is more specific and immediately (hook up SourceLink, following the steps in the linked WinUI PR). #4551 does appear to be a true dupe, which I should have caught (Vlad opened ~20 issues to track his own work and they were bulk triaged instead of going through the normal triage process).

**Comment by jonthysell** [comment] 2020-05-13 21:38
This is effectively blocked until we get #4546 complete E2E. Right now everyone downloads and builds the RNW source and so already has both it and the symbols.

**Comment by RobMeyer** [comment] 2020-05-13 21:52
That's unfortunately not true, @jonthysell. We're getting RNW binaries from the OfficeISS package. There is an effort to switch from React.UWP to React.Windows (which might change how we get/build binaries?) but there are other blocking issues, I'm told.

**Comment by jonthysell** [comment] 2020-05-13 21:55
The new package is only accessible internally to office. Are you building on top of ReactUWP or Microsoft.ReactNative?

**Comment by RobMeyer** [comment] 2020-05-14 16:52
Yeah, we're in Office (Mail & Calendar Preview app). We're currently on React.UWP. We want to move to Microsoft.ReactNative but I'm told there are some blocking issues that we're working with your team on (I'm a little out of the loop -- Stanley and Ken know more)

**Comment by jonthysell** [comment] 2020-08-12 16:23
This was completed by #5533.

**Closed by jonthysell** 2020-08-12 16:23 UTC
Labels: Area: Debug Infrastructure
