### ISSUE TITLE
Provide an implementation for AccessibilityInfo

### ISSUE THREAD

**Issue by rigdern** [Microsoft/react-native-windows#1097] opened 2017-04-21 04:59 UTC
Currently, it's just a stub: https://github.com/Microsoft/react-native-windows/blob/199a835aab8e7570666687426dfc13c881752484/Libraries/Components/AccessibilityInfo/AccessibilityInfo.windows.js

Here are the docs for the module: http://facebook.github.io/react-native/releases/0.43/docs/accessibilityinfo.html#accessibilityinfo

**Comment by rozele** [comment] 2017-06-30 01:20
Closing as dupe of #1051

**Closed by rozele** 2017-06-30 01:20 UTC
