### ISSUE TITLE
DevSupportManager illegally calls HttpClient from an STA

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5073] opened 2020-05-31 02:25 UTC
`\vnext\Desktop\DevSupportManager.cpp`

```cpp
string DevSupportManager::GetJavaScriptFromServer(
    const string &debugHost,
    const string &jsBundleName,
    const string &platform) {
  auto bundleUrl =
      DevServerHelper::get_BundleUrl(debugHost, jsBundleName, platform /*platform*/, "true" /*dev*/, "false" /*hot*/);
  Uri uri(Common::Unicode::Utf8ToUtf16(bundleUrl));
  Filters::HttpBaseProtocolFilter filter;
  filter.CacheControl().ReadBehavior(Filters::HttpCacheReadBehavior::NoCache);
  HttpClient client(filter);
  client.DefaultRequestHeaders().Host(HostName(uri.Host().c_str()));

  HttpRequestMessage request(HttpMethod::Get(), uri);
  HttpResponseMessage response = client.SendRequestAsync(request).get();
```

is being called from an STA thread which is illegal as it can hang the app. This hits an assert in Debug.

**Comment by chrisglein** [comment] 2020-06-01 18:22
Sounds like this will only affect development scenarios, not retail.
@JunielKatarn as an FYI. Sounds like there might be something in the UWP implementation that can be copied.

**Comment by chrisglein** [comment] 2020-06-01 18:23
Was hit running desktop integration tests.

**Comment by JunielKatarn** [comment] 2020-06-02 01:34
Noted!

There is also a task to attempt merging the implementations (Universal, Desktop) for they serve exactly the same purpose.

Please note the previous implementation also did the HTTP call from the owning (UI) thread, though never hanging the app permanently.

**Comment by acoates-ms** [comment] 2020-07-15 21:16
This specific code should be fine.  This code should never be run on an STA thread, so if it is being hit on an STA then the root of why that is should be identified.

The specific code in desktop has been deleted, so I think we can probably close this issue.

**Comment by JunielKatarn** [comment] 2020-07-17 01:01
@acoates-ms Can we close this as "by design"?

**Closed** 2020-07-17 01:02 UTC
Labels: Platform: Desktop, bug
