### ISSUE TITLE
[Gamepad] Cannot invoke TouchableHighlight or TouchableOpacity content

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#2182] opened 2019-03-21 16:53 UTC
Using the Xbox controller (gamepad), I cannot invoke any content wrapped with TouchableHighlight or TouchableOpacity using the A button.

**Comment by ahimberg** [comment] 2019-03-21 18:30
How does xbox A button event come in?  We currently only support click via mouse/pointer events, keyboard input looking at space/enter, and accessibility invoke.  There must be some additional event to hook in ViewViewManager::CreateViewControl that should be simple

**Comment by micahl** [comment] 2019-04-30 19:17
This issue seems like a dupe of #2085.

**Comment by harinikmsft** [comment] 2019-05-30 22:33
Using #2085 to track this work in addition to keyboard.

**Closed by harinikmsft** 2019-05-30 22:33 UTC
Labels: vnext
