### ISSUE TITLE
NativeAnimatedModule missing implementation of updateAnimatedNodeConfig

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#10731] opened 2022-10-13 19:57 UTC
NativeAnimatedModule implementation is incomplete and is missing the `updateAnimatedNodeConfig` method.  This prevents the module from being able to turn on using the codegen'd Spec.

**Comment by rozele** [comment] 2022-10-16 17:44
Looks like this is only being used in AnimatedColor.js, so we can probably coalesce this issue with https://github.com/microsoft/react-native-windows/issues/9493

**Comment by chrisglein** [comment] 2022-10-17 18:06
Duplicate of #9493

**Closed** 2022-10-17 18:06 UTC
Labels: Needs: Triage :mag:, enhancement, Area: Animation, API: Completion
