### ISSUE TITLE
Errors running "react-native run-windows"

### ISSUE THREAD

**Issue by eljamaki01** [Microsoft/react-native-windows#1597] opened 2018-01-22 19:08 UTC
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.52.1

2. `npm ls rnpm-plugin-windows`:
myapp@0.0.1 C:\Users\eljam\Downloads\myapp
`-- rnpm-plugin-windows@0.2.8

3. `npm ls react-native-windows`:
myapp@0.0.1 C:\Users\eljam\Downloads\myapp
`-- react-native-windows@0.52.0-rc.0

4. `node -v`:
v8.9.3

5. `npm -v`:
5.5.1

6. `yarn --version`:
I don't

Then, specify:

- Target Platform:
UWP

- Target Platform Version(s):

- Target Device(s):

- Development Operating System:
Windows 10 

- Visual Studio Version:
2017

### Steps to Reproduce

Run the following commands:
npm install -g react-native-cli
react-native init myapp
cd myapp
npm i --save-dev rnpm-plugin-windows
react-native windows
react-native run-windows

On running this last command I get errors. Here is the head portion of those errors:
C:\Users\eljam\Downloads\myapp>react-native run-windows
Scanning folders for symlinks in C:\Users\eljam\Downloads\myapp\node_modules (37ms)
Restoring NuGet packages
Building C:/Users/eljam/Downloads/myapp/windows/myapp.sln
Found MSBuild v15.0 at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
Building Solution: C:/Users/eljam/Downloads/myapp/windows/myapp.sln
Build configuration: Debug
Build platform: x86
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Properties\AssemblyInfo.cs(8,12): error CS0246: The type or namespace name 'AssemblyTitleAttribute' could not be found
(are you missing a using directive or an assembly reference?) [C:\Users\eljam\Downloads\myapp\node_modules\react-native
-windows\ReactWindows\ReactNativeWebViewBridge\ReactNativeWebViewBridge.csproj]
Properties\AssemblyInfo.cs(8,12): error CS0246: The type or namespace name 'AssemblyTitle' could not be found (are you
missing a using directive or an assembly reference?) [C:\Users\eljam\Downloads\myapp\node_modules\react-native-windows\
ReactWindows\ReactNativeWebViewBridge\ReactNativeWebViewBridge.csproj]
Properties\AssemblyInfo.cs(9,12): error CS0246: The type or namespace name 'AssemblyDescriptionAttribute' could not be
found (are you missing a using directive or an assembly reference?) [C:\Users\eljam\Downloads\myapp\node_modules\react-
native-windows\ReactWindows\ReactNativeWebViewBridge\ReactNativeWebViewBridge.csproj]

**Comment by jbcullis** [comment] 2018-01-28 00:55
I'm having the same problem, did you find a fix?

**Comment by jbcullis** [comment] 2018-01-28 01:01
<img width="629" alt="targeting" src="https://user-images.githubusercontent.com/27532334/35477915-cb28f74e-039c-11e8-9e51-09fb056367e5.png">

Edited the targeting on the web bridge project and now builds.

**Comment by Abhinav-Sharan** [comment] 2018-01-28 11:28
same error here

**Comment by plasticbraindotcom** [comment] 2018-01-30 02:37
I'm seeing the exact same issue as well, and can't resolve it. OP steps to reproduce still exhibit the issue.

@jbcullis Your suggestion isn't clear to me. I've set all the targets for the project and enclosed libraries to match 10.0 Build 14393 but it does not solve the problem.

**Comment by activebiz** [comment] 2018-07-16 10:40
I am getting same error. The above fix does not work!

**Comment by rozele** [comment] 2018-07-23 22:12
Can you run `react-native run-windows --verbose` and drop the output somewhere? It looks like NuGet restore is failing, but hard to tell from the pasted logs.

**Comment by HerrX2000** [comment] 2019-01-14 11:50
> 
> $ react-native run-windows --verbose                                             Restoring NuGet packages                                                         MSBuild auto-detection: using msbuild version '15.9.21.664' from 'D:\Program Fil es (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.               Restoring packages for D:\Android\Project\CleanProject\windows\CleanProject\Clea nProject.csproj...                                                               Restoring packages for D:\Android\Project\CleanProject\node_modules\react-native -windows\ReactWindows\ReactNative\ReactNative.csproj...                          Restoring packages for D:\Android\Project\CleanProject\node_modules\react-native -windows\ReactWindows\ReactNativeWebViewBridge\ReactNativeWebViewBridge.csproj.. .                                                                                Committing restore...                                                            Lock file has not changed. Skipping lock file write. Path: D:\Android\Project\Cl eanProject\node_modules\react-native-windows\ReactWindows\ReactNativeWebViewBrid ge\obj\project.assets.json                                                       Restore completed in 3,51 sec for D:\Android\Project\CleanProject\node_modules\r eact-native-windows\ReactWindows\ReactNativeWebViewBridge\ReactNativeWebViewBrid ge.csproj.                                                                       Committing restore...                                                            Committing restore...                                                            Lock file has not changed. Skipping lock file write. Path: D:\Android\Project\Cl eanProject\windows\CleanProject\obj\project.assets.json                          Restore completed in 3,94 sec for D:\Android\Project\CleanProject\windows\CleanP roject\CleanProject.csproj.                                                      Lock file has not changed. Skipping lock file write. Path: D:\Android\Project\Cl eanProject\node_modules\react-native-windows\ReactWindows\ReactNative\obj\projec t.assets.json                                                                    Restore completed in 3,94 sec for D:\Android\Project\CleanProject\node_modules\r eact-native-windows\ReactWindows\ReactNative\ReactNative.csproj.                                                                                                  NuGet Config files used:                                                             C:\Users\Freddy\AppData\Roaming\NuGet\NuGet.Config                               C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config                                                                                     Feeds used:                                                                          https://api.nuget.org/v3/index.json                                              C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\                         Build failed with message Error: Must have a minimum Windows SDK version 10.0.10 586.0 installed. Check your build configuration.
> --
> 
> 
>

**Comment by GreenRidingHood** [comment] 2019-02-06 20:24
@eljamaki01 , @db-rdz solution worked for me https://github.com/Microsoft/react-native-windows/issues/1593

**Comment by rozele** [comment] 2019-02-26 04:37
Closing. This issue is quite out of date. We've recently updated the minimum target version for React Native Windows to 10.0.14393.

**Closed by rozele** 2019-02-26 04:37 UTC
