### ISSUE TITLE
react-native-fs not linking for Windows

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/react-native-windows#1576] opened 2018-01-12 03:40 UTC
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.52.0

2. `npm ls rnpm-plugin-windows`:
APPNAMEREMOVED@0.0.1 C:\Projects\Partners\APPNAMEREMOVED
`-- (empty)

3. `npm ls react-native-windows`:
APPNAMEREMOVED@0.0.1 C:\Projects\Partners\APPNAMEREMOVED
`-- UNMET DEPENDENCY react-native-windows@0.50.0

npm ERR! missing: react-native-windows@0.50.0, required by APPNAMEREMOVED@0.0.1

4. `node -v` :v9.3.0
5. `npm -v`: 5.5.1
6. `yarn --version`:

Then, specify: 1.3.2

- Target Platform: UWP

- Target Platform Version(s): 10.0.14393 (UWP)

- Target Device(s): Desktop

- Development Operating System: Windows

- Visual Studio Version: 2017

### Steps to Reproduce

(Write your steps here:)

1. Take a dependency on https://github.com/itinance/react-native-fs
2. Execute: react-native link react-native-fs

### Expected Behavior
Native library to link for Windows.

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

It failed (app name obfuscated):

C:\Projects\Partners\APPNAMEREMOVED>react-native link react-native-fs
Scanning folders for symlinks in C:\Projects\Partners\APPNAMEREMOVED\node_modules (99ms)
rnpm-install info Android module react-native-fs is already linked
rnpm-install info iOS module react-native-fs is already linked
rnpm-install ERR! Something went wrong while linking. Error: ENOENT: no such file or directory, open 'C:\Projects\Partners\APPNAMEREMOVED\windows\APPNAMEREMOVED\MainPage.cs'
Please file an issue here: https://github.com/facebook/react-native/issues

It is correct in that I do not see a MainPage.cs file in my project.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rozele** [comment] 2018-02-08 14:25
Dupe of #1578

**Closed by rozele** 2018-02-08 14:25 UTC
