### ISSUE TITLE
Could not find react-native-windows@0.56.*. Latest version of react-native-windows is 0.55.0.rc.0

### ISSUE THREAD

**Issue by spointeau** [Microsoft/react-native-windows#1943] opened 2018-08-18 10:35 UTC
Following the "GettingStarted" to start a project, 

> react-native init <project name>
> cd <project name>
> react-native windows

I had the error message: "Could not find react-native-windows@0.56.*. Latest version of react-native-windows is 0.55.0.rc.0, try switching to react-native@0.55.*."

actually we have to do:
> react-native initi --version="react-native@0.55.4" <project name>

Can this be updated in the "GettingStarted" section?

When will react-native-windows support react-native 0.56?

**Comment by npmun** [comment] 2018-08-18 16:53
Refer to #1893

**Comment by rozele** [comment] 2018-08-20 20:18
Closing as dupe of #1893 - there will not be a release aligning with react-native@0.56 due to unresolved issues with metro. The next release of react-native-windows will target react-native@0.57 once https://github.com/facebook/react-native/commit/c5297c75cb6da58a241c8f91b0d2fefbc5835a46 is cherry-picked (refer to https://github.com/react-native-community/react-native-releases/issues/34 for further discussion)

**Closed by rozele** 2018-08-20 20:18 UTC

**Comment by xtianus79** [comment] 2018-09-06 20:27
what is the workaround now?
