### ISSUE TITLE
E2ETest:  Add WaitForIdle functionality

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#5841] opened 2020-08-25 23:16 UTC
Currently the E2E tests have a lot of polling/timeout logic in them, due to the lack of synchronization between the jasmine/appium side of the test and the native side of the test.  This polling is inefficient and somewhat brittle.

XAML tests have a WaitForIdle utility that we use to avoid this sort of polling logic.  This task is tracking adding WaitForIdle to our E2E test infrastructure.

We'll need to do two basic things here:
1) Copy the underlying WaitForIdle functionality from XAML.  This has the logic to wait for the XAML tree to stabilize
2) Expose this functionality somehow to the jasmine side of things.  We may be able to accomplish this with a native module, or by extending WinAppDriver (was prototyped in hackathon 2019).  This needs some investigation.

**Comment by asklar** [comment] 2020-08-26 02:12
dupe of #3779 ?

**Comment by kmelmon** [comment] 2020-11-20 21:42
This is now part of https://github.com/microsoft/react-native-windows/projects/39 and may depend on #5841

**Comment by rectified95** [comment] 2021-03-05 00:11
@NickGerleman Is this still necessary after your changes to the e2e infra?

**Closed** 2023-09-19 23:13 UTC
Labels: enhancement, Area: Test Infrastructure, Story: ⚙ Quality
