### ISSUE TITLE
View prop borderStyle: 'dashed' not working

### ISSUE THREAD

**Issue by syedibrahimt** [microsoft/react-native-windows#6931] opened 2021-01-22 20:52 UTC
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
2. `npx react-native info`:

- Target Platform Version(s): **10.0.19041.0**
- Target Device(s): **Desktop**
- Visual Studio Version: **Visual Studio 2019**

## Steps To Reproduce
Sample code below

`<View
            style={{
              width: 400,
              height: 500,
              borderRadius: 3,
              borderColor: '#0093d1',
              borderWidth: 3,
              borderStyle: 'dashed'
            }} />`

## Expected Results
Border should be in the Dashed format

**Comment by syedibrahimt** [comment] 2021-01-22 20:59
@stmoy   can you please help me with this.

**Comment by NickGerleman** [comment] 2021-01-23 00:00
I believe this is not yet implemented. Related issue: https://github.com/microsoft/react-native-windows/issues/3078

**Comment by syedibrahimt** [comment] 2021-01-23 19:08
@NickGerleman  Any Workaround to achieve dashed border?

**Comment by chrisglein** [comment] 2021-01-25 19:27
There's a comment in #3078 to the `Rectangle` documentation. You could with the native APIs include a Rectangle (or other Shape) that sets a dashed stroke. Not ideal, but that's the available workaround until #3078 is completed.

Duplicate of #3078. Go ahead and add any more details to that issue.

**Closed by chrisglein** 2021-01-25 19:27 UTC
Labels: Needs: Triage :mag:, bug
