### ISSUE TITLE
Scrollbar indicator never goes away once it is shown.

### ISSUE THREAD

**Issue by lamxdoan** [microsoft/react-native-windows#6782] opened 2020-12-18 22:48 UTC
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.13.1
2. `npx react-native info`: 
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
    Memory: 16.04 GB / 31.92 GB
  Binaries:
    Node: 11.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.16299.0, 10.0.17134.0, 10.0.17749.0, 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 15.9.28307.1321 (Visual Studio Enterprise 2017), 16.8.30804.86 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
    Python: 2.7.15 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.14

- Target Platform Version(s): 10.0.18362
- Target Device(s): Desktop
- Visual Studio Version: VS 2019
- Build Configuration: Debug, DebugBundle, Release, ReleaseBundle 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a brand new project which contains a ScrollView inside.
2. Launch the app
3. Scroll the scrollviewer, click away, come back scroll the scrollviewer again. (Do this several times)
4. Notice that the scroll bar indicator shows and never goes away.

## Expected Results
The scroll bar indicator should eventually go away once mouse hover / focus leaves the app.

![image](https://user-images.githubusercontent.com/59846506/102668095-ebd0b200-413f-11eb-8ec5-4dc95588cf91.png)

**Comment by lamxdoan** [comment] 2020-12-18 22:49
Note: also seeing this in our production app

**Comment by asklar** [comment] 2020-12-19 02:47
can you check this setting in Settings:
![image](https://user-images.githubusercontent.com/22989529/102679060-8392c800-4161-11eb-89f6-1860c8edfc76.png)

**Comment by lamxdoan** [comment] 2021-01-05 00:23
@asklar I verified that the setting is turned on. This bug doesn't repro on 0.60 and we started noticing it after upgrading to 0.63.

**Comment by rectified95** [comment] 2021-01-07 19:36
Taking a quick look, the relevant code in ScrollViewManager.cpp has not changed since v0.60 - we still by default set 
```cpp
scrollViewer.VerticalScrollBarVisibility(winrt::ScrollBarVisibility::Auto);
```
overriding XAML's default of `Visible` meaning this should work, combined with the setting Alex referenced.

**Comment by rectified95** [comment] 2021-01-07 19:42
Verified that this works on 0.64.0-preview.3. Checking v63 now

**Comment by rectified95** [comment] 2021-01-07 19:53
It also works for me on the reported version of 0.63.14
Closing this issue as not reproduced. cc @chrisglein 

@lamxdoan make sure you are not setting `showsVerticalScrollIndicator` on the component, which would make it permanently visible. (ref: https://github.com/microsoft/react-native-windows/blob/df49e9bae0cc355294d8088c533fae139211c5f2/vnext/ReactUWP/Views/ScrollViewManager.cpp#L155-L159)

Just for my curiosity - does the scrollbar never disappear for you, or does it stop disappearing after doing it several times?

**Closed by rectified95** 2021-01-07 19:53 UTC
Labels: Area: ScrollView, Good First Task, bug

**Comment by lamxdoan** [comment] 2021-01-07 20:23
@rectified95 I wonder if it's depends on OS version as well and/or WinUI. We are definitely not setting the verticalScrollBarVisibility (I also verified using the XAML tree explorer). The scrollbar initially does not show but if I hover over it once and move away then it will show and stay that way.

**Comment by rectified95** [comment] 2021-01-11 08:24
@lamxdoan I tested it on build 19042.685, version 20H2, feature exp. pack 120.2212.551.0, XAML: Microsoft.UI.Xaml.2.3_2.32002.13001.0
Could you try creating a XAML app with one ScrollViewer and see if it acts correctly?
