### ISSUE TITLE
Guidance for SqlLite

### ISSUE THREAD

**Issue by robertev** [microsoft/react-native-windows#6048] opened 2020-09-21 15:57 UTC
I have a customer that needs SqlLite support in their RN4W app... what is the best path? 

I see this project but it has not been updated in over a year... recommendations? what is the best path?

https://github.com/andpor/react-native-sqlite-storage/tree/master/platforms/windows

There is also async-storage/windows/ReactNativeAsyncStorage - but does that support SQLLite? Guidance?

**Comment by asklar** [comment] 2020-09-21 16:51
related: #6033

**Comment by chrisglein** [comment] 2020-09-21 18:13
Yep, we've changed up our community module story as version 0.60 and modules written for 0.59 need to be updated. So this is just a matter of someone doing the work. Given there's a C# implementation from before it should be easier than most. 

Let's carry the discussion over on the dupe.

Duplicate of #6033

**Closed by chrisglein** 2020-09-21 18:13 UTC
Labels: Extensions, Needs: Triage :mag:
