### ISSUE TITLE
LocationObserverModule will Fail Thread Checks

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6037] opened 2020-09-20 12:05 UTC
This uses react::uwp::BatchingMessageQueue created on the UI thread, and will fail thread checks as BatchingMessageQueue is itself weirdly thread-affined. We also seem to be using it like it should be the NM thread, even though it's not. Likely an artifact of the MSRN migration.

**Comment by NickGerleman** [comment] 2020-09-20 12:10
There's a fun comment at the bottom here

```c++
  modules.emplace_back(
      LocationObserverModule::name,
      [messageQueue]() { return std::make_unique<LocationObserverModule>(messageQueue); },
      MakeSerialQueueThread()); // TODO: figure out threading
```

**Comment by chrisglein** [comment] 2020-09-21 18:22
Duplicate of #6038

**Closed by chrisglein** 2020-09-21 18:22 UTC
Labels: Needs: Triage :mag:
