### ISSUE TITLE
Add focusable to Pressable

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#5512] opened 2020-07-13 17:29 UTC
From [Keyboarding in React Native Desktop](https://microsoft-my.sharepoint-df.com/:w:/r/personal/harinik_microsoft_com/_layouts/15/guestaccess.aspx?e=vboyhr&wdLOR=c797FF090-3702-4FEE-AD68-1E204281FFD9&share=EY4TcWAvR4tKu7EjxUG7OcwBkIHpcehA26atyX4BTwCYLw) document:

> Property that determines whether this View, Touchable should be focusable with a non-touch input device, eg. receive focus with a hardware keyboard. Setting the property to true will make that View compoonent become a part of tabbing loop. 
> - Add focusable to Pressable

**Comment by NickGerleman** [comment] 2020-07-15 00:52
We should already have this. Stock Pressable will set the inner view to Focusable so long as the outer Presasble is not explicitly set not to be focusable See https://github.com/facebook/react-native/blob/0.63-stable/Libraries/Components/Pressable/Pressable.js#L213-L226

We can keyboard between pressables in the RNTester example with this.

**Comment by NickGerleman** [comment] 2020-07-15 00:56
Going to close this one since I think there's nothing left to do. @chrisglein please reopen if I missed something here.

**Closed by NickGerleman** 2020-07-15 00:56 UTC
Labels: Area: Keyboard, Proposal

**Comment by TheSavior** [comment] 2020-07-15 01:38
It might not be necessary, but I could expect Pressable to pass in the state object `hovered` and `focused`, where right now it just passes `pressed`. https://github.com/facebook/react-native/blob/0.63-stable/Libraries/Components/Pressable/Pressable.js#L222-L223

`hovered` is probably more valuable than `focused`, but the API was designed to enable platforms to add more things like that.
