### ISSUE TITLE
React native windows Error  

### ISSUE THREAD

**Issue by vinaykumardetrix** [microsoft/react-native-windows#12590] opened 2024-01-10 20:43 UTC
### Problem Description

× Building Solution: C:\Users\XXX\Desktop\SyncloLabs\node_modules\react-native-windows\PropertySheets\Codegen.t...
 × Build failed with message C:\Users\XXX\Desktop\SyncloLabs\node_modules\react-native-windows\PropertySheets\Codegen.targets(17,5): error : TypeError: _this._shutdownStatsbeat is not a function [C:\Users\XXX\Desktop\SyncloLabs\windows\SyncloLabs\SyncloLabs.vcxproj]. Check your build configuration.
Command failed. Re-run the command with --logging for more information.
C:\Users\XXX\Desktop\SyncloLabs\node_modules\applicationinsights\out\Library\Sender.js:199
                                        _this._shutdownStatsbeat();
                                              ^

TypeError: _this._shutdownStatsbeat is not a function
    at IncomingMessage.<anonymous> (C:\Users\XXX\Desktop\SyncloLabs\node_modules\applicationinsights\Library\Sender.ts:203:34)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.12.1

Using below list of npm packages:

    "@react-native-async-storage/async-storage": "^1.21.0",
    "@react-native-community/netinfo": "^11.1.0",
    "@react-native-masked-view/masked-view": "^0.3.0",
    "@react-navigation/native": "^6.1.8",
    "@react-navigation/native-stack": "^6.9.17",
    "jwt-decode": "^4.0.0",
    "react": "18.2.0",
    "react-native": "0.73.1",
    "react-native-chart-kit": "^6.12.0",
    "react-native-gesture-handler": "^2.14.0",
    "react-native-pager-view": "^6.2.1",
    "react-native-pie-chart": "^3.0.2",
    "react-native-reanimated": "^3.6.1",
    "react-native-safe-area-context": "^4.7.2",
    "react-native-screens": "^3.25.0",
    "react-native-svg": "^14.1.0",
    "react-native-webview": "^13.6.4",
    "react-native-windows": "0.73.2"
    
npx react-native autolink-windows        

npx react-native-windows-init --overwrite

npx react-native run-windows

tried npm i applicationinsights             with latest version

### Steps To Reproduce

New project also getting issues with react native wndows latest version 

### Expected Results

Need to solve this error

### CLI version

npx react-native -v got (12.3.0)

### Environment

```markdown
npx react-native info

PS C:\Users\XXX\Desktop\SyncloLabs> npx react-native info
info Fetching system and libraries information...
System:
  OS: Windows 11 10.0.22000
  CPU: "(16) x64 AMD Ryzen 7 5800X 8-Core Processor             "
  Memory: 10.19 GB / 15.91 GB
Binaries:
  Node:
    version: 18.12.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.3.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "29"
      - "33"
    Build Tools:
      - 29.0.2
      - 30.0.3
      - 33.0.1
    System Images:
      - android-29 | Intel x86 Atom_64
      - android-29 | Google APIs Intel x86 Atom
      - android-29 | Google Play Intel x86 Atom
      - android-33 | Google APIs Intel x86 Atom_64
    Android NDK: Not Found
  Windows SDK:
    AllowAllTrustedApps: Enabled
    AllowDevelopmentWithoutDevLicense: Enabled
    Versions:
      - 10.0.17763.0
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.20348.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: AI-213.7172.25.2113.9123335
  Visual Studio:
    - 17.7.34202.233 (Visual Studio Community 2022)
Languages:
  Java: 11.0.16.1
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-windows:
    installed: 0.73.3
    wanted: 0.73.3
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

info React Native v0.73.2 is now available (your project is running on v0.73.1).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.73.2
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.73.2
info For more info, check out "https://reactnative.dev/docs/upgrading?os=windows".
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

None

### Build Configuration

None

**Comment by jonthysell** [comment] 2024-01-11 18:19
This bug is a duplicate of #12587. Please upgrade to RNW 0.73.4.

**Closed by jonthysell** 2024-01-11 18:19 UTC
Labels: bug, Needs: Triage :mag:
