### ISSUE TITLE
Unable to use FileOpenPicker after updating to RNW-0.64.4

### ISSUE THREAD

**Issue by MustafaAlsihati** [microsoft/react-native-windows#7722] opened 2021-05-04 08:55 UTC
I'm facing an issue and I'm not sure what is causing it after updating react-native-windows from 0.63 to 0.64.4. I have a native module code using `Windows.Storage.Pickers.FileOpenPicker` class to pick images in C# UWP project, before 0.64.4 it was working fine, but after updating I got an exception which cause the image picking to fail, the window dialog for file picking is not even opening.

*Code:*
```
        public async Task<File> PickFileAsync(string[] fileTypes)
        {
            File file;
            try
            {
                var picker = new FileOpenPicker
                {
                    ViewMode = PickerViewMode.Thumbnail,
                    SuggestedStartLocation = PickerLocationId.PicturesLibrary
                };
                
                foreach (string filetype in fileTypes)
                {
                    picker.FileTypeFilter.Add(filetype);
                }

                StorageFile storageFile = await picker.PickSingleFileAsync();
                if (storageFile != null && Array.IndexOf(fileTypes, storageFile.FileType) > -1)
                {
                    var fileProperties = await storageFile.GetBasicPropertiesAsync();
                    var size = fileProperties.Size;
                    var base64_data = await StorageFileToBase64(storageFile);
                    file = new File(storageFile.Path, storageFile.FileType, storageFile.Name, base64_data, size);
                }
                else
                {
                    throw new Exception("No File was Selected");
                }
            }
            catch (Exception e)
            {
                throw e;
            }

            return file;
        }
```

It basically fails at `var picker = new FileOpenPicker{...}`

*Exception:* `Invalid window handle. (Exception from HRESULT: 0x80070578)`

I added this line of code which solved the exception above, but raised another exception:
```
 public async Task<File> PickFileAsync(string[] fileTypes)
        {
          ...
          ((IInitializeWithWindow)(object)picker).Initialize(System.Diagnostics.Process.GetCurrentProcess().MainWindowHandle);
          ...
        }
```

*New exception:* `Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))`

I already added *Pictures Library* in **Capabilities**, and I also tried added *broadFileSystemAccess*, and I added file types *[".jpg", ".jpeg", ".png"]* in **Declarations**, but no luck so far.

**Comment by rectified95** [comment] 2021-05-04 21:56
Potentially related to https://github.com/microsoft/react-native-windows-samples/issues/427

**Comment by asklar** [comment] 2021-05-05 06:41
@MustafaAlsihati See the in-progress documentation update here: https://github.com/microsoft/react-native-windows-samples/pull/428

**Comment by asklar** [comment] 2021-05-05 06:42
Duplicate of microsoft/react-native-windows-samples#427

**Closed by asklar** 2021-05-05 06:42 UTC
Labels: Needs: Triage :mag:, question
