### ISSUE TITLE
Text cut-off when Text size is changed to maximum

### ISSUE THREAD

**Issue by bahri-dev** [microsoft/react-native-windows#12069] opened 2023-08-24 17:12 UTC
### Problem Description

Navigate to system Settings and set Text size to maximum.
Observed that Text cut off like the following.
![image](https://github.com/microsoft/react-native-windows/assets/92716081/25656d87-bb82-424d-a323-bec5b167b8c8)
How can I fix this issue?

### Steps To Reproduce

import { Text } from 'react-native';

<Text>Long sentense - RNText sentence. Text font size is changed to maximum. Check out all Text components from multiple libraries. Test sentence. Text font size is changed to maximum. Check out all Text components from multiple libraries. Test sentence. Text font size is changed to maximum. Check out all Text components from multiple libraries.</Text >

### CLI version

0.71.0

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 2.97 GB / 15.67 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.16299.0, 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0, 10.0.22000.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.33529.622 (Visual Studio Enterprise 2019)
  Languages:
    Java: 1.8.0_302 - C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.0 => 0.71.0
    react-native-windows: 0.71.4 => 0.71.4
  npmGlobalPackages:
    react-native: Not Found
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

**Comment by chrisglein** [comment] 2023-08-24 18:09
Can you provide more context? As in the actual source that assigns that value to the `Text` including the text properties like font and such? I'm not sure what font size "maximum" means, for example.

**Comment by chrisglein** [comment] 2023-08-24 18:27
Can you provide the source around your `Text` component so we know what bounds are being set? Is the Text or its layout constrained in any way? Or is the Text given free reign and clipping within that regardless?

**Comment by bahri-dev** [comment] 2023-08-24 18:30
It's free. The app is very simple.
`const App = (): JSX.Element => { return (<Text> .... </Text>); }`
I tried to use style={{flex:1}}, and it fixed. But it's incorrect solution.

**Comment by TatianaKapos** [comment] 2023-08-24 20:52
This seems related to https://github.com/microsoft/react-native-windows/issues/10253, may be a duplicate issue

**Comment by bahri-dev** [comment] 2023-08-24 21:38
Yeah, it seems the same.

**Comment by chrisglein** [comment] 2023-08-28 16:27
Yep, confirmed this still repros and is only an issue when you change the size while the app is running:

Right after change:
![image](https://github.com/microsoft/react-native-windows/assets/26607885/33535cba-84fe-4d54-8544-b127ae2a9461)
Close the app and run the same scenario:
![image](https://github.com/microsoft/react-native-windows/assets/26607885/15464bf7-f14c-4425-aa1c-a13bf7292809)

Duplicate of #10253

**Closed by chrisglein** 2023-08-28 16:27 UTC
Labels: bug, Needs: Attention :wave:, Area: Text, Needs: Repro

**Comment by bahri-dev** [comment] 2023-08-28 16:41
Will it be fixed in the future?

**Comment by odaytelbany** [comment] 2024-08-05 07:16
did any one find a solution ?
