### ISSUE TITLE
Reconcile AppTheme Module with new Appearance Module

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4322] opened 2020-03-16 13:00 UTC
React Native 0.62 adds a new Appearance Module, which allows apps to query light mode vs dark mode. See https://medium.com/@rossbulat/theming-in-react-native-explained-ac40d0d2e15c

This conflicts with out existing custom AppTheme module, which provides the same functionality, but adds information about high contrast, and the high contrast palette.

We should figure out our story here. A few options immediately come to mind:
1. **Keep both around:** This seems confusing to users, but there is some Windows specific theming information we might want to expose in the future, like "personalization color" (highlight color).
2. **Add APIs to Appearance:** We should not do this. It will just add debt.
3. **Add `AppearanceWindows` with a superset of functionality:** This seems cleanish if we can't logically split other things off.
4. **Split some functionality into `AccessibilityInfo` and `PlatformColor`:** We already have Windows specific accessibility needs, and these APIs already differ by platform. For things like whether high contrast is enabled, that seems like a potentially better home. High contrast palette, or personalization color could work with PlatformColor, which we should have soon.

FYI @marlenecota

**Comment by NickGerleman** [comment] 2020-03-16 13:01
I might wire up the AppearanceModule during the 0.62 upgrade just because RNTester takes a dependence on it and it seems simple. We should still think about what to do longer term though.

**Comment by kikisaints** [comment] 2020-03-16 17:25
Related or dupe of #3701? maybe we should merge these two issues as the former was logged a while ago before we knew as much about this API as we do now.

**Comment by chrisglein** [comment] 2020-07-13 23:41
Duplicate of #3701

**Closed** 2020-07-15 02:00 UTC
Labels: API: Completion, Area: Theming, Deforking, Deliverable, duplicate, needs PM design
