### ISSUE TITLE
how can i run the project on my windows device?

### ISSUE THREAD

**Issue by radha-kotecha** [Microsoft/react-native-windows#1797] opened 2018-04-20 07:28 UTC

**Comment by piyush965** [comment] 2018-04-20 08:58
@radha-kotecha  Refer: https://github.com/Microsoft/react-native-windows/blob/master/docs/GettingStarted.md

**Comment by radha-kotecha** [comment] 2018-04-20 09:16
@piyush965 i have created the project which is running on a my laptop but i want to deploy the same in my mobile phone i followed all the steps of https://github.com/Microsoft/react-native-windows/blob/master/docs/RunningOnDeviceWindows.md yet the JS bundle cannot be fetched.

**Comment by radha-kotecha** [comment] 2018-04-20 10:08
![image](https://user-images.githubusercontent.com/34673746/39045566-d65a76f6-44b0-11e8-857f-9f74ed756a1c.png)
this is the  issue ti am facing

**Comment by rozele** [comment] 2018-04-20 15:46
@radha-kotecha unfortunately we don't have anything like _adb reverse_ on Windows, and we also have yet to implement a developer settings page where you can configure the URI from the app, so you have to edit the packager server URI in source code to match the IP of your development machine and redeploy the app. The location of this setting is here: https://github.com/Microsoft/react-native-windows/blob/c8ef244b91b7c3f2b7d01df44fb638439f3479a2/ReactWindows/ReactNative.Shared/DevSupport/DevServerHelper.cs#L27

Closing this, as it is actually a dupe of #478, #1378, #650, #365, etc.

**Closed by rozele** 2018-04-20 15:46 UTC
