### ISSUE TITLE
Feature nice to have Separate debughost and debugport. 

### ISSUE THREAD

**Issue by stecrain** [microsoft/react-native-windows#2593] opened 2019-06-07 23:35 UTC
It would be better to allow the host name and port to be set independently. The code in ReactWindows does this, but I did not extend this to the devSettings struct at the time. Perhaps we should create an issue to investigate making this change.

_Originally posted by @akrantz in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0Mjg2MjM1Mzc1/pull_requests/unread_timeline_

**Comment by harinikmsft** [comment] 2019-06-12 19:44
Looks like a dupe of #2586

**Closed by harinikmsft** 2019-06-12 19:44 UTC
Labels: Needs: Triage :mag:, vnext
