### ISSUE TITLE
Remove Modules with old C# Windows support

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7895] opened 2021-05-29 19:54 UTC
There are a number of native modules that have Windows support but for the C# version of the framework (what we called current as opposed to today’s vNext).
Most people outside our team won’t know or care about the difference but the thing is that these modules advertise that they support Windows, but they cannot be used with modern RNW versions.
Proposal is to go to each of these and remove the Windows implementation and update the directory.

**Comment by asklar** [comment] 2021-06-03 23:24
CC @stmoy, looks like this is on track to be addressed on your end : )

**Comment by chrisglein** [comment] 2022-01-14 21:48
Duplicate of #6282

**Closed by chrisglein** 2022-01-14 21:48 UTC
Labels: enhancement, Documentation, Extensions, External
