### ISSUE TITLE
VS22 initial build of RNW stalls

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/react-native-windows#9475] opened 2022-02-04 17:52 UTC
### Problem Description

The first build after opening Visual Studio 2022 doesn't properly start up. It will only start building if I cancel the first build and build again or try to exit VS (shown in video). 

Root-caused it to the commit from #8195, likely a side-effect of PackageReference changes. 

https://user-images.githubusercontent.com/41223743/152577265-18c6093d-3a3d-46c5-8385-4472f2bdde5f.mp4

 

### Steps To Reproduce

1. Open RNW project in VS 2022
2. Try to build

### Expected Results

Project should start building when 'build' is pressed. 

### CLI version

6.2.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 45.37 GB / 63.85 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.19041.0, 10.0.22000.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.0.32112.339 (Visual Studio Enterprise 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by JunielKatarn** [comment] 2022-02-04 21:31
Self-assigning due to #8195 authorship.

**Comment by NickGerleman** [comment] 2022-02-07 15:08
@JunielKatarn there is an MSBuild property for whether VS is doing a "design time build", instead of a real build. We've needed to add that before to some expensive tasks, to maintain VS interactivity.

**Comment by JunielKatarn** [comment] 2022-03-02 19:33
@chrisglein Why is this bug labeled `0.68`?

Isn't VS 2022 unsupported for that version?

**Comment by chrisglein** [comment] 2022-03-02 20:20
Good callout, @JunielKatarn. Moving this out a release as we want to track VS 2022 issues, but this shouldn't be a blocker for 0.68.

**Closed** 2022-03-05 08:35 UTC
Labels: bug, Area: Developer Experience, Area: Build Infrastructure, PackageReference

**Comment by JunielKatarn** [comment] 2022-03-09 01:31
Update.

Root cause found.

The following was thought to be a hard requirement for `PackageReference` in `.vcxproj` projects:
```xml
<ItemGroup>
  <ProjectCapability Include="PackageReferences" />
</ItemGroup>
```

1. This caused the hangs in VS2022.
2. It is not at all needed for `PackageReference`. Can be safely omitted.
