### ISSUE TITLE
App crashes when using PlatformColor

### ISSUE THREAD

**Issue by Laci556** [microsoft/react-native-windows#7144] opened 2021-02-16 23:45 UTC
## Environment
1. `npx react-native --version`: 4.13.1
2. `npx react-native info`:
```
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 8.63 GB / 15.90 GB
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.30804.86 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: 3.8.4 - /c/Users/bucsa/AppData/Local/Programs/Python/Python38/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.14
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

```jsx
<View style={{backgroundColor: PlatformColor( 'SystemListLowColor' )}}></View>
```

## Expected Results
The app shouldn't crash and the view should have the SystemListLowColor background color.

I tried experimenting with colors from the UWP docs page linked in the React Native for Windows documentation site but every brush I tried crashed the app without throwing any errors. Button colors work though. Is there any list or resources of the brushes available in React Native? Or it's just trial and error, seeing what is supported and what isn't? After hours of googleing I could not find any other helpful resources. And why do those linked in the docs make the app crash?
[https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/xaml-theme-resources](url)

**Comment by chrisglein** [comment] 2021-02-18 19:14
This shouldn't crash on unknown brush names. Not sure what's hardcoded here (color names) versus customizable with other native brush names. Needs some investigation.

**Comment by asklar** [comment] 2021-04-14 23:32
Duplicate of #7576

**Closed by asklar** 2021-04-14 23:32 UTC
Labels: Area: PlatformColor, bug
