### ISSUE TITLE
datetimepicker on RN Windows not work

### ISSUE THREAD

**Issue by RahidAkhundzada** [microsoft/react-native-windows#7647] opened 2021-04-26 06:06 UTC
npx react-native info output:
info Fetching system and libraries information...
System:
OS: Windows 10 10.0.19041
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Memory: 15.19 GB / 23.85 GB
Binaries:
Node: 15.12.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
npm: 7.8.0 - C:\Program Files\nodejs\npm.CMD
Watchman: Not Found
SDKs:
Android SDK:
API Levels: 23, 28, 29
Build Tools: 23.0.1, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0
System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64
Android NDK: Not Found
Windows SDK:
AllowDevelopmentWithoutDevLicense: Enabled
AllowAllTrustedApps: Enabled
Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
IDEs:
Android Studio: Version 4.1.0.0 AI-201.8743.12.41.7042882
Visual Studio: 16.9.31205.134 (Visual Studio Community 2019)
Languages:
Java: 1.8.0_211 - C:\Program Files\Java\jdk1.8.0_211\bin\javac.EXE
npmPackages:
@react-native-community/cli: * => 5.0.1-alpha.2
react: 17.0.1 => 17.0.1
react-native: 0.64.0 => 0.64.0
react-native-windows: ^0.64.0-0 => 0.64.4

npmGlobalPackages:
react-native: Not Found

datetimepicker version: 3.4.6

Windows 10
------------------------------------------------------------------------------------------------------------------------------

I select date but set wrong date.for example i select 23 but datetimepicker set 22. as on photo.

------------------------------------------------------------------------------------------------------------------------------

```jsx
const DatePicker: FC = props => {

const now=new Date();
const startTime =new Date(1619271418);
return (

{
<Text style={{color:'black'}}>{props.title}
}
<DateTimePicker
value={props.value}
timeZoneOffsetInMinutes={0}
is24Hour={false}
display="default"
dateFormat='shortdate'
onChange={props.onChange}
minimumDate={props.minimumDate? props.minimumDate : startTime}
maximumDate={props.maximumDate? props.maximumDate: now}
/>

);
};
```
------------------------------------------------------------------------------------------------------------------------------
```jsx
<DatePicker
title={item.title}
value={costumerData[item.subTitle]}
onChange={(e: any, selectedDate: any) => {
console.log("selectedDate : ", selectedDate);

        setcostumerData({
          ...costumerData,
          [item.subTitle]: selectedDate,
        });
      }}
    />
------------------------------------------------------------------------------------------------------------------------------

console.log("selectedDate : ", selectedDate); => if i watch log it is same.
```
-----------------------------------------------------------------------------------------------------------------------
![1](https://user-images.githubusercontent.com/45500775/116036002-06c7ab80-a677-11eb-896b-085078208f19.png)
![2](https://user-images.githubusercontent.com/45500775/116036006-07f8d880-a677-11eb-8aba-3a5bf0e545c4.png)

**Comment by NickGerleman** [comment] 2021-04-26 10:54
@RahidAkhundzada do you know what locale you have windows set to use?

**Comment by RahidAkhundzada** [comment] 2021-04-26 11:04
> @RahidAkhundzada do you know what locale you have windows set to use?

Yes i get data new Data() .it work good.but i select date with picker.it sets wrong date. DateTimePicker default use devices time. if we watch photo we can see other time select.it get data from new Data() firstly.then i change it goes wrong.

**Comment by asklar** [comment] 2021-04-26 18:14
Andrew thinks the xaml locale is different than the JS locale
Since this is in a community module, marking this one as a dupe.

**Comment by asklar** [comment] 2021-04-26 18:14
Duplicate of react-native-datetimepicker/datetimepicker#446

**Closed by asklar** 2021-04-26 18:14 UTC
Labels: Needs: Triage :mag:, bug
