### ISSUE TITLE
CLI app won't launch with "Application XXX has not been registered" error

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2663] opened 2019-06-22 01:18 UTC
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.58.0
2. `npm ls rnpm-plugin-windows`:
3. `npm ls react-native-windows`:
helloworld_current3@0.0.1 D:\helloworld_current3
`-- (empty)
4. `node -v`:
v10.15.1
5. `npm -v`:
6.7.0
6. `yarn --version`:

Then, specify:

- Target Platform:  UWP

- Target Platform Version(s): idunno

- Target Device(s): desktop

- Development Operating System: Windows 10 (19h1)

- Visual Studio Version: VS 2017

- Build Configuration: Debug

### Steps to Reproduce

(Write your steps here:)

1. react-native init helloworld_current3 --version 0.58.0

Now look at app.json, you'll see this:

{
  "name": "helloworld_current3_current3",
  "displayName": "helloworld_current3_current3"
}
Notice the additional _current3.  This is the bug.  It should be helloworld_current3

When I launch the app it fails because it's looking for helloworld_current3_current3 and this class isn't registered.  This must be a bug in the CLI.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rozele** [comment] 2019-06-24 13:17
This is an unfortunate side-effect of you using `helloworld` as part of your app name. If you changed it to `foo_current3` you wouldn't have this problem. In `react-native`, they use `HelloWorld` as the placeholder name for the project name, and apparently the CLI performs two regex replace operations (case insensitive), leading to the behavior listed above.

This bug should definitely be filed in either `react-native` to choose a more unique placeholder name or the `react-native-community/cli` tool to fix the double regex replace (if possible).

**Comment by rozele** [comment] 2019-06-24 13:21
Actually, if you even just changed your project name to `Helloworld_current3`, you wouldn't hit the issue. The problem is that the CLI tool seems to check for both case sensitive and all lower case variants of the placeholder name. So in the case of the default `react-native` template, it checks for `HelloWorld` and `helloworld`. It finds the lowercase `helloworld` in the app name it's already replaced.

https://github.com/react-native-community/cli/blob/master/packages/cli/src/commands/init/editTemplate.js#L14-L19

Closing this one out - up to you if you want to file upstream.

**Comment by rozele** [comment] 2019-06-24 13:22
cc @grabbou for visibility.

**Closed by rozele** 2019-06-24 13:21 UTC
Labels: .NET, Needs: Triage :mag:

**Comment by grabbou** [comment] 2019-06-24 13:40
Ah, that definitely sounds like something our regex should take care of + a better placeholder name. Let me cross-open an issue.
