### ISSUE TITLE
react-native link should perform the task of react-native bundle ...

### ISSUE THREAD

**Issue by AaronFriel** [microsoft/react-native-windows#1415] opened 2017-10-05 23:02 UTC
The React Native docs and other repositories suggest using `react native link` to copy assets to various directories, and conveniently this can be built in as a single build step for iOS and Android. Unfortunately, the same functionality does not work for Windows projects.

Perhaps this code in `link.js` from the React Native project should be modified to perform the same task as the prescribed bundle command:

```
react-native bundle --platform windows --entry-file index.windows.js --bundle-output windows\nativeapp\ReactAssets\index.windows.bundle --assets-dest windows\nativeapp\ReactAssets
```

https://github.com/facebook/react-native/blob/master/local-cli/link/link.js#L123-L139

Would that be a correct solution?

**Comment by rozele** [comment] 2017-10-05 23:09
This is a dupe of #1254

**Comment by AaronFriel** [comment] 2017-10-06 03:48
No it is not.

**Comment by AaronFriel** [comment] 2017-10-06 04:09
Because I know I'll have to do this tomorrow when you get to this:
  
victorileaf in #1254:

> Hi,
> Im developing an app that supports ios,android and windows as well. I was able to add custom fonts to the react native app by adding fonts to a folder and then adding assets inside package.json. Then running react-native link , i was able to use the custom fonts using fontFamily.
> How can i do this react-native-windows? Can someone help me?

This is a different issue. His issue is that in React-Native-Windows, fonts aren't registered under global names that can then be referenced via `fontFamily`. A Windows-specific technique needs to be used. (See, your [comment in August of last year](https://github.com/Microsoft/react-native-windows/issues/652#issuecomment-243172649) on issue #652.)

Another issue, #738 this be considered a duplicate, but has languished and appears to be conflated with #652. In fact some assets *do* get bundled when using the `react-native bundle ...` command provided. And if I add `const Roboto = require('native-base/Fonts/Roboto.ttf');` I do see that those assets are copied when I perform `react-native bundle ...`.

Finally, in #1254, the problem is primarily that `fontFamily` is broken and not cross platform in React Native Windows. That's a big breaking issue, but very different from the one I'm describing.

I read all of the issues related to assets and fonts, and of them, #738 is the closest to being a duplicate of this issue, but there was no root cause analysis performed and it was closed and then re-opened. Well, I can tell you why it wasn't fixed: there's literally no implementation for copying assets in `link.js`.

**Comment by rozele** [comment] 2017-10-06 12:20
@AaronFriel  I should have said "related to #1254", not dupe. Thanks for diving deep on these issues. I think your suggested approach of implementing the `copyAssetsWindows` is a good one.

**Closed** 2019-10-25 23:03 UTC
Labels: .NET
