### ISSUE TITLE
DLL debuggability: post process PDBs to support source access

### ISSUE THREAD

**Issue by vmoroz** [microsoft/react-native-windows#4551] opened 2020-04-09 21:41 UTC
This is part of the work to deploy RNW as DLLs.
We must keep the code inside of DLLs be debuggable.
It means that we must figure out how we should post-process PDB files before packaging them up into the Nuget package to access source code.
Ideally, it should enable access to the sources inside of the RNW GitHub repo.
If it is not possible then we should explore use of the SourceServer.
Some investigation must be done what approach must work best.

**Comment by asklar** [comment] 2020-04-13 08:46
@chrisglein @vmoroz  this is a dupe of #4377

**Comment by vmoroz** [comment] 2020-04-13 15:00
@asklar @chrisglein , yes it is a dupe of #4377 and I am closing this one and adding the #4377 to the project https://github.com/microsoft/react-native-windows/projects/33 for tracking its as apart of the 'Core DLL' effort.

**Closed** 2020-04-14 17:00 UTC
Labels: Area: Core DLL, Area: Debug Infrastructure, duplicate
