### ISSUE TITLE
Official react-native-webrtc support

### ISSUE THREAD

**Issue by tobyfrancis** [microsoft/react-native-windows#9877] opened 2022-04-22 18:16 UTC
### Summary

Official support for react-native-webrtc would go a long way - leaving individual developers to build the interface between WinRTC and React Native is inefficient, not to mention the deprecated state of WinRTC and MixedReality/WebRTC.

Most of the necessary imports for react-native-webrtc are functional, support for mediaDevices.getUserMedia as well as RTCView would be the highest priority. 

### Motivation

**Any** cross-platform mobile/desktop video communication application would benefit from support for react-native-webrtc in react-native-windows. Personally, I hope to be able to use react-native-windows to build a UWP that communicates via WebRTC with mobile targets.

### Basic Example

```
import React, { useState } from 'react';

import {
    RTCView,
    MediaStream,
    mediaDevices,
  } from 'react-native-webrtc';

export default function Video(){
  const [localStream,  setLocalStream]  = useState<MediaStream|null>(null);
  const setupWebrtc = async () => {
    let mediaStream = await mediaDevices.getUserMedia( { video: true, audio: false } );
    setLocalStream(mediaStream as  MediaStream);
  }
  return(
    <RTCView streamUrl={localStream?.toURL()}/>
  );
}

**Comment by chrisglein** [comment] 2022-04-25 18:08
Duplicate of #6028

**Closed** 2022-04-26 19:33 UTC
Labels: enhancement, Extensions, Resolution: Duplicate

**Comment by smasinde** [comment] 2023-03-13 18:25
@tobyfrancis did you ever figure out a workaround?
