### ISSUE TITLE
Need Hermes support for RNW with C#

### ISSUE THREAD

**Issue by aRajeshKumar** [microsoft/react-native-windows#8076] opened 2021-06-21 19:51 UTC
Tried to setup a new RNW project by following the steps from https://microsoft.github.io/react-native-windows/docs/getting-started with "--userHermes --language cs" flags and receiving the following error:

Receiving the following error when tried to compile ( I even tried to compile .sln through Visual studio, but similar error). 
`
C:\rntodo\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj(682,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGe
t Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is C:\rntodo\windows\packages\ReactNative.Hermes.Windows.0.7.2\build\
native\ReactNative.Hermes.Windows.targets.
Done Building Project "C:\rntodo\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\rntodo\windows\rntodo\rntodo.csproj" (default targets) -- FAILED.

Project "C:\rntodo\windows\rntodo.sln" (1:2) is building "C:\rntodo\node_modules\react-native-windows\Microsoft.ReactNative.Managed.CodeGen\Microsoft.ReactNative.Managed.CodeGen.csproj" (4:6) on n
ode 1 (default targets).
`

Based on the discussion with @asklar & @rectified95, I realized that the limitations are mentioned at a very later stage of the doucmentaion (https://microsoft.github.io/react-native-windows/docs/hermes).

Requesting for the following:

- Update the documentation stating explicitly that Hermes is only supported for .cpp based apps for now.
- Enable Hermes for C# based apps as well.

**Comment by asklar** [comment] 2021-06-21 21:30
Duplicate of #7225

**Comment by asklar** [comment] 2021-06-21 21:33
For updating the doc, I've sent microsoft/react-native-windows-samples#454
For blocking in the CLI, #8075

**Closed** 2021-06-24 18:22 UTC
Labels: Needs: Triage :mag:
