### ISSUE TITLE
Playground Fast Refresh Not Working

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#8595] opened 2021-09-07 22:58 UTC
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 6.0.0
2. `npx react-native info`:

```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 36.99 GB / 63.84 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.9.31529.145 (Visual Studio Enterprise 2019)
  Languages:
    Java: 1.8.0_282
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

- Target Platform Version(s): 10.0.19041.0
- Target Device(s): Desktop
- Visual Studio Version: 2019
- Build Configuration: Debug
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run playground app.
2. Open text.tsx.
3. Make sure Fast Reload checkbox is checked. 
3. Edit text.tsx  styles and save.
4. Changes to text.tsx do not appear on page.

## Expected Results

Would expect to see changes to JS source to load automatically when Fast Refresh option is selected. 
Describe what you expected to happen.

**Comment by chrisglein** [comment] 2021-09-13 15:11
Same or different as #8608?
Also, FYI no RNW version number came back on this one.

**Comment by chrisglein** [comment] 2021-09-13 18:24
Duplicate of #8608

**Closed by chrisglein** 2021-09-13 18:24 UTC
Labels: bug, Needs: Triage :mag:, Area: Developer Experience
