### ISSUE TITLE
Getting Invalid response for BLOB  at application startup

### ISSUE THREAD

**Issue by Surendirani-Adappt** [microsoft/react-native-windows#11439] opened 2023-03-31 09:14 UTC
### Problem Description

I'm trying to upgrade my existing windows app, to latest version,
But on App launch am getting this error

version used :
React Native 0.68.0
React native windows : 0.68.30

![Screenshot 2023-03-23 190824](https://user-images.githubusercontent.com/74950426/229078006-adcbd5c7-eeb7-47cb-83be-947d26810869.png)

### Steps To Reproduce

- Set `UseWebDebugger` to `false` in `App.cpp`.
- Perform any `fetch` call.\
  Using NPM package `whatwg-fetch`.

### Expected Results

`fetch` call succeeds

### CLI version

10.1.3

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.15063

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

https://github.com/jurocha-ms/Repro/tree/main/ReactNative/fetchwinvalidblob

### Root Cause

Context:
Once `BlobModule` is enabled, `whatwg-fetch` defaults `responseType` to `blob`.
This will cause even plain text responses to be handled as blobs, requiring the HTTP module to have a Blob response handler ready.\
Such handler is added to the HTTP module by the Blob module's `addNetworkingHandler` method.

Under certain conditions (i.e. see `Steps to Reproduce`), module initialization will happen in a deferred manner.\
A module (i.e. `Blob`) will be fully initialized and start receiving method calls before one of its dependencies (i.e. `Http`) has been properly initialized.

Using the described repro steps, the following sequence takes place:
1. `BlobTurboModule::Initialize`
2. `BlobTurboModule::AddNetworkingHandler`\
   The HTTP module has not been initialized (context property `HttpModule.Proxy` has not been set).\
  `AddNetworkingHandler` will do nothing.
3. `HttpTurboModule::Initialize`\
   This sets context property `HttpModule.Proxy` too late for the Blob module to register it.

### Workarounds
- Remove Blob support from the app if not needed (remove its registration line from `ReactInstanceWin.cpp`.
- Invoke `Blob.addNetworkingHandler` explicitly after the app has loaded.
  - Only works if no dependencies make a `fetch` call during app setup.

**Comment by chrisglein** [comment] 2023-03-31 23:42
I too have been seeing this on 0.71.
Thought it was supposed to be resolved:
https://github.com/microsoft/react-native-windows/issues/10036
https://github.com/microsoft/react-native-windows/pull/10848/files
PR merged Nov 14, 2022 in main, and backported to 70 , 69, and 68. Did it make the 71 cutoff?. @JunielKatarn @chiaramooney

**Comment by chrisglein** [comment] 2023-04-03 16:57
As far as an upgrade potentially being helpful, you said 0.68.30 and this change should have been in as of [0.68.24](https://github.com/microsoft/react-native-windows/releases/tag/react-native-windows_v0.68.24). So you already have that fix. Must need more.

**Comment by Surendirani-Adappt** [comment] 2023-04-06 05:07
Yeah, but facing issue there as well , same blob response err, I've  tried with other version as well

**Comment by Surendirani-Adappt** [comment] 2023-04-06 10:13
![image](https://user-images.githubusercontent.com/74950426/230347390-24e6f7a8-7ace-437e-83f2-8574e11fd25b.png)
Facing the same errrin react native ver 69

**Comment by JunielKatarn** [comment] 2023-04-29 07:12
Can't reproduce this issue using the current release versions to create a new application.
@chrisglein can you please share your steps to reproduce (particularly on 0.71)?

@Surendirani-Adappt can you please provide more details about your app?
Does it directly use HTTP or Blob APIs?

Also, can you please run `npx react-native info`?

**Comment by chrisglein** [comment] 2023-05-01 14:32
> Can't reproduce this issue using the current release versions to create a new application. @chrisglein can you please share your steps to reproduce (particularly on 0.71)?

Sure. One of the apps where I'm seeing this is [here](https://github.com/chrisglein/artificial-chat). It's possible I've also seen it with [gallery](https://github.com/microsoft/react-native-gallery/), but I haven't built it in a while.

**Comment by JunielKatarn** [comment] 2023-05-01 19:32
> Sure. One of the apps where I'm seeing this is [here](https://github.com/chrisglein/artificial-chat). It's possible I've also seen it with [gallery](https://github.com/microsoft/react-native-gallery/), but I haven't built it in a while.

Thanks.
I'm not able to see any errors by just building and running this app.
Do I need to do something specific with it?
Also, I'm not being able to use it. Is there a way to change the theme so text won't get lost in the background?
Note, I have an API key but adding it on settings doesn't seem to work.

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/4507319/235516516-3824382b-ce0c-4a95-84b2-dfd1ffa33129.png">

**Comment by JunielKatarn** [comment] 2023-05-01 19:50
@chrisglein I'm not seeing any issues after starting the app and setting up the API key.
Are there any further steps to take?

**Comment by Surendirani-Adappt** [comment] 2023-05-02 10:01
> npx react-native info

![image](https://user-images.githubusercontent.com/74950426/235637703-a698ae39-3b53-4799-8042-860f17f93fcd.png)

**Comment by Surendirani-Adappt** [comment] 2023-05-02 10:05
@JunielKatarn 
> Regarding the app, it was developed initially as a mobile application,, and converted to Windows RN ver 63, .Now  an trying to Upgrade it  to higher version of react native (0.69.0)

> Also, can you please run `npx react-native info`?

![image](https://user-images.githubusercontent.com/74950426/235638493-4037c5da-9f4d-4c27-bdc1-559faaf255f6.png)

**Comment by Surendirani-Adappt** [comment] 2023-05-02 12:55
> @JunielKatarn
> 
> > Regarding the app, it was developed initially as a mobile application,, and converted to Windows RN ver 63, .Now  am trying to Upgrade it  to higher version of react native (0.69.0)
> 
> > `npx react-native info`?
> 
> ![image](https://user-images.githubusercontent.com/74950426/235638493-4037c5da-9f4d-4c27-bdc1-559faaf255f6.png)

**Comment by chrisglein** [comment] 2023-05-02 18:02
Confirmed that I can get this to repro with the [gallery](https://github.com/microsoft/react-native-gallery/) app. No interaction required, just boot up the app. Did it from CLI `yarn windows`, starting from nothing (no existing metro open or browser debug port).

**Comment by JunielKatarn** [comment] 2023-05-02 22:43
@chrisglein Confirmed repro on RN Gallery launch (`main` branch, commit ID `07242a3984292cfe96a8b0e37d4d3ba1be4b649a`).

Continuing investigation.

**Comment by JunielKatarn** [comment] 2023-07-19 21:50
The issue is introduced by `whatwg-fetch`.
See `node_modules/whatwg-fetch/dist/fetch.umd.js`.

(Around line 12)
```JavaScript
  var support = {
    searchParams: 'URLSearchParams' in global,
    iterable: 'Symbol' in global && 'iterator' in Symbol,
    blob:
      'FileReader' in global &&
      'Blob' in global &&
      (function() {
        try {
          new Blob();
          return true
        } catch (e) {
          return false
        }
      })(),
    formData: 'FormData' in global,
    arrayBuffer: 'ArrayBuffer' in global
  };
```

(Around line 559)
```JavaScript
      if ('responseType' in xhr) {
        if (support.blob) {
          xhr.responseType = 'blob';
        } else if (
          support.arrayBuffer &&
          request.headers.get('Content-Type') &&
          request.headers.get('Content-Type').indexOf('application/octet-stream') !== -1
        ) {
          xhr.responseType = 'arraybuffer';
        }
      }
```

If Blob support is detected as enabled, `fetch` will force the `responseType` as `blob`.
This makes our native module (via `WinRTHttpResource`) mishandle the response and causing the JS exception.

Note, we are not claiming this is a bug on whatwg-fetch.
I will compare this behavior to iOS or Android variants and see how they handle the same condition.

**Closed** 2023-07-24 19:34 UTC
Labels: bug, Area: Networking
