### ISSUE TITLE
Unable to restore packages WinRTXamlToolkit

### ISSUE THREAD

**Issue by codebased** [Microsoft/react-native-windows#1149] opened 2017-06-14 10:00 UTC
After following the "Start" guide, installing awesomeproject, I am getting the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to retrieve information from remote source 'https://www.nuget.org/api/v2/FindPackagesById()?id='WinRTXamlToolkit''.
The ServicePointManager does not support proxies with the https scheme.			0

**Comment by matthargett** [comment] 2017-06-15 23:19
It sounds like you are on a network with a strict http proxy configuration. Can you connect to a different network (like tethering to your phone's cellular network over WiFi) and see if the problem is reproducible?

**Comment by sayar** [comment] 2017-07-07 19:05
@codebased were you able to resolve this issue with different network settings?

**Comment by sayar** [comment] 2017-07-17 19:59
@codebased It seems as though your issue has been resolved. If you don’t mind, I will close this issue in 1 day unless I get an update from you.

**Closed** 2017-07-24 14:36 UTC
Labels: needs-update-or-close
