### ISSUE TITLE
Running only one e2e test seems to run them all

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-windows#7266] opened 2021-03-03 23:12 UTC
This is actually 2 closely related issues:
- When running e2etest for the first time, all tests are run even if only one is specified. The app window is opened multiple times and closed immediately, until the target test is started, and only then does the test driver type the test name in the app and triggers the XAML dump;
- Running eg. `yarn e2etest -t LegacyTextBackgroundColortest` subsequent times, makes other test names appear in the console with an indication they're running, without starting the app window, before the target test gets run. This seems to slow down the whole process by a lot.

**Comment by NickGerleman** [comment] 2021-03-04 13:49
Dupe here with additional context/solutions https://github.com/microsoft/react-native-windows/issues/7240

**Comment by chrisglein** [comment] 2021-03-04 19:21
Duplicate of #7240

**Closed** 2021-03-04 19:21 UTC
Labels: Area: Test Infrastructure, Needs: Triage :mag:, bug
