### ISSUE TITLE
Errors with Upgrade to 0.68-preview

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#9512] opened 2022-02-09 20:16 UTC
### Problem Description

After upgrading to 0.68.0-preivew.1 Gallery is hitting the following errors. 

Seems like the new way of adding CppWinrt with packagereference isn't playing well with ReactNativeXaml and that a series of other modules are unable to build because of something to do with the UAP framework. 
![image](https://user-images.githubusercontent.com/34109996/153282698-5beb821a-877f-41ae-803d-ac356082052e.png)

### Steps To Reproduce

Upgrade gallery to 0.68 preview.

### Expected Results

Successful build. 

### CLI version

7.0.1

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 49.50 GB / 63.84 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.9.32002.222 (Visual Studio Enterprise 2019)
  Languages:
    Java: 1.8.0_282
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.0-rc.1 => 0.68.0-rc.1
    react-native-windows: 0.68.0-preview.1 => 0.68.0-preview.1
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Build Configuration

Debug

**Comment by chiaramooney** [comment] 2022-02-09 20:17
@NickGerleman fyi for release status.

**Comment by NickGerleman** [comment] 2022-02-09 20:25
cc @JunielKatarn

**Comment by JunielKatarn** [comment] 2022-02-09 23:41
@NickGerleman   Will look into it.

@chiaramooney I am not familiar with the RN gallery.
Could you please add precise steps to reproduce the issue?

At a first glance, it looks like a configuration issue.
Some build properties may need to be updated when adopting 0.68.

**Comment by NickGerleman** [comment] 2022-02-10 06:22
I think @tido64 ran into a similar issue.

**Comment by NickGerleman** [comment] 2022-02-10 09:26
@JunielKatarn this is the repo for react native gallery. https://github.com/microsoft/react-native-gallery
@chiaramooney, could you publish your local state as a draft PR? That would help give Julio a way to locally reproduce the issue you are seeing.

**Comment by tido64** [comment] 2022-02-10 14:08
I've been having issues on this branch: [microsoft/react-native-test-app#windows-support-0.68](https://github.com/microsoft/react-native-test-app/tree/tido/windows-support-0.68)

I've tried the following without success:

- Running `yarn windows`
- Building in Visual Studio 2019/2022 (on two different Windows machines)
- The `MSBuild` steps detailed in https://github.com/microsoft/react-native-windows-samples/pull/628

**Comment by jonthysell** [comment] 2022-02-10 19:20
@chiaramooney can you upload a draft PR of the upgrade so we can take a look at it?

**Comment by chiaramooney** [comment] 2022-02-10 19:25
@NickGerleman @JunielKatarn Here's the PR! https://github.com/microsoft/react-native-gallery/pull/193

**Comment by JunielKatarn** [comment] 2022-02-11 00:24
> 

Let's follow up again tomorrow if you have time.
As I mentioned offline yesterday, I did not face this issue following the steps you provided.

The build succeeded for me, and the app started correctly.

**Comment by JunielKatarn** [comment] 2022-02-11 00:25
> I've hit the same issue on this branch: [microsoft/react-native-test-app#windows-support-0.68](https://github.com/microsoft/react-native-test-app/tree/tido/windows-support-0.68)
> 
> I've tried the following without success:
> 
> * Running `yarn windows`
> * Building in Visual Studio 2019/2022 (on two different Windows machines)
> * The `MSBuild` steps detailed in [Document mixed `PackageReference` and `packages.config` projects react-native-windows-samples#628](https://github.com/microsoft/react-native-windows-samples/pull/628)

@tido64 Let's follow up again tomorrow if you have time.
As I mentioned offline yesterday, I did not face this issue following the steps you provided.

The build succeeded for me, and the app started correctly.

**Comment by chiaramooney** [comment] 2022-02-18 22:44
@JunielKatarn The gallery app succeeded for you? It looks like it is not only failing for me locally but also on ADO, so it isn't just an issue with my local environment.

**Comment by JunielKatarn** [comment] 2022-02-19 02:03
@chiaramooney I was on bug queue duty these last weeks.
I'll jump back to this and all `PackageReference`-related issues on Tuesday.

**Comment by JunielKatarn** [comment] 2022-02-25 03:43
This is an unexpected error.

There is a failure building even just Microsoft.ReactNative (meaning, it could be unrelated to the gallery code or dependencies):
```
msbuild.exe /p:Configuration=Debug /p:Platform=x64 /p:AppxBundle=Never /p:RestorePackagesConfig=true /p:RunAutolinkCheck=false /restore .\node_modules\react-native-windows\Microsoft.ReactNative\ /p:UseWinUI3=false
```

The two resulting errors are:

1. Assertion failed (apparently, `noexcept` method returning void).
```
node_modules\react-native-windows\Mso\dispatchQueue\dispatchQueue.h(728,17): error C2607: static assertion failed [R:\pkr\gal\node_modules\react-native-windows\Microsoft.ReactNative\Mi
crosoft.ReactNative.vcxproj
```

And, the one likely shown in VS:
```
(_OnXamlPreCompileError target) ->
  C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(486,5): error MSB4181: The "CompileXaml" task returned false but did not log an error
. [node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]
```

The latter does not happen if we set MSBuild property `UseWinUI3` to `true`, but the `dispatchQueue` error still happens.

**Comment by JunielKatarn** [comment] 2022-02-25 08:39
Update. The following command fails for any version in the React Native Windows `0.68-stable` branch:
```
cls; msbuild.exe /restore  /maxCpuCount /p:Platform=x64 /p:RestorePackagesConfig=true vnext\Microsoft.ReactNative\
```
with the errors mentioned above.

However, it succeeds when run against the `main` branch.
There is likely some `PackageReference`-related fix we haven't backported yet.

**Comment by JunielKatarn** [comment] 2022-02-25 09:26
Both MSBuild errors go away when applyint #9562.
#9609 posted to backport to `0.68-stable`.

Once it's merged, RN gallery should try bumping the RNW preview dependency.

**Comment by asklar** [comment] 2022-02-25 23:09
@JunielKatarn the error should only happen in vs2022, are you seeing it in vs2019 as well?

**Comment by JunielKatarn** [comment] 2022-02-25 23:55
> 

I just noticed the original issue that your PR fixes.
I don't have 2019 installed on this machine, so it's safe to assume it happened only because I upgraded to VS 17.1.

Resuming research on the root cause.

**Comment by NickGerleman** [comment] 2022-02-28 23:50
@JunielKatarn Can we inject that prop ourselves? E.g. via internally used, or externally included property sheets? I don't think we can be asking our users to add special props outside of our framework to fix the issue.

This sort of thing is why I was a bit hesitant about us modifying `Directory.build.props` with the change. It fixes the issue in our own repo, but our own repo is not what customers are using.

**Comment by NickGerleman** [comment] 2022-02-28 23:53
Note that `.vcxproj` using community modules in `node_modules` should already indirectly import [`vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.props`](https://github.com/microsoft/react-native-windows/blob/main/vnext/PropertySheets/External/Microsoft.ReactNative.Uwp.CppLib.props) if they are well behaved.

**Comment by JunielKatarn** [comment] 2022-03-01 00:19
> @JunielKatarn Can we inject that prop ourselves? E.g. via internally used, or externally included property sheets? I don't think we can be asking our users to add special props outside of our framework to fix the issue.
> 
> This sort of thing is why I was a bit hesitant about us modifying the repo directory `Directory.build.props` with the change. It fixes the issue in our own repo, but our own repo is not what customers are using.

We can. We should. Based on your last comment, we can probably use that particular file to set the property.

**Comment by NickGerleman** [comment] 2022-03-01 00:44
Thanks 🙂.

Note that the app @chiaramooney is using, `react-native-gallery` includes many community modules, some of which are quite old, from before we had the foundation we have today. We were standardizing to use the mentioned PropertySheet [two years ago](https://github.com/microsoft/react-native-windows/pull/4987), so you should assume you can target it, but it is possible this will still break compatibility with very old modules if they have not been correctly maintained.

@JunielKatarn please don't concern yourself if you encounter one of these modules, beyond maybe documenting the workaround you referenced to force the properties to be included. We've already been doing quite a bit of due diligence for these modules and are still being quite liberal with support level here.

**Comment by NickGerleman** [comment] 2022-03-01 00:47
@chrisglein @chiaramooney do you have any thoughts on how we should handle that case? Of modules included in the gallery which will no longer work out of the box? My gut feeling is that if we cannot support them and haven't fixed their build logic in the last two years, we shouldn't be advertising them.

**Comment by JunielKatarn** [comment] 2022-03-02 00:37
@chiaramooney #9628 will make it unnecessary to add the `Directory.Build.props` file.
You can try it once that PR gets backported to branch `0.68-stable`.

**Closed** 2022-03-02 19:40 UTC
Labels: bug, Scenario: Upgrade, Area: Build Infrastructure, PackageReference
