### ISSUE TITLE
Update to WinSDK 10.0.19041.0 

### ISSUE THREAD

**Issue by vmoroz** [microsoft/react-native-windows#6843] opened 2021-01-08 20:08 UTC
We currently depend on the WinSDK 10.0.18362.0  which is quite old.
The 10.0.19041.0 has a number of important fixes to the MIDL parser such as:
- Support for [noexcept] attribute
- Better handling of [experimental] attribute

**Comment by JunielKatarn** [comment] 2021-01-09 00:14
If it's not critical to have, maybe we can wait until Visual Studio makes it the default?

**Comment by chrisglein** [comment] 2021-01-11 19:08
We have an issue tracking this that has some discussion. Definitely copy in any of the benefits to that issue.
Duplicate of #4960

**Closed by chrisglein** 2021-01-11 19:08 UTC
Labels: Needs: Triage :mag:, enhancement
