### ISSUE TITLE
Should the "hidden" TypeScript support be mentioned in the vnext docs :)

### ISSUE THREAD

**Issue by johot** [microsoft/react-native-windows#3182] opened 2019-09-22 21:10 UTC
I tried finding information on how to use TypeScript for React Native Windows (vnext) but didn't find any. Then I saw the playground actually used TypeScript.

So in my sample app that I created from blank using the vnext instructions I just renamed my files to `.tsx` and it just worked 💃 

Should this perhaps be mentioned in the docs or am I missing something?

Thank you for a wonderful project, really excited for this!

**Comment by johot** [comment] 2019-09-23 07:39
After further investigation it seems React Native added TypeScript support via Babel 7 in 0.43.3, so we only need to rename files to `.ts` or `.tsx`. I think the best solution would perhaps be to add a typescript template so we can do `react-native react-native windows --template vnext-typescript` or something like that :)

**Comment by chrisglein** [comment] 2019-09-30 17:49
We've been following the pattern set by react native, where there's no typescript template. But perhaps this is an opportunity to push value back to react native so that both have good typescript starting template?

**Comment by johot** [comment] 2019-09-30 18:04
But React Native has a typescript template since a while back though? :)

react-native init MyTSProject --template typescript

Would feel strange if not even MS themselves have a TS template I think :)

**Comment by chrisglein** [comment] 2020-04-10 18:17
Duplicate of #4505.
We'll unify the discussion there.

**Closed** 2020-04-11 20:00 UTC
Labels: Documentation, duplicate, needs PM design, question
