### ISSUE TITLE
[RNTester] On Windows the buttons at the top should include Windows, not iOS & Android

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6588] opened 2020-11-20 05:55 UTC
![image](https://user-images.githubusercontent.com/22989529/99764426-dff6bf00-2ab1-11eb-939b-c68d1d8238c0.png)

**Comment by NickGerleman** [comment] 2020-11-20 13:15
Dupe of https://github.com/microsoft/react-native-windows/issues/6314

When we discussed this, the overall thought was that it wasn't really worth the effort.

**Closed** 2020-11-23 19:30 UTC
Labels: Area: Tests, External, bug
