### ISSUE TITLE
Picker does not detect a right to left language

### ISSUE THREAD

**Issue by adam-bratin** [Microsoft/react-native-windows#1913] opened 2018-07-26 21:32 UTC
### Environment

1. 
- react-native-cli: 2.0.1
- react-native: 0.55.4
- rnpm-plugin-windows@0.2.8
- react-native-windows@0.55.0-rc.0
- node: v9.4.0
- yarn v 1.3.2

Then, specify:

- Target Platform:
UWP
- Target Platform Version(s):
SDK 17134
- Target Device(s):
Desktop

- Development Operating System:
Windows 10

- Visual Studio Version:
Visual Studio 2017 15.7.4

- Build Configuration:
Debug

### Steps to Reproduce

(Write your steps here:)

1. Create an empty project
2. Add a view with a Picker element
3. Change the OS language to a right to left language like hebrew or arabic

### Expected Behavior
The picker should be oriented right to left and the text when the picker is opened should be aligned to the right side
![screenshot 16](https://user-images.githubusercontent.com/5893603/43289248-3f83e994-90df-11e8-89f9-0bc1e0671572.png)
![screenshot 17](https://user-images.githubusercontent.com/5893603/43289279-5388955c-90df-11e8-8f17-671f802e5377.png)

### Actual Behavior

The picker is left aligned and when it is opened the text is left aligned as well.
![screenshot 18](https://user-images.githubusercontent.com/5893603/43289656-8036d194-90e0-11e8-8b2c-9fbb475605b6.png)
![screenshot 19](https://user-images.githubusercontent.com/5893603/43334429-524bc8f0-9182-11e8-8f77-88b483f50f15.png)

I think this behavior is due to the fact that React-Native-Windows is using the Yoga Library to do layouting instead of letting UWP do it. Part of that means that when we create a Picker element the flow direction is always being set to the default FlowDirection.LeftToRight regardless of what the OS Language is set to. We might need to check whether the user has selected a RTL language and change the FlowDirection accordingly in ReactPickerManager's CreateViewInstace. Also, this may effect similar elements like Texbox whose clear text button is also determined by FlowDirection.

**Comment by achipa** [comment] 2018-08-01 11:06
According to https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/adjust-layout-and-fonts--and-support-rtl this is not quite automatic:

> Important
> However, FlowDirection is not set automatically based on the user's selected display language in Windows settings; nor does it change dynamically in response to the user switching display language. If the user switches Windows settings from English to Arabic, for example, then the FlowDirection property will not automatically change from left-to-right to right-to-left. As the app developer, you have to set FlowDirection appropriately for the language that you are currently displaying.

As FlowDirection is not specified in RNW when creating these elements (like Picker or InputText), their internal alignment will be wrong, even though the layout in general is rendered (RTL) correctly by Yoga. This is why it looks OK when taking a cursory look at RNTester in LTR.

Now, setting a parent FlowDirection in ReactRootView that gets inherited by all the children is easy, but then there are several side-effects:
- that way *both* Yoga and the UWP layer do RTL reversal, so the layouts are actually double-flipped and you're back in LTR. If you decide to do RTL solely on the UWP level is a no go, too
- disabling Yoga's RTL doesn't help as then paddings/margins/borders are not flipped
- disabling RTL in I18nManager also breaks RTL apps and RTL-aware components
- images with the FlowDirection set to RTL get mirrored in UWP (?!)

 It feels that RNW needs to be a bit more mindful of RTL components, either by selectively setting FlowDirection on instantiation on the ones that are RTL-sensitive, or let UWP handle all this, but that requires disabling some of Yoga's own RTL functionality (like flexbox ordering, but not margins/borders). I can think of up and downsides of both. As is, it's a strange mixture that "almost, but not quite works".

**Comment by rozele** [comment] 2018-08-01 11:56
@achipa so the problem is that Yoga relies on absolute positioning, and absolute positioning is not compatible with FlowDirection (eg, setting the Canvas.Left property when FlowDirection is RTL at the root still sets the left dimension). Does that sound correct?

If that's the case, then yes, we'll likely have to implement RTL on a per view basis. Seems like this should be a problem for many components (Text, TextInput, etc.), not just Picker...

**Comment by achipa** [comment] 2018-08-01 16:53
Yes, that's right. Picker was just the original component this came up with in this particular report, but it  applies to all direction-sensitive views/components (which is actually most of them). Note that it's not just about input - for example progress bars also demonstrate this problem very apparently.

**Comment by reseul** [comment] 2018-08-01 18:15
@rozele @achipa We were going to apply FlowDirection to our root views in our app (didn't do it yet) to fix all the occurrences of "scroll bar is still on the right", "clear button is still on the right", etc.
We didn't yet test, and the first bullet up there is concerning.

*That way both Yoga and the UWP layer do RTL reversal, so the layouts are actually double-flipped and you're back in LTR. If you decide to do RTL solely on the UWP level is a no go, too*

That made me curious. I may be able to test at some point to see if we could do some tricks (setting Canvas.Right instead of Left, etc.) when the rott view tree has a FlowDirection of RTL, etc.

**Comment by adam-bratin** [comment] 2018-08-01 18:40
I would say that I think we have potentially reached a point of philosophical debate around this issue. I think the root cause of this issue is around that fact that Yoga in an attempt to be faithful the the cross platform interface for layouting handles RTL changes in a different way than UWP, which are not mutually exclusive. Also, they are slightly destructive when used together. I think I agree with @achipa that we either need to set flow direction on individual components in the corresponding view managers or we need to disable using ReactShadowNode RTL direction. I feel if we try to play around with trying to mix the two solutions by tweeking settings on the root view it will be very hacky and brittle. @reseul To give more details when trying to root cause the issue I tried overriding View and adding a ReactProp to set UiDirection which would set that FlowDirection on a View that was at the root of our application. That caused images to instead of being moved to the right side of the application, instead they remained on the left side and the image was mirrored.

**Comment by reseul** [comment] 2018-08-01 18:46
Well, I can't promise anything, and I may not have time in the next day or so.
But I won't push anything hacky/brittle :)

**Comment by achipa** [comment] 2018-08-01 19:00
Here's a visual demonstration of what you get currently with a new project when you try to do RTL

ReactNative.I18nManager.allowRTL(true), no explicit FlowDirection:
![rtl_base1](https://user-images.githubusercontent.com/822934/43542327-9bcb1814-95c4-11e8-9699-3041ad2a423a.png)

This is almost good - layouting and image are OK, but the dropdown is aligned wrong and the progressbar is LTR.

ReactNative.I18nManager.allowRTL(true),  FlowDirection = Windows.UI.Xaml.FlowDirection.RightToLeft; in ReactRootView
![rtl_base2](https://user-images.githubusercontent.com/822934/43542331-9dc233fa-95c4-11e8-816d-820f235d49d8.png)

Layouts are double reversed (so they actually look LTR), and the Image is mirrored due to the inherited FlowDirection. Dropdown and progressbar are OK.

ReactNative.I18nManager.allowRTL(false),  FlowDirection = Windows.UI.Xaml.FlowDirection.RightToLeft; in ReactRootView
![rtl_base3](https://user-images.githubusercontent.com/822934/43542339-a131d040-95c4-11e8-87ca-685d9d1dfe4c.png)

Layout is (almost) OK, the padding is wrong, the image is mirrored, the dropdown and progressbar are OK.

**Comment by achipa** [comment] 2018-08-08 13:30
@reseul any luck with this? We're happy to help, but would like to avoid developing redundant solutions.

**Comment by adam-bratin** [comment] 2018-09-13 22:00
@rozele @reseul any update on this?

**Comment by reseul** [comment] 2018-09-13 22:11
@adam-bratin not really, I'm swamped with lots of other things. I'm afraid of providing ETAs..

**Comment by reseul** [comment] 2018-10-05 02:31
@adam-bratin @achipa @rozele 
I've been playing with this and I went through some of your experiences.
It's true that setting both flowdirection and allowRtl ends up doing double flipping due to Canvas.SetLeft (used by the Yoga driven absolute positioning being affected by Xaml layout direction as well.
So we have to go with just one.
1. I implemented a Xaml FlowDirection based solution. About the peculiarities:
- Images: a peculiarity of RCTImage is that it doesn't use Windows.UI.Xaml.Controls.Image controls (which, according to docs, would NOT obey an inherited FlowDirection by default). We use Border, I guess due to flexibility like rounded corners, etc.
Border does flip the image brush based on the inherited FlowDirection. I avoided overwriting locally since this would've impacted the children, so I apply a scale relative transform for the RTL case. The controls hook to that dependency property change to detect when to add the transform or clear it (we do want to support direction changing on the fly).
- Text Padding: I haven't tested, I just played with Skype (our "test" app) and tried to catch issues visually. I'll try to play with your sample tomorrow and figure it out. I'm pretty sure it's due to the combination of Yoga computed padding and the applying of it through a Thickness object to the native control itself. I think it fits same "listen to inherited FlowDirection and tweak locally" pattern.

2. With regards to how to apply this RootView.FlowDirection, I got to a point where a change in the i18nmanager pushes a "all RootViews FlowDirection update" through the operation queue. But then I realized "UIManager.measureInWindow" stopped working correctly. Turned out the direction discrepancies between ReactRootView and Window.Current.Content mess up the algorithm.
That got me thinking that an app-wise complete solution is for the app itself to set FlowDirection on that Window.Current.Content (maybe based on i18nUtil.isRightToLeft so we factor in those allow/force flags). 
More, that makes the code that sets this flag on ReactRootView superfluous.. so I'm just thinking of removing it.
It puts a little bit of a burden on the app writer, but otherwise I'd have to do some magic in measureInWindow to work on all conditions.. (and hey, setting the top level direction tweaks the title bar too, so that's a plus). I'm in a slight dilemma here.

3.For the I18NModule APIs, we have 2 more requirements in our team
- Direction is fully at the app's control. I know it can be achieved with passing "allowRTL == false" and then playing with "forceRTL", but that would look ugly. I guess I'll add a new flag.
- The resultant value can change (it's a constant now), so I'd have to add some event, I guess.
This module doesn't look very helpful anyway. I removed the only usage of I18NUtil.IsRightToLeft since we leave Yoga as is, I may defer the Xaml direction changes to the hosting app, various view managers read/listen to the FlowDirection changes (we followed same pattern in some internal view managers we have, with good results), etc. A bunch of flags for nothing much.. but it mimics the other RN platforms.

Anyway, I'm planning on sending a PR tomorrow if all planets align.

**Comment by adam-bratin** [comment] 2018-10-05 17:12
@reseul Thanks so much for all the effort you have put into addressing this issue. I am appreciate how difficult it is to juggle your own work on top of trying to help support others. I think I follow most of what you observed, but I will wait for the PR to try and better understand where the changes are occurring and am willing to be a guinea pig to see how these changes can effect other apps.

**Comment by rozele** [comment] 2019-01-25 13:44
@adam-bratin - I think this was fixed by #1994. Can you confirm?

**Comment by achipa** [comment] 2019-01-30 19:58
@rozele Looks good at a first glance, let me check back with more consistent testing (RTL is really all about testing...). I'm a bit torn between 0.55 and 0.57 for other reasons which might makes verification a bit more roundabout than usual.

**Comment by rozele** [comment] 2019-02-26 04:05
Closing. Thanks @achipa.

**Closed by rozele** 2019-02-26 04:05 UTC
Labels: needs-update-or-close
