### ISSUE TITLE
Add support to client for --port parameter

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4520] opened 2020-04-07 18:09 UTC
When launching metro, there is a --port parameter which tells metro to listen for connections on a port other than 8081.  The client doesn't support this as it's hard-coded to always use port 8081.

We should add support for this.  The feature request is very similar to: https://github.com/microsoft/react-native-windows/issues/4316

Perhaps we can get @nasadigital to take this task as well.

**Comment by chrisglein** [comment] 2020-04-09 18:12
Duplicate of #2586

**Closed** 2020-04-10 20:00 UTC
Labels: Needs: Triage :mag:, Proposal, duplicate
