### ISSUE TITLE
Error while publishing app to Windows store Windows Runtime metadata validation FAILED Type name correctness

### ISSUE THREAD

**Issue by coronatime2020** [microsoft/react-native-windows#5228] opened 2020-06-16 07:16 UTC
### Environment
If you are using latest version:
1. `react-native -v`: "0.61.5",
2. `react-native run-windows --info`:
```
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 10.94 GB / 15.91 GB
  Binaries:
    Node: 11.6.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.5.0-next.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @react-native-community/cli: ^4.9.0 => 4.9.0
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
    react-native-windows: 0.61.9 => 0.61.9
  Installed UWP SDKs:
    10.0.18362.0
```
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```
Then, specify:

- Target Platform Version(s):

- Target Device(s): Desktop

- Visual Studio Version: Visual Studio 2019

- Build Configuration: ReleaseBundle

### Steps to Reproduce

(Write your steps here:)

1. npx react-native init <project name> --version ^0.61.5
2. npx react-native-windows-init --language cs --overwrite
3. Project > Publish > Create App Package 

I uploaded it to newly created microsoft dev account
after going through all the process I got a certification error for Windows Runtime metadata validation

The same error I got when I ran the Windows App Certification Kit

# Error which I got
```
FAILED Type name correctness
Error Found: The type name correctness test detected the following errors:
Impact if not fixed: Microsoft store doesn't allow apps that don't pass Windows Runtime Metadata Validation.
How to fix: Please ensure there are no Windows Runtime types in the global namespace or in the Windows top-level namespace.
```

While if you make project `npx react-native-windows-init --language cpp --overwrite`
I did not receive an error for Windows Runtime metadata  when I launched the Windows Application Certification Kit

**Comment by chrisglein** [comment] 2020-06-18 18:29
Duplicate of #5201

**Closed** 2020-06-18 18:29 UTC
Labels: Needs: Triage :mag:, bug
