### ISSUE TITLE
Related to Text Focus.

### ISSUE THREAD

**Issue by sakthivel-servicemax** [microsoft/react-native-windows#6640] opened 2020-12-01 06:34 UTC
Having Text Focused and tapping outside on TouchapeOpacity, it is not taking action. First focus lost is what happening then on next click only, it is taking the action. Is it intensional? It was not there before.

Environment Info:
**npx react-native --version:** 4.13.1
**npx react-native run-windows --info:**
System:
    OS: Windows 10 10.0.19041
    CPU: (6) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.70 GB / 11.67 GB
  Binaries:
    Node: 12.6.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: ^0.63.0-0 => 0.63.11
  Installed UWP SDKs:
    10.0.17763.0
    10.0.18362.0

**Comment by asklar** [comment] 2020-12-02 08:23
can you please share your environment/version info

**Comment by sakthivel-servicemax** [comment] 2020-12-02 08:30
> can you please share your environment/version info

@asklar updated the environment info.

**Comment by chrisglein** [comment] 2020-12-03 19:32
> It was not there before.

@sakthivel-servicemax Specifically do you mean on a particular previous version of RNW?

Trying to visualize your repro here. Do you mean on a `TextInput`? If there happens to be overlap in what you're describing that doesn't require RNW-specific APIs can you sketch together a [snack](https://snack.expo.io/)? Or include some snippet of your JS for us to look at?

That'd help, but what I think you're saying is that when focus is a `TextInput` and you click outside to another `Touchable*` it takes 2 clicks. Which certainly sounds like a bug.

**Comment by NickGerleman** [comment] 2020-12-04 02:14
Do the symptoms of this issue sound familiar? https://github.com/microsoft/react-native-windows/issues/5867

A fix will be in an upcoming 0.63 patch release.

**Comment by sakthivel-servicemax** [comment] 2020-12-04 06:05
@NickGerleman Yes. It is same as you mentioned. Thanks for taking it to fix already.

**Comment by chrisglein** [comment] 2020-12-07 18:55
Duplicate of #5867

**Closed by chrisglein** 2020-12-07 18:55 UTC
Labels: Area: Focus, Area: TextInput, Needs: Attention :wave:, bug
