### ISSUE TITLE
DatePicker for windows

### ISSUE THREAD

**Issue by aravi1995** [Microsoft/react-native-windows#1143] opened 2017-06-08 18:57 UTC
Is DatePicker implemented like it is for IOS ? If not how would I go about doing it ?

**Comment by rozele** [comment] 2017-07-03 16:29
@aravi1995 we do not currently have a DatePicker implementation for react-native-windows, but a pull request would be greatly appreciated.  There is some documentation on building native components here - https://github.com/Microsoft/react-native-windows/blob/master/docs/NativeComponentsWindows.md. I'd suggest using the UWP DatePicker control (https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.DatePicker).

**Comment by rozele** [comment] 2017-07-03 16:29
Closing as this is a duplicate of #230.

**Closed by rozele** 2017-07-03 16:29 UTC
