### ISSUE TITLE
[BUG] Playground app fails with web debugger checked, Chrome launches but not with debugger

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#2943] opened 2019-08-16 19:03 UTC
If you:
1. Build and run packages\playground
2. Get metro running
3. Load RNTester with web debugger enabled

Expected: Bundle is made, app loads, Chrome launches web debugger

Actual: Chrome launches to blank tab, no bundle, app fails with websocket error

**Comment by kmelmon** [comment] 2019-08-22 23:31
dupe of #2964

**Closed by kmelmon** 2019-08-22 23:31 UTC
Labels: Needs: Triage :mag:, bug, vnext
