### ISSUE TITLE
Upgrade to 61:  Implement React Refresh

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#4088] opened 2020-02-12 02:42 UTC
When we upgraded to react-native version 61, we got a new feature called React Refresh.  This is the new version of Hot Reload.

We should add support for React Refresh in react-native-windows.

**Comment by harinikmsft** [comment] 2020-02-13 21:10
Dupe of #4062

**Closed by harinikmsft** 2020-02-13 21:10 UTC
Labels: Needs: Triage :mag:, vnext
