### ISSUE TITLE
System.Runtime.InteropServices.COMException was unhandled by user code

### ISSUE THREAD

**Issue by sm2017** [Microsoft/react-native-windows#1198] opened 2017-07-12 06:18 UTC
In this line
https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative.Shared/DevSupport/DevSupportManager.cs#L362

We have this issue 

```
An exception of type 'System.Runtime.InteropServices.COMException' occurred in ReactNative.dll but was not handled in user code

Additional information: An async operation was not properly started.



Only a single ContentDialog can be open at any time.
```

```
System.Runtime.InteropServices.COMException was unhandled by user code
  ErrorCode=-2147483623
  HResult=-2147483623
  Message=An async operation was not properly started.

Only a single ContentDialog can be open at any time.
  Source=""
  StackTrace:
       at Windows.UI.Xaml.Controls.ContentDialog.ShowAsync()
       at ReactNative.DevSupport.DevSupportManager.<HandleReloadJavaScript>d__47.MoveNext()
  InnerException: 
```

**Comment by matthargett** [comment] 2017-07-12 18:10
do you have some sample code that is paste-able into Playground that reproduces the issue?

**Comment by sm2017** [comment] 2017-07-13 04:59
I follow this http://redux.js.org/docs/basics/ExampleTodoList.html

**Comment by rozele** [comment] 2017-07-13 08:41
@sm2017 are you using Ctrl+R to refresh, or trying to open the Shift+F10 dev options menu simultaneously? I think there's an older bug on this. https://github.com/Microsoft/react-native-windows/issues/146.

**Comment by sm2017** [comment] 2017-07-15 06:35
@rozele I use `Ctrl+R`

**Comment by rozele** [comment] 2018-07-23 21:02
@sm2017 please update if still an issue

**Comment by rozele** [comment] 2018-07-23 23:08
I think this is actually just a dupe of #361

**Closed by rozele** 2018-07-23 23:08 UTC
Labels: needs-update-or-close
