### ISSUE TITLE
FlatList `inverted` prop inverts keyboard and wheel scrolling

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#7267] opened 2021-03-04 00:30 UTC
The problem is that the `inverted` prop is implemented in JS by performing a matrix transform on the scroll content container (and then subsequently again on each cell item so the content is oriented correctly). Interestingly, pan gestures and the scroll bar operate as expected. However, other mechanisms for scrolling (including Page Up / Page Down / arrow keys while focused on the ScrollViewer content, and using a mouse scroll wheel) have opposite behavior. 

There's another question around whether the tab order of items in an inverted list should be top to bottom or bottom to top. My guess is that the inversion should simply be thought of a UI trick, and for accessibility, all other scrolling / tab ordering behaviors should be identical to non-inverted lists.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run RNTester FlatList example
2. Check the box to set `inverted` prop to true.
3. Tab focus into the ScrollViewer hosting the ListView
4. Try the Page Down, Page Up,  arrow keys to scroll the list, try a mouse scroll wheel.

## Expected Results
I expect the scroll wheel and keyboard navigation to work the same way pan gestures, scroll bar, etc. work, which is in the same direction as a non-inverted FlatList. E.g., if I'm at the "bottom" of the ScrollViewer (first item when inverted), and I hit Page Up key, I should scroll up (further down the list when inverted).

## Snack, code example, screenshot, or link to a repository:

Here's a video repro (though you can't see my pressing Page Down to scroll up 😬)

https://user-images.githubusercontent.com/1106239/109890835-f9350d00-7c55-11eb-8b1c-c64e4d6368b5.mp4

**Comment by chrisglein** [comment] 2021-03-04 19:19
Dupe of #4098

In writing a chat experience I imagine this is very important to you. Check on that issue and sync with @rectified95 for the whole story.

**Comment by chrisglein** [comment] 2021-03-04 19:45
Duplicate of #4098

(used wrong magic github words and so above comment didn't create the link 😅)

**Closed** 2021-03-04 19:46 UTC
Labels: Area: FlatList, Needs: Triage :mag:, Partner: Facebook, bug
