### ISSUE TITLE
Part of UI don't respect Dark mode

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5492] opened 2020-07-10 04:09 UTC
- turn on dark mode
- parts of playground RNTester will render as white on white,
  e.g. the text is following dark mode but not the background panels, or disabled items like disabled checkbox will show up as white

![image](https://user-images.githubusercontent.com/22989529/87115526-6e1b8880-c228-11ea-9a83-4358969f3563.png)

**Comment by NickGerleman** [comment] 2020-07-10 06:00
There are a couple issues around different aspects of this. Things will also look much better if you turn off web debugging, which is needed to use the new Appearance APIs.

**Comment by asklar** [comment] 2020-07-10 07:11
I first got a crash when disabling web debugger (#5497). Launched again and was able to disable web debugger and things look ok that way, it's weird that a debugging feature has impact on the UI... is this unique to RNW or common to all of RN?

**Comment by NickGerleman** [comment] 2020-07-10 16:45
It's common to all of RN. Facebook decided to implement Appearance APIs using synchronous NM calls, which don't work over web debugging, so they hardcode to light mode if you are. Web debugging is likely going away soon enough though.

**Comment by NickGerleman** [comment] 2020-07-10 16:47
PlatformColor should work with web debugging though. RNTester is all using Appearance APIs though.

**Comment by chrisglein** [comment] 2020-07-13 18:40
Duplicate of #4688

**Closed** 2020-07-14 20:00 UTC
Labels: Needs: Triage :mag:, bug, duplicate
