### ISSUE TITLE
Implement TextInput.submitKeyEvents for Fabric

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#11460] opened 2023-04-07 17:34 UTC
Part of https://github.com/microsoft/react-native-windows/issues/11145

Example
```jsx
      <TextInput
        accessibilityLabel="Prompt input"
        multiline={true}
        placeholder="Ask me anything"
        style={{flexGrow: 1, flexShrink: 1}}
        onChangeText={newValue => setValue(newValue)}
        submitKeyEvents={[{code: 'Enter', shiftKey: false}]}
        onSubmitEditing={submitValue}
        value={defaultText ?? value}/>
```

**Comment by YajurG** [comment] 2023-08-31 02:31
Looks like a duplicate of #11459

**Comment by TatianaKapos** [comment] 2024-02-21 00:34
closed via: #12746

**Closed by TatianaKapos** 2024-02-21 00:34 UTC
Labels: enhancement, Area: TextInput, Area: Fabric
