### ISSUE TITLE
Can't include a module's header file with REACT_STRUCT and REACT_FIELD in main App.cpp

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#4631] opened 2020-04-17 22:43 UTC
version: RNW 61-stable

App.cpp:
#include "SomeModule.h"
// ...
//use something/SomeStatic/Global from someModule.h
// etc...

SomeModule.h:

REACT_STRUCT(someStruct)
struct someStruct{
REACT_FIELD(someField)
std::string someField;
}
REACT_MODULE
...
// use someStruct
...etc...

When compiling, it gives errors that someStruct was already defined in app.obj and it gets unhappy.

There are some internal reasons we needed to include SomeModule.h in App.cpp for the time being to work around another issue (sneak in the LaunchActivatedEventArgs from App::OnLaunched).
Note: We aren't instantiating a copy of the module or anything, just needed access to a static function. 

Known workaround:
I can create a secondary SomeModuleProxy.h to move a few things of why we needed to include this module header in app.cpp but I feel REACT_STRUCT and REACT_FIELDS should be more resilient to such issues.

**Comment by vmoroz** [comment] 2020-04-20 21:34
Yes, I found this bug today too. I forgot to add the 'inline' for the function declaration in REACT_STRUCT.

**Comment by vmoroz** [comment] 2020-04-25 03:10
The issue is fixed in 0.61 by #4659 and in 0.62 by #4656.

**Closed by vmoroz** 2020-04-25 03:10 UTC
Labels: Area: Native Modules, Partner: Stream, bug
