### ISSUE TITLE
Console.log events are delayed in Metro by several seconds

### ISSUE THREAD

**Issue by lyahdav** [microsoft/react-native-windows#5650] opened 2020-08-06 01:02 UTC
## Environment
Run the following in your terminal and copy the results here.
1. `react-native -v`: running from git clone of this repo, at commit https://github.com/microsoft/react-native-windows/commit/69ea2c4831d11aec3f8c8ce406f7efb3248d20ee
2. `react-native run-windows --info`: Can't run this script easily, but I'm on Windows 10 Enterprise, version 2004
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Git clone this repo
2. Run Playground app per https://github.com/microsoft/react-native-windows/blob/master/docs/building-rnw.md#running-the-playground-app
3. Update one of the sample JS files to include:
```
  componentDidMount() {
    console.log('componentDidMount');
  }
```
4. Select that sample in Playground app and click Load

## Expected Results
After sample app is rendered I'd expect the console.log statement to show immediately in Metro logs. Instead it's delayed by several seconds.

**Comment by chrisglein** [comment] 2020-08-06 18:17
Highly unlikely this is a react-native-windows issue (we don't directly handle console methods), but could be an issue with Metro on Windows?
Are you only running this on Windows or do you have any comparison with this on iOS/Android?
Knowing more about your environment would be very helpful. Try running this:
`npx react-native run-windows --info`
We don't generally observe this so it'd be helpful to know what is different here. Do you experience a delay for later console logs or only for ones that occur right after load?

**Comment by lyahdav** [comment] 2020-08-10 23:00
I could see this being an issue with Metro on Windows, but if you don't experience this I agree we need to find out the differences between our environments. I was comparing this to RN Mac which doesn't have this issue. I assume RN mobile doesn't either, but didn't confirm.

Here's a video of the delay for logs during load (except for the Metro bundle line):
[RNW Metro delay.mov.zip](https://github.com/microsoft/react-native-windows/files/5053811/RNW.Metro.delay.mov.zip)

I also added a Button that logs in the onPress well after load and that logs immediately, so I think it's something specific to initial load. If I click the button during that initial loading delay it also delays that onPress log event:
[RNW Metro delay button click.mov.zip](https://github.com/microsoft/react-native-windows/files/5053825/RNW.Metro.delay.button.click.mov.zip)

And here's the info you requested:
```
PS C:\Users\lyahdav\Documents\GitRepos\react-native-windows\packages\playground> npx react-native run-windows --info

  System:
    OS: Windows 10 10.0.19041
    CPU: (40) x64 Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
    Memory: 169.46 GB / 190.60 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.0-20190429.1820 - C:\open\fbsource\xplat\third-party\yarn\yarn.BAT
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20200724.030019 - C:\tools\watchman\watchman.EXE
  Installed UWP SDKs:
    10.0.18362.0
```

**Comment by asklar** [comment] 2020-08-19 08:18
@lyahdav @chrisglein should this be tracked in the metro repo instead?

**Comment by chrisglein** [comment] 2020-08-19 16:15
> @lyahdav @chrisglein should this be tracked in the metro repo instead?

Possibly, although I don't think we're certain of the cause yet and also we don't really mind tracking the Windows quality of experience here even if the fix goes elsewhere (like we do for the community modules).

**Comment by asklar** [comment] 2020-08-19 16:46
@lyahdav I see the console.log statement render in the browser window (F12 tools) immediately after the app renders. I don't see any console.log output make it to the metro console window... is there a setting that may be missing in the repro?

**Comment by asklar** [comment] 2020-10-02 08:40
I did, here's the screen capture, the message shows up as soon as the app paints for me (ignore the errors those are from yellowboxes due to modules being removed from core)
![console log](https://user-images.githubusercontent.com/22989529/94904429-2b94d100-0450-11eb-9ca0-e3992bea8f4f.gif)

**Comment by asklar** [comment] 2020-10-02 21:30
spoke offline, @lyahdav will try this on master :)

**Comment by asklar** [comment] 2020-10-08 03:56
going to close this since I can't repro, Liron please lmk if you are able to get a repro on master and we can reopen this :)

**Closed by asklar** 2020-10-08 03:56 UTC
Labels: Needs: Author Feedback, Partner: Facebook, bug
