### ISSUE TITLE
The latest version failed to build on VS2022 17.7 Preview

### ISSUE THREAD

**Issue by 1280103995** [microsoft/react-native-windows#11642] opened 2023-05-22 13:08 UTC
### Problem Description

I followed the steps described in the [documentation](https://microsoft.github.io/react-native-windows/docs/getting-started), but I couldn't run the app in the terminal and I couldn't build on VS2022 17.7 Preview (same bug in 17.6)

### Steps To Reproduce

1. npx react-native init demo --template react-native@^0.71.0
2. cd demo
3. npx react-native-windows-init --overwrite
4. yarn windows --logging

### Expected Results

**Development dependencies are installed.**
```
PS C:\Users\Administrator> Set-ExecutionPolicy Unrestricted -Scope Process -Force;
>> iex (New-Object System.Net.WebClient).DownloadString('https://aka.ms/rnw-vs2022-deps.ps1');
>>
Checking Free space on current drive > 15 GB                        OK
Checking Installed memory >= 16 GB                                  OK
Checking Windows version >= 10.0.17763.0                            OK
Checking Developer mode is on                                       OK
Checking Long path support is enabled                               OK
Checking Visual Studio 2022 (>= 17.3) & req. components             OK
Checking Node.js (LTS, >= 16.0)                                     OK
Checking Yarn                                                       OK
Checking .NET SDK (LTS, = 6.0)                                      OK
All mandatory requirements met.
Press Enter to exit:
```

### CLI version

10.0.0

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19045
    CPU: (12) ia32 12th Gen Intel(R) Core(TM) i5-12400F
    Memory: 8.05 GB / 15.83 GB
  Binaries:
    Node: 18.14.1 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.3.1 - C:\Program Files (x86)\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.19041.0, 10.0.22000.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.7.33711.374 (Visual Studio Professional 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.0 => 0.71.0
    react-native-windows: 0.71.13 => 0.71.13
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

None

### Visual Studio Version

None

### Build Configuration

None

### Snack, code example, screenshot, or link to a repository

**yarn windows --logging error info**
```
D:\demo>yarn windows --logging
yarn run v1.22.19
$ react-native run-windows --logging
ERROR: The system was unable to find the specified registry key or value.
 i Verbose: ON
Looking for VS installs with version range: [17.0,18.0)
Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
 ‼ No public VS release found
 i Trying pre-release VS
Looking for VS installs with version range: [17.0,18.0]
Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
 √ Found compatible MSBuild at C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin (17.7.33711.374)
 MSBuild version 17.7.0-preview-23226-04+0dbc421ea for .NET Framework
Build started 5/22/2023 8:45:36 PM.

Project "D:\demo\windows\demo.sln" on node 1 (Restore target(s)).
D:\demo\windows\demo.sln.metaproj : error MSB4126: The specified solution configuration "Debug|ia32" is
 invalid. Please specify a valid solution configuration using the Configuration and Platform properties
 (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties
 blank to use the default solution configuration. [D:\demo\windows\demo.sln]
Done Building Project "D:\demo\windows\demo.sln" (Restore target(s)) -- FAILED.


Build FAILED.

"D:\demo\windows\demo.sln" (Restore target) (1) ->
(ValidateSolutionConfiguration target) ->
  D:\demo\windows\demo.sln.metaproj : error MSB4126: The specified solution configuration "Debug|ia32"
is invalid. Please specify a valid solution configuration using the Configuration and Platform properti
es (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properti
es blank to use the default solution configuration. [D:\demo\windows\demo.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.05
× Restoring NuGet packages
 × Couldn't restore found packages.config instances. Restoring NuGet packages  - exit error code 1
 i Gathering MSBuild data for telemetry.
 i Unable to find msbuildproperties.g.json
Command failed with error MSBuildError: Restoring NuGet packages  - exit error code 1
Your telemetry sessionId was 087a70b7c8960f818bde48c13ed24d48
error Command failed with exit code 2302.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Build failed on VS2022**
```
Rebuild started...
1>------ Rebuild All started: Project: Common, Configuration: Debug x64 ------
2>------ Rebuild All started: Project: fmt, Configuration: Debug x64 ------
1>Determining projects to restore...
2>Determining projects to restore...
1>Unicode.cpp
2>Applying temporary patches to fmt.
2>pch.cpp
2>format.cc
2>os.cc
1>Common.vcxproj -> D:\demo\node_modules\react-native-windows\target\x64\Debug\Common\Common.lib
2>fmt.vcxproj -> D:\demo\node_modules\react-native-windows\target\x64\Debug\fmt\fmt.lib
3>------ Rebuild All started: Project: Folly, Configuration: Debug x64 ------
3>Determining projects to restore...
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error : '{' is an unexpected token. The expected token is '"' or '''. Line 2, position 31.
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Xml.XmlTextReaderImpl.ParseAttributes()
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Xml.XmlTextReaderImpl.ParseElement()
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Xml.XmlTextReaderImpl.ParseElementContent()
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Xml.XmlDocument.Load(XmlReader reader)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at Microsoft.Build.Shared.SolutionConfiguration.GetProjectConfigurations(String xmlString)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at Microsoft.Build.Shared.SolutionConfiguration..ctor(String xmlString)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at Microsoft.Build.Graph.ProjectInterpretation.<GetReferences>d__24.MoveNext()
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at Microsoft.Build.Graph.GraphBuilder.ParseReferences(ProjectGraphNode parsedProject)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at Microsoft.Build.Graph.GraphBuilder.ParseProject(ConfigurationMetadata configurationMetadata)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Lazy`1.CreateValue()
3>C:\Program Files\Microsoft Visual 

.
.
.

Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Lazy`1.CreateValue()
6>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Lazy`1.LazyInitValue()
6>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at Microsoft.Build.Graph.ParallelWorkSet`2.ExecuteWorkItem()
6>Done building project "demo.vcxproj" -- FAILED.
========== Rebuild All: 2 succeeded, 4 failed, 0 skipped ==========
========== Rebuild started at 9:00 PM and took 05.518 seconds ==========

```

**Comment by chrisglein** [comment] 2023-05-22 18:12
From looking at your environment and your build error, the configuration is "ia32". Which... I'm not actually familiar with? What device/PC are you building with? We build x86 (which is 32-bit), but the focus is on 64-bit.

**Comment by 1280103995** [comment] 2023-05-23 02:53
The device is my personal desktop computer. When I run `yarn Windows - arch x64`, it does work. However, errors will still be encountered on VS2022.

**Comment by 1280103995** [comment] 2023-05-23 02:55
I have now switched to an HP laptop, and no one will make any mistakes when running `yarn windows`. But similarly, the VS2022 build failed.

```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 7.06 GB / 15.68 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0, 10.0.22000.0, 10.0.22621.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.6.33717.318 (Visual Studio Community 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.0 => 0.71.0
    react-native-windows: 0.71.0 => 0.71.0
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by lyahdav** [comment] 2023-05-24 23:25
I'm also running into this on x64 machine when trying to build the playground-win32 solution. Started happening I think after upgrading to Visual Studio 17.6.

**Comment by lyahdav** [comment] 2023-05-24 23:34
Also repros on VS 17.6.1

**Comment by 1280103995** [comment] 2023-05-25 01:14
> 



> I'm also running into this on x64 machine when trying to build the playground-win32 solution. Started happening I think after upgrading to Visual Studio 17.6.

You are right. I also have a machine with `VS2022 17.5.5` installed and it works fine.

**Comment by 1280103995** [comment] 2023-05-25 01:17
Shocking. I renamed the `C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets` file to `999NuGet.RestoreEx.targets` and built again and it worked.

**Comment by frankcalise** [comment] 2023-05-25 04:06
Experiencing this as well, version 17.6.1

**Comment by jonthysell** [comment] 2023-05-26 18:16
Ok I've confirmed the following the steps as written, VS 17.6.3 builds successfully.

**Comment by jonthysell** [comment] 2023-05-26 19:40
Ok I've also confirmed I can build with VS 17.7.0 Preview 1.0 (17.7.33711.374) successfully. While I do have 17.6 installed I can confirm from the logs that 17.7 is used: 

<img width="499" alt="image" src="https://github.com/microsoft/react-native-windows/assets/10852185/461276a0-b5c9-4d87-95a3-5d8b86e22fa0">

There are some problems elsewhere though. The current dependency script doesn't necessarily set up preview properly - see #11665. So it's possible you're getting a false positive from the dep script.

Also, if you tried to force `run-windows` to use 17.7 by setting the `VisualStudioVersion` environment property, the build can break. See #11666.

Not closing this yet, but there's something else wrong happening in your setup.

**Comment by 1280103995** [comment] 2023-05-29 01:56
When I have free time in two days, I will try again on my desktop computer. Now I am using an HP laptop, and next month I will compile the app for partners to try out, as I cannot make any modifications on it.

**Comment by jonthysell** [comment] 2023-05-30 17:36
Ok, I see, you've reported **two** different issues here.

The first one, where `yarn windows` didn't work because it saw the CPU as `ia32`, was fixed here: https://github.com/microsoft/react-native-windows/pull/11659

I can build successfully with `yarn windows` with VS 17.6 or 17.7 installed.

However, the second issue, with the `NuGet.RestoreEx.targets(19,5)` error, where you try to build *within* VS 2022 itself, I can now repro. It only repros when trying to build from within VS. Investigating now.

**Closed** 2023-05-30 18:14 UTC
Labels: bug, Needs: Attention :wave:, Area: CLI, Developer First Experience, Area: Dependencies
