### ISSUE TITLE
Crash if JS exception occurs while the debug menu is up

### ISSUE THREAD

**Issue by rigdern** [Microsoft/react-native-windows#1558] opened 2018-01-02 06:37 UTC
### Repro Steps

1. Create an app which throws a JS exception 5 seconds after a button is tapped
2. Tap the button
3. Bring up the debug menu (shift+F10)
4. Wait 5 seconds

**Unexpected result**: The app crashes with the following exception:

```
An async operation was not properly started.

Only a single ContentDialog can be open at any time.
```

It looks like the app has several different ContentDialogs that it shows (progress indicator, redbox, debug menu). Is there some mechanism it uses to coordinate the dialogs to ensure there's only ever one shown at a time?

**Comment by rozele** [comment] 2018-07-23 22:05
This is basically a dupe of #361. We need a more complex dialog manager for dev support, which is way overdue for refactoring.

**Closed by rozele** 2018-07-23 22:05 UTC
