### ISSUE TITLE
Playground RNTester crashes when disabling Web debugging

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5497] opened 2020-07-10 07:08 UTC
I got this message as a result of an abort

```
ReactNative ['Samples\rntester'] (error): 'ReferenceError: 'nativeFabricUIManager' is not defined'
Exception thrown at 0x7699DCA2 (KernelBase.dll) in playground.exe: WinRT originate error - 0x8000000E : 'A method was called at an unexpected time.'.
Exception thrown at 0x7699DCA2 in playground.exe: Microsoft C++ exception: winrt::hresult_illegal_method_call at memory location 0x0154E814.
Debug Error!

Program: ...kages\playground\windows\Debug\playground\AppX\playground.exe

abort() has been called


 	ucrtbased.dll!issue_debug_notification(const wchar_t * const message) Line 28	C++
 	ucrtbased.dll!__acrt_report_runtime_error(const wchar_t * message) Line 154	C++
 	ucrtbased.dll!abort() Line 51	C++
>	ucrtbased.dll!terminate() Line 59	C++
 	Microsoft.ReactNative.dll!facebook::react::CxxNativeModule::invoke::__l2::<lambda>() Line 175	C++
 	Microsoft.ReactNative.dll!std::_Invoker_functor::_Call<void <lambda>(void) &>(facebook::react::CxxNativeModule::invoke::__l2::void <lambda>(void) & _Obj) Line 1612	C++
 	Microsoft.ReactNative.dll!std::invoke<void <lambda>(void) &>(facebook::react::CxxNativeModule::invoke::__l2::void <lambda>(void) & _Obj) Line 1612	C++
 	Microsoft.ReactNative.dll!std::_Invoker_ret<void,1>::_Call<void <lambda>(void) &>(facebook::react::CxxNativeModule::invoke::__l2::void <lambda>(void) & <_Vals_0>) Line 1631	C++
 	Microsoft.ReactNative.dll!std::_Func_impl_no_alloc<void <lambda>(void),void>::_Do_call() Line 911	C++
 	Microsoft.ReactNative.dll!std::_Func_class<void>::operator()() Line 958	C++
 	Microsoft.ReactNative.dll!Mso::React::MessageDispatchQueue::tryFunc(const std::function<void __stdcall(void)> & func) Line 41	C++
 	Microsoft.ReactNative.dll!Mso::React::MessageDispatchQueue::runOnQueue::__l2::<lambda>() Line 36	C++
 	Microsoft.ReactNative.dll!Mso::Details::FunctionObjectWrapper<void <lambda>(void),void>::Invoke() Line 166	C++
 	Microsoft.ReactNative.dll!Mso::QueueService::InvokeTask(Mso::Functor<void __stdcall(void)> && task, std::optional<std::chrono::time_point<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000>>>> endTime) Line 208	C++
 	Microsoft.ReactNative.dll!Mso::ThreadPoolSchedulerWin::WorkCallback(_TP_CALLBACK_INSTANCE * __formal, void * context, _TP_WORK * __formal) Line 89	C++

```

**Comment by chrisglein** [comment] 2020-07-13 18:23
@vmoroz you've been looking at host lifetime issues and Keith mentioned this looked similar. What's this look like to you?

**Comment by chrisglein** [comment] 2020-07-13 18:24
Note from Alex: Not 100% repro, but he was able to get to happen multiple times.

**Comment by NickGerleman** [comment] 2020-07-20 15:10
Marking as a potential regression since 0.62 based on timing

**Comment by NickGerleman** [comment] 2020-07-20 15:58
Testing this manually, I'm frequently seeing asserts during instance reload (but also not entirely deterministically).

**Comment by chrisglein** [comment] 2020-07-20 18:25
There's some concern that we have some race conditions here, but we need someone to look at it and see what's going on. Pulling into 0.63 to investigate and see.

**Comment by NickGerleman** [comment] 2020-08-25 19:56
Don't think this is blocking for 0.63, since in 0.62 we were seeing instance reload crash. We still have bugs, but I think this might be an improvement over past state.

**Comment by chrisglein** [comment] 2021-01-21 19:43
Belief is that this is fixed.

**Closed by chrisglein** 2021-01-21 19:43 UTC
Labels: Area: Instance Management, Recent Regression, bug
