### ISSUE TITLE
[Gamepad] Cannot Invoke/Press Items in a FlatList

### ISSUE THREAD

**Issue by kikisaints** [Microsoft/react-native-windows#2181] opened 2019-03-21 16:31 UTC
I can navigate a FlatList just fine with the Xbox controller (gamepad) but I cannot press/invoke the items using the A button, like I can with the mouse. No "(pressed)" text appears.

**Comment by harinikmsft** [comment] 2019-04-25 17:39
This is a dupe of #2182

**Closed by harinikmsft** 2019-04-25 17:39 UTC
Labels: bug, needs PM design, rnwcpp
