### ISSUE TITLE
TestWhack is failing in CI

### ISSUE THREAD

**Issue by dannyvv** [microsoft/react-native-windows#7937] opened 2021-06-03 16:27 UTC
in CI TestWack step is failing:
```
runtime140.dll is not supported for this application type. Microsoft.UI.Xaml.Phone.dll calls this API. API __std_t    
erminate in vcruntime140.dll is not supported for this appl

...

API RtlLookupElementGenericTable in 
ntdll.dll is not supported for this application type. Microsoft.UI.Composition.OSSupport.dll calls this API.
```
for Playground x64 Release
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=175089&view=logs&j=9becf8ff-cd6f-536f-70b9-114e9c7c08ae&t=dc69c997-216f-5c30-22bf-70917afd7509

**Comment by NickGerleman** [comment] 2021-06-03 16:30
Heh, just filed this a few minutes earlier 😂

**Comment by NickGerleman** [comment] 2021-06-03 16:30
Duplicate of #7935

**Comment by asklar** [comment] 2021-06-03 16:42
closing as a dupe

**Closed by asklar** 2021-06-03 16:42 UTC
Labels: Needs: Triage :mag:, bug
