### ISSUE TITLE
App fails to run after upgrading to Visual Studio v15.8.5 (current latest)

### ISSUE THREAD

**Issue by npmun** [Microsoft/react-native-windows#1988] opened 2018-09-29 17:54 UTC
### Environment

1. `react-native -v`: 0.57.1
2. `npm ls rnpm-plugin-windows`: ^0.2.8
3. `npm ls react-native-windows`: 0.57.0-rc.0
4. `node -v`: v8.6.0
5. `npm -v`: 6.4.1
6. `yarn --version`:

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): 10.0.16299.0

- Target Device(s): Desktop

- Development Operating System: Windows 10 Pro

- Visual Studio Version: 15.8.5

- Build Configuration: Debug

### Steps to Reproduce

I setup brand new ReactNative project (successfully tested on the Android device). 
Windows app (react-native run-windows) ran successfully for the very first time.
However, it fails to run from the 2nd time onwards. 

![image](https://user-images.githubusercontent.com/36347019/46248938-76009480-c3d5-11e8-93bc-80942915494b.png)

Everything started working correctly after downgrading Visual Studio to 15.7.6

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

The app runs successfully when the latest version of Visual Studio installed.

(Write what happened. Add screenshots!)

### Reproducible Demo

App fails to run.

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by npmun** [comment] 2018-09-29 17:57
Also noticed this on npm bundler window.
_'.packager.bat' is not recognized as an internal or external command, operable program or batch file._

![image](https://user-images.githubusercontent.com/36347019/46248991-6897da00-c3d6-11e8-87d2-c2243fbcd994.png)

**Comment by rozele** [comment] 2019-02-26 03:48
@npmun - I believe upgrading Rx.NET dependencies will solve the issue, I'll follow up with a PR.

The `.packager.bat` issue is unrelated, it comes from the upstream JavaScript logic for starting the packager in the `run-android` scenario. We may actually use this hook for `run-windows`:
https://github.com/facebook/react-native/pull/17498/files

**Comment by rozele** [comment] 2019-02-26 03:57
Closing as dupe of #1954

**Closed by rozele** 2019-02-26 03:57 UTC
Labels: .NET
