### ISSUE TITLE
Web Debugging is busted

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2964] opened 2019-08-20 20:08 UTC
When launching an app into the web debugger, the browser launches a new tab, but it doesn't navigate to localhost:8081/debugger-ui.  The client then can't connect to the web debugger and this breaks the web debugging experience.

This bug appeared around the time the playground app moved into a separate package.

Repro Steps:
sync
yarn install
yarn build
build playground
Launch Chrome
from playground, yarn start
launch playground
load any app

RESULT
Chrome opens a new tab but stays at the welcome page instead of navigating to debugger-ui

You can workaround the issue by manually navigating to http://localhost:8081/debugger-ui

**Comment by acoates-ms** [comment] 2019-08-20 22:30
I think this might have been a change in chromes behavior.  -- I thought I saw something about it somewhere.  I assume web debugging works if you manually navigate chrome to 
http://localhost:8081/debugger-ui/
?

**Comment by kmelmon** [comment] 2019-08-20 22:35
> I think this might have been a change in chromes behavior. -- I thought I saw something about it somewhere. I assume web debugging works if you manually navigate chrome to
> http://localhost:8081/debugger-ui/
> ?

Yes that's the workaround.  I'm honestly not sure exactly when it started but I'm hearing reports of it across the team.

**Comment by micahl** [comment] 2019-08-22 15:53
@kmelmon dunno if it's related, but I'm also unable to get debugging to work in VS code enabling the web debugger and following [your instructions](https://github.com/microsoft/react-native-windows/wiki/VS-Code-Debugging).

**Comment by ddalp** [comment] 2019-09-19 17:02
It is caused by running old runserver.js which is from react-native-local-cli package and has unspecified port number. The same script from react-native-community package has updates which picks up the debugger port number 8081 from metro config. Andrew stated that we are moving to RN 0.60 which will correctly depend on react-native-community package, and the issue will be resolved by then. Keep this issue open and will check back once we are at RN 0.60.

**Comment by ddalp** [comment] 2019-09-30 19:20
Verified that the port number is correctly passed in after upgrade to RN 0.60

**Closed by ddalp** 2019-09-30 19:20 UTC
Labels: Area: Debug Infrastructure, Developer First Experience, bug, should-have, vnext
