### ISSUE TITLE
Mobile Emulator 10.0.14939 not running

### ISSUE THREAD

**Issue by ballySingh** [Microsoft/react-native-windows#1281] opened 2017-08-09 08:55 UTC
I've been following the guidelines and I cannot get my mobile emulator running for 10.0.14939 but funny thing is I can get 'mobile emulator 10.0.10586.0' working and also 'Local Machine'. 
I'm using Visual Studio 2017 on windows 10, cause the company has paid for it, I've got all my window SDKs installed. followed the guidelines but i get this:

![image](https://user-images.githubusercontent.com/30837072/29113083-ee9290a0-7ce7-11e7-9f03-83a8859f2e14.png)

-----
![image](https://user-images.githubusercontent.com/30837072/29113100-fc0ead90-7ce7-11e7-9d57-458773698358.png)

After 2 days of reading, I then decided to downgraded to Visual studio 2015 and then I get these issues, makes me wonder is this happening due to it conflicting with Visual Studio 2017.

![image](https://user-images.githubusercontent.com/30837072/29113288-8bbe1494-7ce8-11e7-9cc9-7608aad53aa4.png)

Thanks for reading..

**Comment by andreszs** [comment] 2017-09-20 13:24
I'd never downgrade VS on the same machine, instead, you should install VS on fresh-Windows installations only. Also, VS2015 was designed to work better on Windows 8.1.

**Comment by rozele** [comment] 2017-10-03 21:09
The issue was not with Visual Studio 2015, this is a dupe of https://github.com/Microsoft/react-native-windows/issues/683

**Comment by rozele** [comment] 2018-07-23 21:18
I suspect we can resolve this with #358.

**Closed by rozele** 2018-07-23 21:18 UTC
