### ISSUE TITLE
Text truncates depending on scale factor/layout rounding?

### ISSUE THREAD

**Issue by stmoy** [microsoft/react-native-windows#2660] opened 2019-06-21 17:34 UTC
Seems similar to #324 but repros on RNW vNext. 

Repro steps:
- Create a new RNW vNext project
- Run it
Notice that the text truncates with an ellipses (...) even when it has room to render the full text. Resizing the window causes the text to "jitter" between the proper text and the ellipses (see attached video).

Very likely due to a bug in layout rounding. Repro is most consistent on a high DPI machine that has a non-100% scale factor. 

![ReactNativeWindows Text Truncating](https://user-images.githubusercontent.com/25991996/59940630-10937e80-9410-11e9-83e4-201b742c1fd8.gif)

**Comment by kmelmon** [comment] 2019-06-28 23:39
Andy checked in a workaround which is to round up during yoga layout.  Keeping this open - we should root cause this instead of always rounding up.

**Comment by decrowle** [comment] 2019-07-25 22:19
Fixed in microsoft/react-native repo by PR #104 https://github.com/microsoft/react-native/pull/104

**Closed by decrowle** 2019-07-25 22:19 UTC
Labels: must-have, ready for dev, vnext
