### ISSUE TITLE
Due diligence for version 63:  pressRectOffset => pressRetentionOffset

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#5275] opened 2020-06-18 02:05 UTC
This breaking API change is coming in react-native version 63:

[Breaking][General]: Pressable: Rename pressRectOffset to pressRetentionOffset to be consistent with other touchables ([6610327](https://github.com/facebook/react-native/commit/6610327) by [@TheSavior](https://github.com/TheSavior)) 

Based on the discussion below, we should pick up this change for "free".  This task is just due diligence - make sure it works.

**Comment by TheSavior** [comment] 2020-06-18 02:12
I don't actually think that breaking change is an issue. Touchable and Pressability use `pressRectOffset` internally, although the API exposed on all the Touchables was `pressRetentionOffset`. When Pressable landed, we didn't realize the naming difference on the Touchables, so the prop exposed was called `pressRectOffset`. We renamed the prop exposed by Pressable to `pressRetentionOffset` to match the other components.

This was only marked as breaking because it was a public API change, however this change was made before a release of Pressable went out with the old name, so in practice this isn't breaking to the public API and we are not including this commit in the changelog.

I think the only thing to check for you is whether the nightly commit you are currently integrating has Pressable with the old prop name, in which case you'll need to make the same change as the linked commit when you actually update to 0.63

**Comment by kmelmon** [comment] 2020-06-18 02:28
Thanks @TheSavior!  We do have a bunch of forked files with the old prop name, so I think we'll just need to make sure we update our forked files with the new prop name (and possibly some tests).

**Comment by TheSavior** [comment] 2020-06-18 02:47
Are all the forked files the ones in your OP? I don't think any of those need to change. Take this for example:

```
src\Libraries\Components\Touchable\TouchableBounce.win32.js:57: getPressRectOffset: () => this.props.pressRetentionOffset,
```

I think that is saying, pass to Touchable (the internal statemachine), a function that called the prop called `pressRetentionOffset`. The public API name is `pressRetentionOffset`, the internal name hasn't changed. Nothing in that file needs to change. 

The bug was purely in Pressable.js's public interface, not a breaking change to any internal files or any of the other Touchables.

**Comment by kmelmon** [comment] 2020-06-18 03:04
Thanks @TheSavior for clarifying.  I do see this hit:
https://github.com/microsoft/react-native-windows/blob/a3467d7effb527e02cc3366d4dac255697285b8b/vnext/src/Libraries/Pressability/Pressability.windows.js#L64
Isn't this the place where we declare the public prop name?  If so this seems to be the only place that needs a rename.

**Comment by TheSavior** [comment] 2020-06-18 03:34
I don’t think so. Pressability is the internal implementation detail of Pressable (and now all the other Touchables as well). Pressable takes the public prop name and passes it into the internal Pressability key with the other name.

**Comment by NickGerleman** [comment] 2020-06-18 16:38
I don't think we have anything custom relying on pressability yet. We make some minor changes to Touchable, but those changes don't touch this prop.

A bit unrelated, but we do have some changes to Pressability itself to support keyboarding. These are 100% gross hacks, and we should really consider thinking about what it would take to do it the right way upstream.

**Comment by NickGerleman** [comment] 2020-06-25 19:26
Confirmed in our 0.63 branch that Touchable internally keeps the `pressRetentionOffset` prop. The only references to `pressRectOffset` are for Pressability config and the forked TouchableWin32.

**Closed by NickGerleman** 2020-06-25 19:26 UTC
Labels: bug

**Comment by NickGerleman** [comment] 2020-06-25 19:30
During discussion there was some mention of hit slop, which is a separate view property (just called `hitSlop`). We don't seem to support it in our view managers. Filing a separate issue for that.
