### ISSUE TITLE
ReactNotificationService: Not receiving notifications in native module sent from host

### ISSUE THREAD

**Issue by mjfusa** [microsoft/react-native-windows#6836] opened 2021-01-08 05:32 UTC
I'm able to send notifications from a native module to the host app, but having difficulty receiving notifications in a native module sent from the host. Code is below. Thanks in advance for your comments.

```C++
//In App.cpp:
App::App() {
    ...
    const ReactNotificationId<void> backgroundNotification{ L"NativeModuleClass", L"BackgroundNotification" };
    ...
}

App::SendNotification() {
    auto myNotification = 
        ReactPropertyBagHelper::GetName(ReactPropertyBagHelper::GetNamespace(L"NativeModuleClass"), L"BackgroundNotification");
    auto rns = InstanceSettings().Notifications();
    rns.SendNotification(myNotification, nullptr, nullptr);
}

//In NativeModuleClass.cpp

NativeModuleClass::Initialize(ReactContext const& reactContext) noexcept	
{
	m_reactContext = reactContext;
	auto myNotification =
        	ReactPropertyBagHelper::GetName(ReactPropertyBagHelper::GetNamespace(L"NativeModuleClass"), L"BackgroundNotification");
    auto rns = m_reactContext.Notifications().Handle();
    bool received = false;
    IReactNotificationSubscription subscription = rns.Subscribe(
        myNotification, nullptr,
        [&received](IInspectable const& /* sender */, IReactNotificationArgs const&  /*args*/) noexcept {
        received = true;  // Not received
        });
}
```

**Comment by chrisglein** [comment] 2021-01-11 19:17
Thanks @mjfusa! Looks like that conversation spawned two bugs. I'm going to dupe this to the other one and it'll be linked so this context isn't lost.

Duplicate of #6840.

**Closed by chrisglein** 2021-01-11 19:17 UTC
Labels: Needs: Triage :mag:, question
