### ISSUE TITLE
Support react-native-config

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/react-native-windows#5310] opened 2020-06-23 08:25 UTC
# Support `react-native-config` on RNW

## Basic Info
- Module Repo URL: [https://github.com/luggit/react-native-config](https://github.com/luggit/react-native-config)
- Target version: 0.61
- [ ] Issue exists on module repo (if so, [link]())
- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?
An AppConsult customer

## In what scenarios will this module be used?
This module allows to expose config variables to your javascript code in React Native through a .env file. The customer is using this module to keep all the default settings of the app in a dedicated configuration file.

## Essential Features
Read a setting from the .env file

**Comment by chrisglein** [comment] 2020-07-16 18:27
@jonthysell What's the status on react-native-config? Did you get it working?

**Comment by asklar** [comment] 2020-07-22 05:39
@chrisglein this is different - this is `react-native-config` which is a native module for handling app configuration. @jonthysell 's thing was the `react-native config` command to get config data about build-time preferences for a project

**Comment by stmoy** [comment] 2020-09-10 17:50
Dupe of #4149

**Closed by stmoy** 2020-09-10 17:50 UTC
Labels: Extensions, Partner: AppConsult, help wanted, must-have
