### ISSUE TITLE
0.65+: run-windows will error out if multiple VS installed

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#8471] opened 2021-08-24 13:07 UTC
Filing on behalf of @tido64 who reached out with this issue

In 0.65 we added running the rnw-depependencies script to CLI health checks. https://github.com/microsoft/react-native-windows/pull/7090

This means any rnw-dependencies bugs will block the build from starting. A bug was identified, where multiple versions of Visual Studio is installed.

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/835219/130621312-496887d5-f0ba-4015-991d-be702cd50f10.png)

The bug that causes this is present in several places in the dependencies script. We execute `vswhere`, which returns multiple paths, but concatenate assuming that only a single path is returned. This creates an invalid path to search for.

```
function CheckCppWinRT_VSIX {
    try {
        $vsWhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        if (!(Test-Path $vsWhere)) {
            return $false;
        }
        $vsPath = & $vsWhere -version 16.5 -property installationPath;
        $natvis = Get-ChildItem "$vsPath\Common7\IDE\Extensions\cppwinrt.natvis" -Recurse;
        return $null -ne $natvis;
    } catch { return $false };
}
```

**Comment by chrisglein** [comment] 2022-02-18 21:41
Duplicate of #9260

**Closed by chrisglein** 2022-02-18 21:41 UTC
Labels: bug, Area: Developer Experience, Area: Dependencies
