### ISSUE TITLE
react-native run-windows fails on shared folders (HOST: Mac OS X <-> VIRTUAL: WIN 10) 

### ISSUE THREAD

**Issue by mtin79** [Microsoft/react-native-windows#1545] opened 2017-12-06 09:51 UTC
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.50.4
2. `npm ls rnpm-plugin-windows`:
edelriddler@0.0.1 S:\edelriddler
`-- rnpm-plugin-windows@0.2.8
3. `npm ls react-native-windows`:
`-- react-native-windows@0.50.0-rc.2
4. `node -v`:
v9.2.0
5. `npm -v`:
5.5.1
6. `yarn --version`:

Then, specify:

- Target Platform: UWP (Windows 10)

- Target Platform Version(s): 10.0.14393, 10.0.10586, UWP

- Target Device(s): Desktop, Mobile (ARM), Mobile Emulator

- Development Operating System: Windows 10 Pro (running on Parallels 13 Pro, hosted by Mac OS X 10.13.1)

- Visual Studio Version: Visual Studio 2017

### Steps to Reproduce

(Write your steps here:)

0. I am logged into a powershell (with admin rights) of a windows 10 pro operating system that runs on Parallels 13 Pro on Mac OS X 10.13.1
1. Change directory into a shared folder of the Mac OS X system that has a react-native app folder which was initialised for iOS and android already.
2. run:
```
$ npm install --save-dev rnpm-plugin-windows
$ react-native windows
$ react-native run-windows
```
3. Building the app fails with the following error:
```
PS S:\edelriddler> react-native run-windows
Scanning folders for symlinks in S:\edelriddler\node_modules (219ms)
Restoring NuGet packages
Building S:/edelriddler/windows/edelriddler.sln
Found MSBuild v15.0 at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
Building Solution: S:/edelriddler/windows/edelriddler.sln
Build configuration: Debug
Build platform: x86
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
obj\x86\Debug\XamlTypeInfo.g.cs(15,25): warning CS1591: Missing XML comment for publicly visible type or member 'XamlMetaDataProvider' [S:\edelriddler\node_modules\react-native-windows\ReactWindows\ReactNative\React
sproj]
React-Native Server already started
Removing old version of the app
Installing new version of the app
& : The term 'windows/edelriddler/AppPackages/edelriddler_1.0.0.0_x86_Debug_Test/Add-AppDevPackage.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of th
or if a path was included, verify that the path is correct and try again.
At line:1 char:3
+ & "windows/edelriddler/AppPackages/edelriddler_1.0.0.0_x86_Debug_Test ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (windows/edelrid...pDevPackage.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Failed to deploy: Command failed: CheckNetIsolation LoopbackExempt -a -n=
```

### Problem

When I copy the folder to a directory maintained by windows it works. But when I run it on a shared folder that is mounted into windows, it fails.
Thanks for any kind of hints or help.

### Intent

The Idea is: Have one folder in the host file system (Mac OS X) have a virtual windows installation accessing it to build and run the windows emulator to test for windows mobile devices and uwp.
Otherwise I would have to copy the folder or use a shared repo between the two systems.

**Comment by rozele** [comment] 2017-12-21 18:36
@mtin79 can you open the solution in the shared folder in Visual Studio on Windows and run from there? There's a known issue with the LookbackExempt CLI functionality where it breaks after you run the solution from Visual Studio. I want to clarify that this issue isn't a dupe of that (#1042).

**Comment by rozele** [comment] 2018-07-23 22:02
Closing due to inactivity.

**Closed by rozele** 2018-07-23 22:02 UTC
