### ISSUE TITLE
FormData request handling missing

### ISSUE THREAD

**Issue by tero-paananen** [microsoft/react-native-windows#10378] opened 2022-08-08 09:26 UTC
### Problem Description

FormData request handling is missing from file 

https://github.com/microsoft/react-native-windows/blob/5cbc25b4f1e90c412f48e4379435a3ea9f387fad/vnext/Shared/Networking/WinRTHttpResource.cpp#L264

I copy/paste old implementation from here 

https://github.com/microsoft/react-native-windows/blob/ae1309301a4662bb5197cccbe6784a40d063f618/vnext/Shared/Modules/NetworkingModule.cpp#L320

and managed to get FormData request to work.

This is breaked maybe in this PR https://github.com/microsoft/react-native-windows/pull/9484

I found open issue about form requests https://github.com/microsoft/react-native-windows/issues/9535

### Steps To Reproduce

fetch FormData network request

### CLI version

7.0.4

### Environment

```markdown
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 20.37 GB / 31.90 GB
  Binaries:
    Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31829.152 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.68.2 => 0.68.2
    react-native-windows: 0.68.12 => 0.68.12
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Snack, code example, screenshot, or link to a repository

How i about fixed this. I took code from https://github.com/microsoft/react-native-windows/blob/react-native-windows_v0.65.14/vnext/Shared/Modules/NetworkingModule.cpp

Added about these:

```
// WinRTHttpResource.cpp
#include <unicode.h>
```

```
// WinRTHttpResource.cpp 

// into PerformSendRequest()

 else if (!data["formData"].empty()) {
      auto formData = data["formData"];
      winrt::Windows::Web::Http::HttpMultipartFormDataContent multiPartContent;

      for (auto& formDataPart : formData) {
        if (!formDataPart["string"].empty()) {
          winrt::Windows::Web::Http::HttpStringContent multipartStringValue{
              Microsoft::Common::Unicode::Utf8ToUtf16(formDataPart["string"].asString()) };
          self->AttachMultipartHeaders(multipartStringValue, formDataPart["headers"]);
          multiPartContent.Add(
            multipartStringValue, Microsoft::Common::Unicode::Utf8ToUtf16(formDataPart["fieldName"].asString()));
        }
        else if (!formDataPart["uri"].empty()) {
          auto filePath = winrt::to_hstring(formDataPart["uri"].asString());
          winrt::Windows::Storage::StorageFile file =
            winrt::Windows::Storage::StorageFile::GetFileFromPathAsync(filePath).get();

          auto stream = file.OpenReadAsync().get();
          winrt::Windows::Web::Http::HttpStreamContent multipartFileValue(stream);
          self->AttachMultipartHeaders(multipartFileValue, formDataPart["headers"]);
          multiPartContent.Add(
            multipartFileValue, Microsoft::Common::Unicode::Utf8ToUtf16(formDataPart["fieldName"].asString()));
        }
      }

      content = multiPartContent;
    } 
```

```
// WinRTHttpResource.cpp

void WinRTHttpResource::AttachMultipartHeaders(winrt::Windows::Web::Http::IHttpContent content, const folly::dynamic& headers) {
  for (auto& header : headers.items()) {
    auto& name = header.first.getString();
    auto& value = header.second.getString();

    content.Headers().Append(
      Microsoft::Common::Unicode::Utf8ToUtf16(name), Microsoft::Common::Unicode::Utf8ToUtf16(value));
  }
}
```

```
// WinRTHttpResource.h

void AttachMultipartHeaders(winrt::Windows::Web::Http::IHttpContent content, const folly::dynamic& headers);
```

**Comment by tero-paananen** [comment] 2022-08-08 09:29
I had conversation about this issue with @asklar

**Comment by tero-paananen** [comment] 2022-08-08 10:27
[react-native-windows+0.68.12.zip](https://github.com/microsoft/react-native-windows/files/9280990/react-native-windows%2B0.68.12.zip)

My current RNW 0.68.12 patch in zip

**Comment by chrisglein** [comment] 2022-08-08 18:10
Based on #9535 this sounds like a known feature gap. @JunielKatarn does that sound correct? Is there a path to bring that functionality back?

Going to close this a dupe. @tero-paananen go ahead and continue any conversation over on #9535.

**Comment by chrisglein** [comment] 2022-08-08 18:10
Duplicate of #9535

**Closed** 2022-08-08 18:10 UTC
Labels: bug, Area: Networking

**Comment by JunielKatarn** [comment] 2022-08-08 23:02
> Based on #9535 this sounds like a known feature gap. @JunielKatarn does that sound correct? Is there a path to bring that functionality back?
> 
> Going to close this a dupe. @tero-paananen go ahead and continue any conversation over on #9535.

Indeed. Form Data support had not been implemented for RNW HTTP in any of its variants.
It is a pending task.

For context, see project https://github.com/microsoft/react-native-windows/projects/42

**Comment by asklar** [comment] 2022-08-09 06:02
@JunielKatarn  From talking to @tero-paananen, my understanding is that this used to work in 0.65 (see the [code in the old networking module](https://github.com/microsoft/react-native-windows/blob/ae1309301a4662bb5197cccbe6784a40d063f618/vnext/Shared/Modules/NetworkingModule.cpp#L320)), but broke when the refactor happened

**Comment by JunielKatarn** [comment] 2022-08-09 22:24
@asklar indeed, I updated my comment:

```
As pointed out, it appears the legacy HTTP module did implement Form Data.
```

I'll address this right after fixing HTTP redirects (current work item).

**Comment by AhmedMustafa505** [comment] 2023-09-19 10:51
Are there any updates regarding formData file upload HTTP request ?
