### ISSUE TITLE
Support rn-fetch-blob

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/react-native-windows#5316] opened 2020-06-23 13:23 UTC
# Support `rn-fetch-blob` on RNW

## Basic Info
- Module Repo URL: [https://github.com/joltup/rn-fetch-blob](https://github.com/joltup/rn-fetch-blob)
- Target version: 
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?
An AppConsult customer

## In what scenarios will this module be used?
The developer is using this module to make file access and data transfer easier and more efficient

## Essential Features
File access and data transfer ones

**Comment by harinikmsft** [comment] 2020-06-30 15:24
Duplicate of #5158

**Closed** 2020-07-01 17:00 UTC
Labels: Extensions, Invalid Triage, Partner: AppConsult, duplicate

**Comment by chiaramooney** [comment] 2023-08-11 00:07
Comment above is correct. It doesn't look like rn-fetch-blob is support but it is listed on our website. Someone should investigate and update the website if needed.

**Comment by chrisglein** [comment] 2023-09-07 18:17
Will track documentation in the linked duplicate issue.
