### ISSUE TITLE
Defork Yoga.cpp

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7600] opened 2021-04-15 20:24 UTC
There seem to be multiple functional changes between RN core's Yoga.cpp and our fork

**Comment by NickGerleman** [comment] 2021-04-21 00:23
Duplicate of #3994

**Comment by NickGerleman** [comment] 2021-04-21 00:25
There is a PR to Yoga which had the fixes from early last year, but the FB team owning it doesn't seem to be accepting contributions to the OSS version.

https://github.com/facebook/yoga/pull/995

**Comment by NickGerleman** [comment] 2021-04-21 00:27
@rozele if the above PR something you might be able to submit FB-side?

**Comment by NickGerleman** [comment] 2021-04-21 00:28
BTW @asklar you can see a diff of our patches if you run `npx react-native-platform-override diff path/to/Yoga.cpp`

**Closed** 2021-04-22 18:18 UTC
Labels: Area: Layout, Deforking, Needs: Triage :mag:, bug

**Comment by rozele** [comment] 2021-09-22 20:48
@NickGerleman I just submitted a request to get this PR imported on Yoga.
