### ISSUE TITLE
Multipart file uploads are missing the boundary

### ISSUE THREAD

**Issue by gillpeacegood** [microsoft/react-native-windows#6046] opened 2020-09-21 13:47 UTC
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: `3.2.1`
2. `npx react-native run-windows --info`: 
```System:
    OS: Windows 10 10.0.18363
    CPU: (2) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Memory: 6.31 GB / 11.73 GB
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @react-native-community/cli: ^3.0.0 => 3.2.1
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
    react-native-windows: ^0.61.9 => 0.61.14
    rnpm-plugin-windows: ^0.4.1 => 0.4.1
  Installed UWP SDKs:
    10.0.18362.0
```
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
```

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. File upload using fetch
2. Fetch params :  request.headers.append("Content-Type", "multipart/form-data");

## Expected Results
File uploads
Instead server was giving a 400 response

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

I found the attached patch fixed the issue for me

```
diff --git a/node_modules/react-native-windows/ReactUWP/Modules/NetworkingModule.cpp b/node_modules/react-native-windows/ReactUWP/Modules/NetworkingModule.cpp
index 7dde77f..9aadefc 100644
--- a/node_modules/react-native-windows/ReactUWP/Modules/NetworkingModule.cpp
+++ b/node_modules/react-native-windows/ReactUWP/Modules/NetworkingModule.cpp
@@ -300,7 +300,8 @@ void NetworkingModule::NetworkingHelper::SendRequest(
       } else if (!bodyData["formData"].empty()) {
         auto formData = bodyData["formData"];
         winrt::Windows::Web::Http::HttpMultipartFormDataContent multiPartContent;
-
+        // reset the content type as we'll need the boundary
+        contentType = nullptr;
         for (auto &formDataPart : formData) {
           if (!formDataPart["string"].empty()) {
             winrt::Windows::Web::Http::HttpStringContent multipartStringValue{
```

**Comment by asklar** [comment] 2020-09-21 16:49
@gillpeacegood we've made lots of changes in this area in the last few releases and 61 is fairly old by now :) , so your best bet will be to upgrade to a newer version (e.g. 0.63).

**Comment by gillpeacegood** [comment] 2020-09-21 18:04
I will be doing that soon, but you might like to look at it anyway as I don't see any evidence the relevant code has changed on your master

Not super important to me as I have a patch (see above)

**Comment by chrisglein** [comment] 2020-09-21 18:17
> I will be doing that soon, but you might like to look at it anyway as I don't see any evidence the relevant code has changed on your master

Sounds like @asklar looked at this and it had migrated?
Glad to hear you have a workaround. We'll see if this is resolved in latest.

**Comment by asklar** [comment] 2020-09-21 19:16
@chrisglein Ah, it looks like we still have 2 NetworkingModule implementations, one for uwp and one for "desktop" so it's possible this still repros after all :(
I'm not sure how to repro the issue in order to verify it though. i.e. how does "file upload using fetch" translate onto repro steps in this case?

**Comment by gillpeacegood** [comment] 2020-09-24 12:09
Hi, we are uploading files pretty much as per the top voted answer here https://stackoverflow.com/questions/42167094/react-native-image-upload

**Comment by chrisglein** [comment] 2020-09-24 18:40
@gillpeacegood You have a fix (thanks!), can you also submit a PR?

**Comment by gillpeacegood** [comment] 2020-09-25 09:56
Yes I will try and do this at some point but it will take a while as I have deadlines to work to at the moment 

I included a patch in the bug report in case you are interested in the solution

**Comment by JunielKatarn** [comment] 2022-02-13 03:41
Related to #8547

**Comment by JunielKatarn** [comment] 2022-11-05 08:22
Root cause found:

Manually setting the `Content-Type` header for multipart/form-data requests overwrites the boundary generated by the WinRT APIs.

The proposed patch fixes the issue fine.
Incorporating into #10797.

**Closed** 2022-11-07 05:09 UTC
Labels: bug, help wanted, Area: Networking
