### ISSUE TITLE
build wpf bundle

### ISSUE THREAD

**Issue by scott108** [Microsoft/react-native-windows#1263] opened 2017-08-03 01:42 UTC
hi,
when I use 
**react-native bundle --platform wpf --entry-file index.wpf.js 
    --bundle-output wpf\tte\ReactAssets\index.wpf.bundle
    --assets-dest wpf\tte\ReactAssets**  
to build index.wpf.bundle, and I got **Unrecognized platform: wpf** message

**Comment by sayar** [comment] 2017-08-04 18:50
Hi @scott108, did you run `npm i rnpm-plugin-wpf` or `yarn add rnpm-plugin-wpf` and `react-native wpf` before trying to run the bundle command?

**Comment by scott108** [comment] 2017-08-07 06:10
Hi @sayar , I just run `npm i rnpm-plugin-windows` and `react-native wpf`, is there anything different??

**Comment by sayar** [comment] 2017-08-07 13:17
Yep, you gotta run `npm i rnpm-plugin-wpf` (note the wpf instead of windows) to be able to add wpf platform support. Let me know if that fixes your problem so I can close this issue.

**Comment by scott108** [comment] 2017-08-08 01:27
If i only run `npm i rnpm-plugin-wpf`, and I got Unrecognized command 'wpf' message after `react-native wpf`
![image](https://user-images.githubusercontent.com/7892590/29052273-8f5e9c9a-7c1b-11e7-9844-f2e379ef8455.png)

**Comment by sayar** [comment] 2017-08-08 14:41
@scott108, I wasn't able to reproduce this error. Can you please share what versions of react-native you are using?

**Comment by scott108** [comment] 2017-08-09 01:20
Hi @sayar, here is my package.json
```
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.1"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.1.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by dpitre** [comment] 2017-09-18 13:47
You are missing react-native-windows.
```
npm install --save-dev rnpm-plungin-wpf
npm install --save-dev react-native-windows
react-native wpf
```

**Comment by Javis1205** [comment] 2018-02-02 01:41
Can you help me about this issue

**Comment by Javis1205** [comment] 2018-02-02 07:34
@sayar can you help me?

**Comment by ncomo11** [comment] 2018-06-05 10:08
In order to create bundle for WPF platform use 'windows' option instead of 'wpf':

`react-native bundle --platform **windows** --entry-file **index.js** --bundle-output wpf\samplewpfapp\ReactAssets\index.wpf.bundle --assets-dest wpf\samplewpfapp\ReactAssets`

Alter refer:
1. https://github.com/Microsoft/react-native-windows/issues/1801
2. https://github.com/Microsoft/react-native-windows/issues/1539

**Comment by rozele** [comment] 2018-07-23 21:13
Looks like @ncomo11 might have the correct solution here. Please advise if this needs to be re-opened.

**Closed by rozele** 2018-07-23 21:13 UTC
