### ISSUE TITLE
PR CI only builds some flavors (need daily validation of other flavors)

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#4308] opened 2020-03-13 02:25 UTC
The PR CI loop only builds x86 Debug, x64 Release, and arm Release configurations.

We need to decide which flavors are necessary to gate PRs, and build the rest at another time.

**Comment by chrisglein** [comment] 2020-04-14 18:28
Jon has already spent attention on building out the various flavors. For the rest of this work:
Duplicate of #4567

**Closed by chrisglein** 2020-04-14 18:28 UTC
Labels: Area: Infrastructure, bug, must-have, needs dev design
