### ISSUE TITLE
List of  Repos that work with RNW 

### ISSUE THREAD

**Issue by velociwabbit** [microsoft/react-native-windows#2824] opened 2019-07-24 22:39 UTC
Even with the hiccups i have encountered I am a big, big fan of RN-W.   It is the right approach... Finally!

What is needed is a set of repos supporting v59 or v60 that are able to be easily installed with the latest release.

Most of the repos for RN I have tried require expo or are not compatible with this release.  

I am willing to help put together and test  a list of the projects if someone can provide some input as to which ones work now, or could work with a bit of tinkering..

Nice work!  The finish line is within sight!

**Comment by harinikmsft** [comment] 2019-07-31 19:11
Thanks for trying out rnw-vnext @velociwabbit. We are still pretty heads down in getting the core infrastructure and APIs working at full parity and we haven't begun testing external modules. 

Also, we are currently in the middle of providing the native modules/view managers story for targeting RNW-vnext. So, any of the community modules that need this story will not currently support RNW-vnext yet. 

We would love to get your help in testing out any community modules that are purely JS. We know of a few that work, like - [react-native-table](https://github.com/Gil2015/react-native-table-component) and several others that are purely JS. 

We may not be able to get around to inventorying this atleast until September - so in the meantime, if you would like to help, that would be great! If you are trying stuff out, feel free to add the list of supported vs. unsupported right below this issue in comments and we will try to have that published once it gets to maturity.

**Comment by velociwabbit** [comment] 2019-07-31 19:42
Great i will try them.

Only too willing to help make this a success.

**Comment by stmoy** [comment] 2020-02-10 17:55
We're working with Facebook, Expo, and the community to help surface this information as part of https://github.com/react-native-community/discussions-and-proposals/issues/190

**Comment by chrisglein** [comment] 2020-06-09 18:48
Check out what stmoy linked above, but also we've done work to have Windows modules listed with Expo's module directory: #5049

Duplicate of #5049

**Closed by chrisglein** 2020-06-09 18:48 UTC
Labels: Documentation, Extensions, Invalid Triage, help wanted
