### ISSUE TITLE
Global monitoring of keyboard key events

### ISSUE THREAD

**Issue by ShaoGongBra** [microsoft/react-native-windows#12527] opened 2023-12-09 01:43 UTC
### Summary

Implement a method similar to JavaScript that can globally listen to keyboard keys without binding this event to a specific component

### Motivation

Need to globally implement shortcut keys, such as pressing Ctrl+M to open a menu

**Comment by chrisglein** [comment] 2023-12-14 19:11
Duplicate of #3449

**Closed by chrisglein** 2023-12-14 19:11 UTC
Labels: Needs: Triage :mag:, enhancement, Area: Keyboard
