### ISSUE TITLE
high CPU usage when using simple animation

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#860] opened 2016-11-06 18:42 UTC
On a Surface Book i7 running latest Windows 10 Insider slow build (14936), the animation below uses 10-20% CPU on average. I would expect this kind of scaling animation to be GPU accelerated as in straight WPF, and have <2% CPU usage as in a regular UWP/WPF application.

         <View style={Styles.controlsSection}>
            <Animatable.View 
              animation="pulse" 
              iterationCount="infinite" 
              style={Styles.attendeesButton}
            >
              <Text style={Styles.attendeesText}>6</Text>
            </Animatable.View>
          </View>

the styles referenced:
  controlsSection: {
    flex: 1,
    padding: Metrics.doubleBaseMargin,
    alignItems: 'flex-end',
  },
  attendeesText: {
    color: Colors.snow,
    textAlign: 'center',
    ...Fonts.style.h3
  }

package versions from package.json:
  "dependencies": {
    "react": "15.3.2",
    "react-native": "0.37.0-rc.3",
    "react-native-animatable": "^0.6.1",
    "react-native-windows": "0.37.0-rc.0"
  },

**Comment by rozele** [comment] 2016-11-07 16:24
@matthargett not likely to solve the issue, but there is the option of using native animations.  The problem is the way that animations work in React Native.  They are all JavaScript driven, so you can think of these basically as a bunch of sequential layout operations at 60 FPS.  The native animations at least uses a more declarative approach so there isn't the requirement of bridge chatter 60 times a second.

You could consider alternate declarative animation options (like the way layout animation works) that uses the UWP / WPF animation APIs, but it would not align with the "regular" React approach for animation.

**Comment by rozele** [comment] 2018-07-23 20:34
Likely that native animations could improve this. This is more of a general issue with bridge driven animations in react-native than a react-native-windows specific issue. Closing.

**Closed by rozele** 2018-07-23 20:34 UTC
