### ISSUE TITLE
Can react native windows use WinUI3 Desktop project Instead of UWP?

### ISSUE THREAD

**Issue by RekiDunois** [microsoft/react-native-windows#7510] opened 2021-04-02 10:05 UTC
I follow what [doc](https://microsoft.github.io/react-native-windows/docs/getting-started) said to add `--useWinUI3` flag while using `npx react-native-windows-init`. And I got a UWP project. I think WinUI3 is able to create the Desktop App, how could I do that while using react native windows?

**Comment by Omar-Belghaouti** [comment] 2021-04-02 18:50
Of course, check the [the docs](https://microsoft.github.io/react-native-windows/docs/getting-started)!

**Comment by vmoroz** [comment] 2021-04-03 02:20
I am not sure if can create the whole Desktop app. I would defer the definite answer to @asklar .
I just want to say that we usually use RN in a desktop app as XAML island and you can see how we do it in this sample project: https://github.com/microsoft/react-native-windows/blob/master/packages/playground/windows/playground-win32.sln

**Comment by vmoroz** [comment] 2021-04-03 02:41
This issue #7359 maybe related to your question.

**Comment by asklar** [comment] 2021-04-03 04:14
Hi @RekiDunois, we don't currently support the kind of desktop app available with Reunion 0.5. 

To hopefully clarify, there are 3 kinds of apps:
- UWP - available with WinUI 3 prerelease package and system XAML. We have templates for this.
- Xaml islands - available with WinUI 3 prerelease package and system XAML. No templates.
- Desktop apps - new type of app for Reunion, not yet supported/tested with React Native for Windows.

**Comment by asklar** [comment] 2021-04-03 04:14
Duplicate of #7359

**Closed by asklar** 2021-04-03 04:14 UTC
Labels: Needs: Triage :mag:, question
