### ISSUE TITLE
Warning C4834 when compiling ReactCommon, Microsoft.ReactNative

### ISSUE THREAD

**Issue by Drigax** [microsoft/react-native-windows#7366] opened 2021-03-12 23:24 UTC
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
5.0.1-alpha.0

2. `npx react-native info`:
```
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
    Memory: 11.03 GB / 31.92 GB
  Binaries:
    Node: 14.16.0 - D:\Programs\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.0 - D:\Programs\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 22.0.7026061
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.10586.0, 10.0.16299.0, 10.0.17134.0, 10.0.17749.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31105.61 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: ^4.13.0 => 4.13.1
    react: ^17.0.1 => 17.0.1
    react-native: ^0.64.0-rc.0 => 0.64.0-rc.2
    react-native-windows: ^0.64.0-0 => 0.64.0-preview.5
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Use react-native-windows ^0.64.0 as a dependency
2. Build a react-native-windows project using visual studio v16.9.1

## Expected Results
Describe what you expected to happen.
Project should build without warnings.

[buildFailureLog.txt](https://github.com/microsoft/react-native-windows/files/6133619/buildFailureLog.txt)

## Snack, code example, screenshot, or link to a repository:
Reproducible via: https://github.com/BabylonJS/BabylonReactNative/

**Comment by NickGerleman** [comment] 2021-03-13 02:02
@Drigax this issue should be fixed in the latest preview. Could you try updating to 0.64.0-preview.15?

**Comment by asklar** [comment] 2021-03-13 03:16
Duplicate of #7248

**Closed by asklar** 2021-03-13 03:16 UTC
Labels: Needs: Triage :mag:, bug
