### ISSUE TITLE
TextInput inside ScrollView not rendered until app window is resized

### ISSUE THREAD

**Issue by capc0** [microsoft/react-native-windows#6354] opened 2020-10-28 21:51 UTC
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 4.13.0
2. `npx react-native run-windows --info`:
```
System:
    OS: Windows 10 10.0.18362
    CPU: (16) x64 AMD Ryzen 7 1700 Eight-Core Processor
    Memory: 9.23 GB / 15.94 GB
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: ^0.63.0-0 => 0.63.5
  Installed UWP SDKs:
    10.0.15063.0
    10.0.16299.0
    10.0.18362.0
```
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

have an App.tsx like the following

```tsx
const App = () => {
    return (
        <ScrollView>
            <TextInput
                style={{ backgroundColor: 'yellow' }}
            />
            <Button onPress={() => { }} title="test"></Button>
        </ScrollView>
    );
};
```

--> the TextInput is not rendered. When I resize the app window (1px is enough), it gets renderer however.

## Expected Results
TextInput and Button should be visible/rendered

## Snack, code example, screenshot, or link to a repository:

![image](https://user-images.githubusercontent.com/27284008/97500529-0e302580-1970-11eb-9b65-f124846e5f51.png)

**Comment by NickGerleman** [comment] 2020-10-29 02:16
Separately tracking with https://github.com/microsoft/react-native-windows/issues/5437 and some of its dupes.

We should really try to take a look at this one soon. I think we've brought it up as a potential release blocker for the past couple releases, but I'm not sure anyone is currently working on it.

**Comment by capc0** [comment] 2020-10-29 07:14
thanks for your fast response. Are you implying that earlier versions might not be affected by this bug? I could maybe downgrade in that case.

**Comment by chrisglein** [comment] 2020-11-02 19:29
@rectified95 Can you check to see if this is a clean dupe of #5437 and when this repros (what versions)?

**Comment by rectified95** [comment] 2020-11-02 23:07
This is a good repro - the issue happens even if the TextInput is not inside a ScrollView. It is a dupe of #5437, though.

**Closed by rectified95** 2020-11-02 23:07 UTC
Labels: Area: Layout, Area: TextInput, bug

**Comment by rectified95** [comment] 2020-11-07 00:40
Addressing this in #6451 
cc @NickGerleman @capc0
