### ISSUE TITLE
React Native application window becomes blank screen when explorer.exe is restarted

### ISSUE THREAD

**Issue by sebastso** [microsoft/react-native-windows#2066] opened 2019-02-14 21:10 UTC
When the explorer.exe is restarted, the react native windows screen becomes blank and application becomes not responsive, it only happens on Released app and MS suggestion to force the app to run on UI thread has temporarily fixed the problem, looking for a long term solution for the same.

**Comment by harinikmsft** [comment] 2019-02-14 23:42
Thanks for filing this @sebastso. Our engineers are looking into the issue. I will update as soon as we have narrowed down the root cause.

**Comment by harinikmsft** [comment] 2019-02-27 21:03
Update - the team has root caused the issue and working on the fix. I will update this thread once it is fixed.

**Comment by sebastso** [comment] 2019-02-27 23:26
Thanks for the update @harinikmsft

**Comment by kmelmon** [comment] 2019-03-26 17:49
After discussing with devs here in the Windows UX Platform team and looking at the code, we don't actually see much benefit in running layout off-thread.  

A little background:  For native XAML apps that don't use react-native, there is no separate layout thread, in fact even app code runs on the same thread and we rarely see responsiveness issues.  With react-native, there is a javascript thread which is typically running the app code so there's already a higher degree of parallelism than a native XAML app.

The recommended fix here is to undefine the CREATE_LAYOUT_THREAD constant, but keep the rest of the code just in case we need to bring it back for some reason.  @sebastso feel free to make this change in master as well as any copy you might have.

**Comment by sebastso** [comment] 2019-03-26 19:29
Thanks, I tried to make this change by createing a Pull request, but
somehow I'm not able to create a branch:
$ git push --set-upstream origin sebastso/rnwcs_remove_uithread_issue
remote: Permission to Microsoft/react-native-windows.git denied to sebastso.
fatal: unable to access '
https://github.com/Microsoft/react-native-windows.git/': The requested URL
returned error: 403

-Sony

**Comment by kmelmon** [comment] 2019-03-27 00:09
Sorry about the confusion - the permissions requirement is intentional - we don't allow topic branches to be created in this repo as we want to keep the repo limited to stable releases - this reduces confusion for folks taking drops.

The recommended way to submit PRs is to first create a fork of the repo, then create a topic branch off of that fork.  You can push these private branches without any permissions requirements.  See the readme for more details.

**Comment by kmelmon** [comment] 2019-08-29 19:30
This is specific to 'current'.  @rozele it looks like PR #2530 was supposed to fix this but it was never checked in.

**Closed** 2020-03-24 09:00 UTC
Labels: .NET, help wanted
