### ISSUE TITLE
The various boolean RNW CLI options specify defaults which are ignored

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#8630] opened 2021-09-14 23:03 UTC
Discovered while writing #8253.

Commander (the library used by the RN CLI to define/parse CLI args) does
not support setting defaults for boolean flags. All such options are
resolved to either `true` (if present) or `undefined` (if specified in
the --no-flag format and present).

We set defaults in our code, thinking it affects how Commander parses our options, but it doesn't. We should stop setting the defaults altogether rather than set up misleading expectations on what the options should contain.

**Comment by asklar** [comment] 2021-09-16 03:16
Duplicate of #6759

**Closed** 2021-09-16 17:35 UTC
Labels: bug, Needs: Triage :mag:
