### ISSUE TITLE
10mb limit on fetch

### ISSUE THREAD

**Issue by jbcullis** [microsoft/react-native-windows#9510] opened 2022-02-09 16:27 UTC
### Problem Description

There seems to be a 10mb limit on fetch responses before they get truncated with react-native-windows, is there a way to increase that value?
We can load the same dataset up on mac, android and ios.

### Steps To Reproduce

Fetch a dataset greater than 10mb and result will be trucated.

### Expected Results

Entire result set should be returned.

### CLI version

npx react-native --version

### Environment
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 21.85 GB / 31.73 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0, 10.0.22000.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.0.31912.275 (Visual Studio Community 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-windows: 0.66.5 => 0.66.5
  npmGlobalPackages:
    *react-native*: Not Found

```markdown
npx react-native info
```

**Comment by jbcullis** [comment] 2022-02-11 12:56
@jonthysell I didn't want to post api details publicly so I've emailed you a fetch example that will throw the json convert error due to truncating the response.

**Comment by NickGerleman** [comment] 2022-02-12 02:48
@JunielKatarn is doing some intersecting work around replacing the HTTP implementation, to unify the impl between open source and office. Adding him to this thread, in case he has any insight into the limitation in OSS.

**Comment by JunielKatarn** [comment] 2022-02-13 00:59
> 

Unfortunately, we ARE enforcing a hard-coded 9.54 MB limit:
https://github.com/microsoft/react-native-windows/blob/react-native-windows_v0.67.1/vnext/Shared/Modules/NetworkingModule.cpp#L136

While I have refactored this module in #9484, I did not fix any of the existing problems (i.e lacking timeout support).
I will be opening specific GitHub items to address any remaining issues.

**Comment by jbcullis** [comment] 2022-02-13 01:18
Thanks @JunielKatarn - for now I've just upped the limit in my environment. Is that limit considering compressed content or is it kicking in after decompression?

**Comment by jbcullis** [comment] 2022-02-13 01:52
@jonthysell Do you guys need me to leave that endpoint open for testing or can I close it off?

**Comment by JunielKatarn** [comment] 2022-02-13 04:32
> @jonthysell Do you guys need me to leave that endpoint open for testing or can I close it off?

You can close it for now.
We are able to emulate an HTTP response of an arbitrary size.

I may ask you to open the endpoint again once we start dealing with response compression.

FYI, we have set up the GitHub project to track overall HTTP completion.
https://github.com/microsoft/react-native-windows/projects/42

**Comment by NickGerleman** [comment] 2022-02-13 12:20
Moving this to bug, since it is confirmed to be a defect in our implementation.

**Closed** 2022-05-20 22:26 UTC
Labels: bug, Area: Networking, Needs: Environment Info

**Comment by jbcullis** [comment] 2022-11-12 09:48
Issue remains on .70

\react-native-windows\Shared\Networking\WinRTHttpResource.cpp
co_await reader.LoadAsync(10 * 1024 * 1024);

**Comment by chrisglein** [comment] 2022-11-14 19:15
@JunielKatarn Can you take a look that this? You merged a PR back in May that should have addressed this, and that code definitely should be in 0.70. There were explicit backports up to 69 but that's because this made the cutoff for 70.

**Comment by JunielKatarn** [comment] 2022-11-14 22:11
@chrisglein @jbcullis this issue was overlooked when implementing Blob support.

The code below is current for both `0.70-stable` and `main` branches.
I'll send a PR to apply the same fix for that case.

<img width="584" alt="image" src="https://user-images.githubusercontent.com/4507319/201778290-7ef48b65-3e29-4e96-9079-8ce085c64438.png">

**Comment by JunielKatarn** [comment] 2022-11-14 22:13
@jbcullis Do you have concrete steps that hit the fixed size request fetch? (Line 415):
<img width="429" alt="image" src="https://user-images.githubusercontent.com/4507319/201779033-4a6895ff-15ae-4062-bc47-a796463f8acc.png">

**Comment by JunielKatarn** [comment] 2022-11-16 20:27
@jbcullis The fix #10885 has been merged yesterday.
