### ISSUE TITLE
experimentalNuGetDependency not working for library project type

### ISSUE THREAD

**Issue by jeanmaried** [microsoft/react-native-windows#7822] opened 2021-05-21 17:22 UTC
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
`5.0.1-alpha.2`
2. `npx react-native info`:
```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 13.26 GB / 31.81 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.16299.0, 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31229.75 (Visual Studio Enterprise 2019)
  Languages:
    Java: 1.8.0_292 - C:\Program Files\OpenJDK\openjdk-8u292-b10\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-windows: microsoft:master => 0.64.8
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. create a module and cd into it
2. `npx react-native-windows-init --version latest --projectType lib --language cs --overwrite`
2. open .sln in visual studio
3. build solution

## Expected Results
Experimental Nuget should be referenced and the library should build.

Right now it seems that references are still pointing to node_modules and not to the nuget. Build fails with this output:

```
Build started...
1>------ Build started: Project: AppExample, Configuration: Debug x64 ------
1>  Discovered package 'react-native-windows' with version '0.64.8'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): warning MSB3243: No way to resolve conflict between "Microsoft.ReactNative, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime" and "Microsoft.ReactNative". Choosing "Microsoft.ReactNative, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime" arbitrarily.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): warning MSB3243: No way to resolve conflict between "Microsoft.ReactNative.Managed, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" and "Microsoft.ReactNative.Managed". Choosing "Microsoft.ReactNative.Managed, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" arbitrarily.
1>  Missing file: C:\Code\win-app-comcent\libraries\app-example\node_modules\react-native-windows\target\x64\Debug\Microsoft.ReactNative.Managed\Microsoft.ReactNative.Managed\Microsoft.ReactNative.Managed.dll
1>EXEC : error : Unsupported argument '/r:C:\Code\win-app-comcent\libraries\app-example\node_modules\react-native-windows\target\x64\Debug\Microsoft.ReactNative.Managed\Microsoft.ReactNative.Managed\Microsoft.ReactNative.Managed.dll'
1>  -- sourceFile (s)   C# Source files to analyzer and generate code for.
1>  -- reference (r)    The references needed to load those source files.
1>  -- define (/d)      The defines used in the source files.
1>  -- outputFile (/o)  The output path to write the generated file in.
1>  -- nameSpace (/ns)  The namespace to put the generated class in.
1>  -- help (/h)        Shows this help.
1>C:\Users\DalmassJ\.nuget\packages\microsoft.reactnative.managed.codegen\0.64.8\build\Microsoft.ReactNative.Managed.CodeGen.targets(62,5): error MSB3073: The command "C:\Users\DalmassJ\.nuget\packages\microsoft.reactnative.managed.codegen\0.64.8\tools\Microsoft.ReactNative.Managed.CodeGen.exe @C:\Code\win-app-comcent\libraries\app-example\windows\AppExample\obj\x64\Debug\AppExample.ReactNativeCodeGen\AppExample.ReactNativeCodeGen.rsp" exited with code 1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

<img width="234" alt="references" src="https://user-images.githubusercontent.com/28982554/119175262-388e2100-ba2f-11eb-834c-829dcec2d123.PNG">

**Comment by asklar** [comment] 2021-05-22 06:35
Duplicate of #7473

**Comment by chrisglein** [comment] 2021-05-24 18:12
Duplicate of #7227

**Closed by chrisglein** 2021-05-24 18:12 UTC
Labels: Needs: Triage :mag:, bug, duplicate
