### ISSUE TITLE
`secureTextEntry` when it is set to `<TextInput secureTextEntry={true} />` causes the TextInput to not render

### ISSUE THREAD

**Issue by dzunisanindlhovu** [microsoft/react-native-windows#4371] opened 2020-03-20 03:52 UTC
### Environment

If you are using latest version:
1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.61.5

2. `react-native run-windows --info`:

Otherwise if `--info` doesn't exist:
1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.61.5

2. `npm ls rnpm-plugin-windows`:
-- (empty)

3. `npm ls react-native-windows`:
react-native-windows@0.61.0-beta.44

4. `node -v`:
v12.10.0

5. `npm -v`:
6.10.3

6. `yarn --version`:
1.22.0

Then, specify:

10.0,18362.0

- Target Platform Version(s):
x64

- Target Device(s):
Windows 10 PC

- Visual Studio Version:
 Visual Studio 2019

- Build Configuration: Debug

### Steps to Reproduce

(Write your steps here:)

1. Get a clean version a new React Native Windows App environment. 
2. The only code you need is below.
`<TextInput secureTextEntry={false} />`
`<TextInput secureTextEntry={true} />`

3. You will notice that the first one renders but the second one doesn't render.

### Expected Behavior

(Write what you thought would happen.)
I expected this `<TextInput secureTextEntry={true} />` to give me a TextInput for a password.

### Actual Behavior

(Write what happened. Add screenshots!)
This didn't render anything `<TextInput secureTextEntry={true} />`

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

### Additional context

(Write any other additional context that may help in root causing the issue.)
Basically, this issue stems from C++/WinRT using 2 seperate UI elements for handling password and text i.e. `winrt::Windows::UI::Xaml::Controls::PasswordBox` and `winrt::Windows::UI::Xaml::Controls::TextBox` , whereas react native only uses `<TextInput secureTextEntry={true/false} />` . The TextInputViewManager.cpp in ReactUWP attempts to swap out the PasswordBox and the TextBox depending on what the value of secureTextEntry is. This is where the TextInput fails to render in React Native.

![image](https://user-images.githubusercontent.com/44168415/77134019-86218f00-6a22-11ea-9117-793000eba7f2.png)

The ReparentView just leads to the ShadowNodeBase.cpp where it tries to swap out the PasswordBox with the `TextBox` 

![image](https://user-images.githubusercontent.com/44168415/77134093-cd0f8480-6a22-11ea-9b79-01b04cea5085.png)

The only way I could ever get the PasswordBox to render was to comment out this line and replace it with the winrt::PasswordBox like as you can see in the screenshot below. I also had to fix a few exceptions.
![image](https://user-images.githubusercontent.com/44168415/77134198-342d3900-6a23-11ea-8aa4-aaaf1a8f28e8.png)

**Comment by namrog84** [comment] 2020-03-20 08:54
Note: Bug filed for Xbox partner team.

**Comment by kmelmon** [comment] 2020-04-13 23:42
I'll take this bug.

Debugging through the problem happens here:

void ShadowNodeBase::ReparentView(XamlView view) {
  GetViewManager()->TransferProperties(m_view, view);
  if (const auto instance = GetViewManager()->GetReactInstance().lock()) {
    if (const auto nativeUIManager = static_cast<NativeUIManager *>(instance->NativeUIManager())) {
      int64_t parentTag = GetParent();
      auto host = nativeUIManager->getHost();
      auto pParentNode = static_cast<ShadowNodeBase *>(host->FindShadowNodeForTag(parentTag));
      if (pParentNode != nullptr) {
        pParentNode->ReplaceChild(m_view, view);

parentNode ends up null so no re-parenting actually happens.  Uh oh.  We need that parent to be non-null so we can actually swap the PasswordBox in as the new child.

I think the reason why we're having an issue is in the scenario where you create a TextInput with secureTextEntry initially set to true.  In this case we're updating the properties on the TextInput before its backing view has been put in the tree.  I'll need to study how we handle this sort of case for other element types that swap out the backing view dynamically.

**Comment by dzunisanindlhovu** [comment] 2020-04-14 00:44
Hi @kmelmon thanks for grabbing this. I have since discovered a workaround for this issue that may help you resolve the bug.

`<TextInput style={{height: 40, alignSelf:'stretch'}} secureTextEntry={true} />`

Basically adding those 2 properties in the `style` enables the `PasswordBox` to render and be clearly visible. I don't know about the innerworking of the `style` but it seems like it causes the PasswordBox to be rerendered properly. Let me know if this helps.

**Comment by kmelmon** [comment] 2020-04-15 05:24
Bug understood.  When we re-parent the new control, we forgot to inform the UIManager which maintains a mapping from shadow node => backing XAML element.  This mapping not being updated caused us to not measure the new XAML element, and then after layout completes, we end up pushing the wrong values back into the backing XAML element.

Fix is straightforward.  Will have this checked in soon.

**Comment by kmelmon** [comment] 2020-04-15 16:46
@chrisglein I marked the PR as "Fixes 4371", but the issue is still open.  Isn't the bot supposed to auto-close?

Closing manually...

**Closed by kmelmon** 2020-04-15 16:46 UTC
Labels: Area: TextInput, Partner: Stream, bug, must-have

**Comment by chrisglein** [comment] 2020-04-15 18:09
@kmelmon looks like it has to be in the PR description, not in comments: https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by kmelmon** [comment] 2020-04-15 18:13
@chrisglein thanks!  I think I've done this before, will try to remember.
