### ISSUE TITLE
Getting Started fails with "Cannot find module '@react-native-community/cli/build/tools/copyAndReplace'"

### ISSUE THREAD

**Issue by anaisbetts** [microsoft/react-native-windows#4882] opened 2020-05-12 23:28 UTC
### Environment

If you are using latest version:
1. `react-native -v`: `error: unknown option -v`
2. `react-native run-windows --info`:

```
  System:
    OS: Windows 10 10.0.19624
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 3.44 GB / 15.96 GB
  Binaries:
    Node: 10.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
    react-native-windows: ^0.61.9 => 0.61.9
  Installed UWP SDKs:
    10.0.17763.0
    10.0.18362.0
```

3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`

```
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1
```

### Steps to Reproduce

1. Follow verbatim the steps described at https://microsoft.github.io/react-native-windows/docs/getting-started
2. Get to `npx react-native-windows-init --overwrite` and run it

### Actual Behavior

```
npx react-native-windows-init --overwrite

npx: installed 114 in 5.983s
Reading application name from package.json...
Reading react-native version from node_modules...
Reading react-native version from node_modules...
Latest matching version of react-native-windows for react-native@0.61.5 is react-native-windows@0.61.9
Installing react-native-windows@^0.61.0-0...
l peer dependencies yourself.
dependencies yourself.
npm WARN eslint-plugin-react@7.12.4 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.6.0 requires a peer of eslint@^3.17.0 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
y"} (current: {"os":"win32","arch":"x64"})
react-native-windows@0.61.9 successfully installed.
Cannot find module '@react-native-community/cli/build/tools/copyAndReplace'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\ana\Desktop\foo\rnwin\node_modules\react-native-windows\local-cli\generator-common\index.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by NickGerleman** [comment] 2020-05-13 02:38
@acoates-ms this has popped up in a couple of threads. Any idea what might be going on here?

**Comment by NickGerleman** [comment] 2020-05-13 02:41
Same as https://github.com/microsoft/react-native-windows/issues/4564

Multiple users reported. Version shown is 0.61.5. Adding a dev dependency supposedly fixes the issue.

Happening in the local CLI, so likely not an issue with react-native-windows-init unless rnpm-plugin-windows was unintentionally bringing something in earlier we relied on.

**Comment by chrisglein** [comment] 2020-05-14 18:15
@anaisbetts Try the solutions in the linked issue #4564 and hopefully that resolves this for you.
We've added a yellow box tip for this in the installation page for the doc.
Duplicate of #4564

@kikisaints We could buff up that yellow box to list the error, or add detection to know if you're in this state (warn if you have a global installation)

**Comment by dstaley** [comment] 2020-05-21 03:02
Just a heads up, even running the following still leads to the same error:

```
npx --ignore-existing react-native init project --version ^0.61.5
cd project
npx --ignore-existing react-native-windows-init --overwrite
```

**Closed** 2020-06-11 06:00 UTC
Labels: Invalid Triage, Needs: Author Feedback, bug, no-recent-activity
