### ISSUE TITLE
Add hovered and focused states to Pressable

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#5588] opened 2020-07-24 20:25 UTC
Spinning off a separate issue to track @TheSavior 's comment in #5512  :

> It might not be necessary, but I could expect Pressable to pass in the state object `hovered` and `focused`, where right now it just passes `pressed`. [Pressable states](https://github.com/facebook/react-native/blob/0.63-stable/Libraries/Components/Pressable/Pressable.js#L222-L223)
> 
> `hovered` is probably more valuable than `focused`, but the API was designed to enable platforms to add more things like that.

@kikisaints : look into this as you are writing up the proposal for hover states/pointer APIs.

**Comment by kikisaints** [comment] 2020-07-24 20:26
Connected to issue #2099

**Comment by chrisglein** [comment] 2020-07-30 18:35
Duplicate of #2099

**Closed by chrisglein** 2020-07-30 18:35 UTC
Labels: Needs: Triage :mag:, Proposal
