### ISSUE TITLE
TextInput and Picker on Navigator -> It's possible to "activate" Picker from another scene

### ISSUE THREAD

**Issue by everyusernameistaken123** [Microsoft/react-native-windows#969] opened 2017-02-03 13:13 UTC
Hi,

I found an issue which is hard to describe - and also hard to reproduce :( 
There is an Navigator-Element involved on top of things, managing multiple scenes.
On some scenes, there are TextInput-Elements, on one scene there is also a TextInput together with an Picker.
Lets describe it this way:
Scene A: TextInput + Picker
Scene B1...n: Only Views + Text + Buttons
Scene C: Multiple TextInputs
I am navigating through all scenes A - B - C, i.e. all are rendered at some time of execution.
When I use [Tab]-Key to switch through inputs on Scene C, it basically works fine.
But after the last TextInput, there seems to be no input selected. Pressing [Arrow Down]-key then can lead to PickerItems (from Scene A!) being shown.
They are at the bottom of the screen, i.e. not where the Picker is usual. And it is only the Picker-Items-selection, not the Picker or Scene A itself visible.

I wasn't able to find anyone on the web who had a similar issue? And yes, it is weird to reproduce, but at some point in time, users doing everything wrong :-P

**Comment by matthargett** [comment] 2017-02-04 03:45
Do you have sample code that reproduces this issue (even intermittently) in a repo we can access?

**Comment by everyusernameistaken123** [comment] 2017-02-04 08:23
I'm sorry, I found this bug in a bigger project, hosted on my company's repo. Can't promise to find time extracting a simple example where this issue occurs.

**Comment by rozele** [comment] 2017-02-06 21:12
I can definitely see where this can happen... I imagine the navigator is rendering all the scenes simultaneously, or at least not recycling the scenes when navigating to a new scene, so tab somehow finds an element from a previous scene.  One workaround you could try is to add a "disabled" prop to tab stop elements in each scene and set it to `true` when you navigate away from the scene.  I think both picker and textinput have the `disabled` prop already.

I think we'll want to consider options for a core fix for this, but it could take some time.  Are there form-filling react-native apps out there for iOS and Android that automatically skip from user input to user input?  How do these avoid this problem with navigator (since the navigator implementation is not specialized for Windows)?  Perhaps "clipping" takes care of this.

**Comment by everyusernameistaken123** [comment] 2017-02-07 20:25
You are totally right... The Navigator is rendering all scenes at once. Which is kind of strange, getting all "componentWillMount" events at the beginning of program-execution. But well, it does not make any performance-problems. So I got used to it and think I am fine for now with your proposed workaround (using "disabled").

Thanks!

**Closed** 2017-07-17 20:21 UTC
