### ISSUE TITLE
Cannot read property 'onStartShouldSetResponderCapture' of undefined

### ISSUE THREAD

**Issue by nhan27165** [Microsoft/react-native-windows#1119] opened 2017-05-17 03:29 UTC
Hi all
As the title, I met the problem when developing windows application (on version 0.43.0-rc)
Source code just has:
`<View>
    <Text>test</Text>
</View>
`
When I click on text **test**, this error occurs:
![d24ae50e3576d12017342461b5f0b737](https://cloud.githubusercontent.com/assets/9447209/26137270/5be4793c-3aeb-11e7-9372-81f07f4630a7.png)

The temporary solution is using version:  0.42.2

**Comment by matthargett** [comment] 2017-05-17 22:12
Can you try reproducing this with version 42?

Generally, a lot of React Native developers are sticking with version 42 while issues with the 43 and 44 releases are ironed out.

**Comment by ndbroadbent** [comment] 2017-05-19 19:55
Confirming that I am also experiencing this crash whenever I tap on text.

**Comment by ndbroadbent** [comment] 2017-05-25 06:08
@rozele Hello, I would love to help with fixing this issue, because it is blocking me from upgrading to RN >= `0.43`. It's not happening on `0.42-stable`.

I will try to investigate, but was wondering if you might be able to remember some recent commits that could have caused it to start happening.

**Comment by matthargett** [comment] 2017-05-30 19:27
this is the same is #1131 . there's a better write-up of the bug there, so I'm closing this.

**Closed by matthargett** 2017-05-30 19:27 UTC
