### ISSUE TITLE
C# Native module finalizer is not called

### ISSUE THREAD

**Issue by tero-paananen** [microsoft/react-native-windows#7844] opened 2021-05-26 05:39 UTC
Native module destructor is not anymore called on react-native-windows 0.64.7 for example when refreshing bundle (Shift+Ctrl+D and reload bundle). 

How then handle case when we are for example listening events and listener is not removed in destructor and new listening is created in initialize?

I think that destructor is called on older react-native-windows 0.62.22 (for sure on 0.59.x)

```
class MyModule
{
  [ReactInitializer]
  public void Initialize(ReactContext context)
  {
      someClass.someEvent += eventReceived;
  }

  ~MyModule()
  {
    // NOTE: This destructor is not called on bundle refresh
    someClass.someEvent -= eventReceived;
  }

  private void eventReceived(object sender, SomeEventArgs e)
  {
    // NOTE: after bundle refresh this is called multiple times because destructor was not called
  }
}
```

## Environment
"react-native-windows": "0.64.7",
"react-native": "0.64.1",
"react": "^17.0.1",
React Native CLI: 5.0.1-alpha.2

## Expected Results
Native module's destructor is called when bundle is reloaded and new initialize is called (for new module instance?)

**Comment by tero-paananen** [comment] 2021-05-26 05:43
Can this be also problem is someone is using CodePush https://github.com/microsoft/react-native-code-push. I do not have tested it but maybe?

**Comment by tero-paananen** [comment] 2021-05-26 06:02
I tested your native module example https://github.com/microsoft/react-native-windows/tree/react-native-windows_v0.64.7/packages/microsoft-reactnative-sampleapps/windows/SampleLibraryCS in hello world and modules destructor was not called.

**Comment by NickGerleman** [comment] 2021-05-26 06:30
C# finalizers are normally called when the garbage collector runs, possibly at an indeterminate later time. So there is nothing to dictate when it is called.  Explicit release usually requires implementing something like IDisposable. See this page for details https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors

I think we had an issue to add explicit support for doing cleanup on instance unload for C# modules. Can try to find it...

**Comment by tero-paananen** [comment] 2021-05-26 06:47
You have had something like `INativeModule.OnReactInstanceDisposeAsync` on react-native-windows 0.59.x https://github.com/Microsoft/react-native-windows/issues/1873

**Comment by tero-paananen** [comment] 2021-05-26 06:48
> C# finalizers are normally called when the garbage collector runs, possibly at an indeterminate later time. So there is nothing to dictate when it is called. Explicit release usually requires implementing something like IDisposable. See this page for details https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors
> 
> I think we had an issue to add explicit support for doing cleanup on instance unload for C# modules. Can try to find it...

Is it that https://github.com/microsoft/react-native-windows/issues/6279

**Comment by NickGerleman** [comment] 2021-05-26 07:18
Yes, that is the one! I think the functionality went missing in the transition from the legacy C# implementation to the C++ based one with C# bindings. This is the second feedback has been given about the missing functionality, which is good confirmation it is needed.

**Comment by asklar** [comment] 2021-05-27 06:46
CC @dannyvv @vmoroz

**Comment by chrisglein** [comment] 2021-05-27 18:30
Duplicate of #6279

**Closed** 2021-05-27 18:30 UTC
Labels: Area: Native Modules, Needs: Triage :mag:, bug
