### ISSUE TITLE
Long press event (Press and Hold) in Touchables cancels the onPress (Regression from 0.60)

### ISSUE THREAD

**Issue by KAnder425** [microsoft/react-native-windows#5906] opened 2020-09-02 17:07 UTC
## Environment
1. `npx react-native --version`:
4.10.0
2. `npx react-native run-windows --info`:
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 4.15 GB / 15.92 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react-native: 0.62.2 => 0.62.2
    react-native-windows: 0.62.5 => 0.62.5
  Installed UWP SDKs:
    10.0.14393.0
    10.0.17134.0
    10.0.17763.0
    10.0.18362.0
3. `reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"`
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock
    AllowDevelopmentWithoutDevLicense    REG_DWORD    0x1
    AllowAllTrustedApps    REG_DWORD    0x1

- Target Platform Version(s): 10.0.18362.0
- Target Device(s): UWP
- Visual Studio Version: Visual Studio 2019

## Steps To Reproduce
1. Run the calculator sample in the Playground
2. Press and Hold on any of the numbers
3. Release
No number is entered.

## Expected Results
This should behave the same as in 0.60.
Honestly, the handling of mouse/touch events cross-platform is hard to keep track of, but in this scenario (desktop mouse event on a component with no onLongPress action) we should not be cancelling the onPress event.

**Comment by NickGerleman** [comment] 2020-09-02 17:52
At a quick glance, can't find any changes we made in RNW or the microsoft/react-native fork related to long press in 0.60 or 0.62 (in Touchable, TouchableHighlight, Pressability).

RNW 0.62+ seems to match Current React Native iOS behavior: (see https://imgur.com/a/f8HcnvT)

There was possibly an upstream behavior change made in 0.62 when Facebook migrated to Pressability, but it looks like RNW is correctly matching behavior of RN Core.

**Comment by NickGerleman** [comment] 2020-09-02 17:56
Realizing that vide doesn't show touches, but this is the event sequence we see for long press on iOS 
![image](https://user-images.githubusercontent.com/835219/92019155-04d96280-ed0b-11ea-90fd-82536696bba8.png)

**Comment by NickGerleman** [comment] 2020-09-02 18:07
We're seeing the same event sequence on 0.61, where we don't see an explicit press event, but the calculator example is still working. Investigating.
![image](https://user-images.githubusercontent.com/835219/92019947-41598e00-ed0c-11ea-8ac5-e7028573b670.png)

**Comment by NickGerleman** [comment] 2020-09-02 18:22
In 0.61, Touchable `_performSideEffectsForTransition` has logic to detect whether a longPressHandler is present, and will call onPress if onLongPress is not available. In 0.62, Pressability  `_performTransitionSideEffects` doesn't fallback, but has special logic to check this deprecated prop in PressabilityConfig, which isn't set by Touchables

![image](https://user-images.githubusercontent.com/835219/92021333-7666e000-ed0e-11ea-8238-3573797fb4c1.png)

@KAnder425 looks like confirmation this was a change made upstream by Facebook, and likely an intentional one.

**Comment by NickGerleman** [comment] 2020-09-02 18:36
FWIW I think this behavior is strange. I don't see anything similar on iOS for example. Might be worth discussing the behavior on https://github.com/react-native-community/discussions-and-proposals

**Comment by NickGerleman** [comment] 2020-09-02 19:23
Upstream issue: https://github.com/facebook/react-native/issues/29040

**Comment by chrisglein** [comment] 2020-09-10 18:38
Sounds like we're matching the behavior of core, and changing to do anything else would be a breaking change from the current behavior. The path forward seems like it should be to influence what core does. @kikisaints this seems like something reconcile alongside mouse/touch. I'm going to give this issue here to track that request. But if we don't change the core design then this is working as intended.

Workaround is to register for both onPress and onLongPress.

**Comment by NickGerleman** [comment] 2020-09-21 06:01
This was fixed upstream and will show up in RN 0.64. FYI @KAnder425 

Not sure if there is anything actionable left here. Going to close this issue, but please let me know if anything folks think still needs to be resolved.

**Closed by NickGerleman** 2020-09-21 06:01 UTC
Labels: Area: Mouse, Partner: Office, enhancement, needs PM design
