### ISSUE TITLE
Animated.timing with useNativeDriver: true causes the program to crash

### ISSUE THREAD

**Issue by LightningDev1** [microsoft/react-native-windows#9938] opened 2022-05-09 16:20 UTC
### Problem Description

I'm trying to make the background color of a button lighter when the user hovers over it. I used `Animated.timing` with the backgroundColor attribute and it works perfectly if `useNativeDriver` is false, but CPU usage goes up to 15%. If I try to enable `useNativeDriver`, which should be more efficient, the program crashes immediately when you hover over the button (i.e. when the animation should starts).

### Steps To Reproduce

Create a new project
Animate something using Animated.timing
Run the program

### Expected Results

The animation should execute normally, like if `useNativeDriver` would be false.

### CLI version

7.0.3

### Environment

```markdown
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 8.03 GB / 15.85 GB
  Binaries:
    Node: 16.13.2 - D:\Languages\Node\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.7.0 - D:\Languages\Node\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.1.32328.378 (Visual Studio Community 2022)
  Languages:
    Java: 18.0.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.0 => 0.68.0
    react-native-windows: ^0.68.3 => 0.68.3
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

```js
import React from 'react';
import {StyleSheet} from 'react-native';
import {Animated, Easing} from 'react-native-windows';

const AnimatedTimingCrashExample = props => {
  const animation = new Animated.Value(0);

  const animationStyle = {
    backgroundColor: animation.interpolate({
      inputRange: [0, 1],
      outputRange:['#264066', '#1E4878'],
    }),
  };

  Animated.timing(animation, {
    toValue: 1,
    duration: 300,
    easing: Easing.linear,
    useNativeDriver: true, // causes crash
  }).start();

  return <Animated.View style={[styles.animatedView, animationStyle]} />;
};

const styles = StyleSheet.create({
  animatedView: {
    backgroundColor: '#264066',
    padding: 100,
  },
});

export {AnimatedTimingCrashExample};

```

**Comment by jonthysell** [comment] 2022-05-09 18:14
@TatianaKapos Can you take a look at this and see what's going wrong?

**Comment by rozele** [comment] 2022-06-11 13:29
Perhaps the issue is that color animations are not yet supported in react-native-windows.

**Comment by chiaramooney** [comment] 2022-08-16 20:36
@TatianaKapos Do we have an update here, or should this be moved to 71?

**Comment by TatianaKapos** [comment] 2022-08-18 22:28
If we don't support color animations yet, it makes sense to crash if useNativeDriver is true. Closing as dupe.

**Closed by TatianaKapos** 2022-08-18 22:28 UTC
Labels: bug, Area: Animation
