### ISSUE TITLE
Re-enable DesktopIntegrationTests (were intermittently crashing in CI)

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5059] opened 2020-05-29 19:31 UTC
```
##[error]The active test run was aborted. Reason: Test host process crashed
Results File: d:\a\_temp\TestResults\VssAdministrator_fv-az123_2020-05-29_18_00_26.trx
##[error]The active Test Run was aborted because the host process exited unexpectedly while executing following test(s):
##[error]RNTesterIntegrationTests::IntegrationTestHarness
Attachments:
  d:\a\_temp\TestResults\878312ba-0c23-48d3-98ac-bb2611127f62\Sequence_bb6c3837152742bf9250b43b8e56ab2c.xml
##[error]Test Run Aborted.
```

**Comment by JunielKatarn** [comment] 2020-05-29 20:02
I'll investigate, but this only started happening recently (probably after the VM image upgrade)?
If this persists, we can separate the test runs and have the test failing frequently run into a task that can be ignored if it fails.

After several attempts over the past two days, I have not been able to reproduce this failure locally.

**Comment by chrisglein** [comment] 2020-06-01 18:28
In the meantime @JunielKatarn can we disable the tests until we get this sorted out?

**Comment by JunielKatarn** [comment] 2020-06-02 01:21
@chrisglein we can, but we should not just disregard them.
Many of those are also ran by React Native (iOS, Android).

I have a plan to create a CI step that allows running intermittently failing, but not critical tests, without failing the whole job but still reporting results for follow-up.

**Comment by JunielKatarn** [comment] 2020-06-03 05:21
Mitigated by #5109.

There are only two specific tests failing since the recent CI VM Image update:
- `RNTesterIntegrationTests::AsyncStorage`
- `RNTesterIntegrationTests::IntegrationTestHarness`

They only fail in CI runs, apparently never in local dev machines.
Will use this issue for follow up so the tests get re-enabled.

**Comment by NickGerleman** [comment] 2020-11-06 09:20
There's been new issues since this one. Closing this.

**Closed by NickGerleman** 2020-11-06 09:20 UTC
Labels: Area: Tests, bug
