### ISSUE TITLE
borderXWidth & borderXColor need to be implemented!

### ISSUE THREAD

**Issue by Omar-Belghaouti** [microsoft/react-native-windows#7518] opened 2021-04-02 18:47 UTC
For some reason ```borderRightWidth``` and ```borderRightColor``` (and all other sides) are not working on windows. It would be helpful for having more flexibility for styling the app.

**Comment by chrisglein** [comment] 2021-04-05 18:25
Yep, not yet implemented yet. You can track on the issue below:

Duplicate of #3077

**Closed by chrisglein** 2021-04-05 18:25 UTC
Labels: Area: Borders and Brushes, Needs: Triage :mag:, enhancement
