### ISSUE TITLE
Problem with borderRightWidth

### ISSUE THREAD

**Issue by ndbroadbent** [Microsoft/react-native-windows#1105] opened 2017-05-08 12:16 UTC
Hello, borders seem to be half-working for me. "top" and "bottom" widths seem to work ok, but "left" and "right" are not working.

For example, I have some little grid icons that I'm building with plain views and borders, using this style:

```
    borderColor: borderColor,
    borderRightWidth: 1,
    borderBottomWidth: 1,
```

This produces the following on iOS:

<img width="39" alt="grid-ios" src="https://cloud.githubusercontent.com/assets/139536/25803607/df49cfc8-3421-11e7-9b33-236bc935a5cf.PNG">

But on Windows it looks like this:

<img width="42" alt="grid-windows" src="https://cloud.githubusercontent.com/assets/139536/25803612/e7269e60-3421-11e7-9ca3-060c91072653.PNG">

As a workaround, I'm just going to set the `borderWidth` to `0.5` on Windows, which looks a little different (but kind of cool):

```
    ...(Platform.OS === 'windows' ? {
      borderWidth: 0.5,
    } : {
      borderRightWidth: 1,
      borderBottomWidth: 1,
    }),
```

<img width="38" alt="grid-windows-workaround" src="https://cloud.githubusercontent.com/assets/139536/25803813/e5e02c0a-3422-11e7-956c-7b59bd4fa3d1.PNG">

**Comment by matthargett** [comment] 2017-05-17 22:17
This may be fixed by #1098. Can you check out master and see if the problem reproduces in Playground?

**Comment by ndbroadbent** [comment] 2017-05-17 22:21
Oh yeah, that definitely looks like it. I'll test it out

**Comment by matthargett** [comment] 2017-05-30 19:40
@ndbroadbent verified fixed? can this be closed?

**Comment by sayar** [comment] 2017-07-17 20:01
@ndbroadbent It seems as though your issue has been resolved. If you don’t mind, I will close this issue in 1 day unless I get an update from you.

**Comment by rozele** [comment] 2018-07-23 20:50
Closing due to inactivity.

**Closed by rozele** 2018-07-23 20:50 UTC
Labels: needs-update-or-close
