### ISSUE TITLE
Header buttons in Stack Navigators broken from 0.66.18-0.67.0

### ISSUE THREAD

**Issue by AdaData** [microsoft/react-native-windows#9977] opened 2022-05-18 17:46 UTC
### Problem Description

I initially wrote [this issue on react-navigation](https://github.com/react-navigation/react-navigation/issues/10553) but after further testing it looks like specifically going from react-native-windows 0.66.18 to 0.67.0 reproduces the issue with no changes to your react-navigation version.

The issue description, just to save time following a link, is: If you start on the root screen of a stack navigator, navigate to a different screen, then hit the back button (or navigate to the start by any other means), any header buttons on the root screen will become unclickable. Other screens seem unaffected.

### Steps To Reproduce

1. Upgrade to react-native-windows 0.67.0
2. Have a stack navigator with at least 2 screens and a button in the header
3. From screen 1, navigate to screen 2, then navigate back to screen 1
4. Click the button in the header - it won't work

### Expected Results

Header button always works

### CLI version

5.0.1

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (2) x64 Intel(R) Xeon(R) Gold 6226 CPU @ 2.70GHz
    Memory: 899.62 MB / 6.00 GB
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.16299.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.10.31410.357 (Visual Studio Professional 2019)
  Languages:
    Java: 17.0.3.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.2 => 0.67.2
    react-native-windows: 0.67.0 => 0.67.0
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Release

### Snack, code example, screenshot, or link to a repository

[Minimal repro that is also my example code:](https://snack.expo.dev/_dbMNoLpW) - Note that you can't see the issue happen here, because you can't select windows! From a default react-native-windows installation, you also need to run

yarn add @react-navigation/native react-native-screens react-native-safe-area-context @react-navigation/stack react-native-elements react-native-vector-icons

```
import { NavigationContainer } from "@react-navigation/native";
import { createStackNavigator, StackScreenProps } from "@react-navigation/stack";
import React, { useState, useCallback } from "react";
import { Alert, Modal, StyleSheet, Text, Pressable, View, LayoutAnimation } from "react-native";
import { Button } from "react-native-elements";
const Stack = createStackNavigator();

export const Screen1 = ({
  navigation,
  route,
}) => {
  return <View style={styles.screens}><Button style={styles.navButtons} title="Click me to go to screen 2!" onPress={() => navigation.navigate('Screen2')} /></View>;
}

export const Screen2 = ({
  navigation,
  route,
}) => {
  return <View style={styles.screens}><Button style={styles.navButtons} title="Click me to go to screen 1!" onPress={() => navigation.navigate('Screen1')} />
  <Button style={styles.navButtons} title="Click me to go to screen 3!" onPress={() => navigation.navigate('Screen3')} /></View>;
};

export const Screen3 = ({
  navigation,
  route,
}) => {
  return <View style={styles.screens}><Button style={styles.navButtons} title="Click me to go to screen 1!" onPress={() => navigation.navigate('Screen1')} /><Button style={styles.navButtons} title="Click me to go to screen 2!" onPress={() => navigation.navigate('Screen2')} /></View>;
};

const App = () => {
  const headerButton = <Button title={"Do I work?"} style={styles.doIWorkButton} onPress={() => alert("I do!") } />;
  return (
    <NavigationContainer>
      <Stack.Navigator screenOptions={{ header: () => headerButton, headerMode: "screen", headerStyle: {height: 500}}} detachInactiveScreens={false}>
        <Stack.Screen name="Screen1" component={Screen1} />
        <Stack.Screen name="Screen2" component={Screen2} />
        <Stack.Screen name="Screen3" component={Screen3} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

const styles = StyleSheet.create({
  screens: { flex: 1, alignItems: 'center' },
  navButtons: { height: 100, width: 250, color: 'white' },
  doIWorkButton: {}
});

export default App;
```

**Comment by AdaData** [comment] 2022-05-20 17:36
For what it's worth, I tried on 0.68 and was still hitting the issue, haven't tried 0.69 though.

**Comment by ryfow** [comment] 2022-05-23 20:09
@TatianaKapos  I stuck a reproducing rnw app at https://github.com/ryfow/NavProb

I couldn't get things completely running with 0.69 but I'm not familiar with running pre-release versions so it was probably my mistake.

**Comment by m-cartmell** [comment] 2022-05-25 19:48
@chrisglein I can confirm the issue is resolved in 0.69.0-preview.1, but persists in 0.68.3. Can anyone confirm when 0.69 will be released?

**Comment by gillpeacegood** [comment] 2022-06-01 10:17
If anyone knows what change fixed it and whether it can be backported to 0.67 we would love to know!

**Comment by jonthysell** [comment] 2022-06-09 18:38
Putting on 0.70 - @chiaramooney , if you can identify a set of changes that fixed this in 0.69 then we should probably backport it.

**Comment by TatianaKapos** [comment] 2022-07-13 22:35
I believe the PR that fixes this issue is 
https://github.com/microsoft/react-native-windows/pull/9898 but just waiting on some confirmation! :)

**Comment by TatianaKapos** [comment] 2022-07-22 20:14
Backported into .68 and .67!

**Closed by TatianaKapos** 2022-07-22 20:14 UTC
Labels: bug, Extensions, Partner: AppConsult, Scenario: Upgrade

**Comment by cjhines** [comment] 2022-08-16 15:23
For some reason this is still happening to me in 0.68.9

**Comment by tero-paananen** [comment] 2022-09-01 10:57
Issue exists still on 

```
"react-native": "0.68.2",
"react-native-windows": "0.68.14",
```

after navigating into some screen and back to first screen Header button does not get tap anymore

**Comment by juhasuni** [comment] 2022-09-01 11:08
Based on our tests setting `pointerEvents` to "none" also leaves them to "none" even if the prop changes later on.

Here's the patch we had to apply:

```
diff --git a/node_modules/@react-navigation/stack/src/views/Header/HeaderContainer.tsx b/node_modules/@react-navigation/stack/src/views/Header/HeaderContainer.tsx
index cbfd6b5..a649bd7 100644
--- a/node_modules/@react-navigation/stack/src/views/Header/HeaderContainer.tsx
+++ b/node_modules/@react-navigation/stack/src/views/Header/HeaderContainer.tsx
@@ -153,11 +153,7 @@ export default function HeaderContainer({
                       }
                     : undefined
                 }
-                pointerEvents={isFocused ? 'box-none' : 'none'}
```

**Comment by chrisglein** [comment] 2022-09-01 18:17
There may be undesired side effects of this issue: https://github.com/microsoft/react-native-windows/issues/10484
Worth checking in after that is addressed.

Would you mind opening a fresh issue for what you're seeing here? It sounds like there may be differences from the issue back in May and it'd be good to capture all the state.

**Comment by juhasuni** [comment] 2022-09-02 13:58
@chrisglein, just filed an issue #10493
