### ISSUE TITLE
Unsupported top level event type "topScrollBeginMomentum" / "topScrollEndMomentum" dispatched

### ISSUE THREAD

**Issue by jbcullis** [microsoft/react-native-windows#12549] opened 2023-12-25 16:56 UTC
### Problem Description

We are catching an exception from FlatList on RNW.

Unsupported top level event type "topScrollBeginMomentum" dispatched
Unsupported top level event type "topScrollEndMomentum" dispatched

Occurs when changing scroll direction.

Present in both debug and release.

### Steps To Reproduce

Create a new project with a flat list, fill list to extend the height.

Override error handler:
global.ErrorUtils.setGlobalHandler((ex, isFatal) => {});

Scroll up and down to trigger warning on change of direction.

### Expected Results

event should be handled.

### CLI version

11.3.10

### Environment

```markdown
System:
  OS: Windows 11 10.0.22621
  CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13950HX
  Memory: 45.28 GB / 63.65 GB
Binaries:
  Node:
    version: 18.17.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.6.7
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.4.34302.79 (Visual Studio Professional 2022)
Languages:
  Java:
    version: 11.0.18
    path: C:\Program Files\Microsoft\jdk-11.0.18.10-hotspot\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-windows:
    installed: 0.72.20
    wanted: 0.72.20
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by TatianaKapos** [comment] 2023-12-28 23:56
Duplicate of https://github.com/microsoft/react-native-windows/issues/12272. Made a PR to backport to 0.73: https://github.com/microsoft/react-native-windows/pull/12551, do we also want to backport this to 0.72?

**Comment by chrisglein** [comment] 2024-01-04 19:08
The mitigation for anyone right now is to move to 0.73... but this obnoxious enough to be worth backporting.

**Comment by jbcullis** [comment] 2024-01-04 19:13
@chrisglein I don't think so, we have already updated our environment and the only reason we knew it was happening cause it was getting wrapped up in logging as an uncaught exception.

Anyone not doing detailed logging won't even know it's happening.

**Closed** 2024-01-24 00:22 UTC
Labels: bug, Area: ScrollView, Backport: Requested, Recommend: Backlog
