### ISSUE TITLE
Initial paint for transform of position absolute going to top left

### ISSUE THREAD

**Issue by Iyzo** [Microsoft/react-native-windows#1182] opened 2017-07-06 04:23 UTC
I have the weirdet behavior here. I expect transform to be from origin 50%,50%. However on initial paint it is 0px,0px. If click the TouchableHighlight it then goes to center as expected. So the problem is on initial paint.

Here is my code, I took the boiler plate, and created a component called GridCell which is like this:

```
import React, { Component } from 'react';
import { TouchableHighlight, Text, View } from 'react-native';
import styles from './style.css'

class GridCell extends Component {
    handlePress = () => {
        // setTimeout(() => this.setState(({active}) => ({ active:!active })), 1000);
    }

    render() {
        return (
            <TouchableHighlight style={[styles.gridCell]} onPress={this.handlePress}>
                <View>
                    <Text style={styles.text}>
                        blah
                    </Text>
                </View>
            </TouchableHighlight>
        )
    }
}

export default GridCell
```

styles.css.js is this:

```
import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
    gridCell :{
        left: 0,
        top: 0,
        backgroundColor: 'lightsteelblue' ,
        alignItems: 'center' ,
        justifyContent: 'center' ,
        position: 'absolute',
        width: '100%',
        height: '100%',
        transform: [
            { scale: 0.2 }
        ]
    },
    text :{
        fontSize: 100 ,
    }
});

export default styles
```

On initial paint we see the TouchableHighlight in top right: http://i.imgur.com/zPU24DX.png
After pressing TouchableHighlight we see it centers, and displays properly: http://i.imgur.com/aiYtdcB.png

**Comment by adi1133** [comment] 2017-07-10 14:21
I am facing the same issue.

**Comment by adi1133** [comment] 2017-07-10 15:39
In React Native the default origin of transforms is the center of the view, in UWP the default origin of transforms is the top left corner if the view. To bridge the two an offset needs to be applied.

The bug happens in  [BaseViewManager L184](https://github.com/Microsoft/react-native-windows/blob/0126c853a4fee6ec276094c2f15212bb36c76744/ReactWindows/ReactNative/UIManager/BaseViewManager.cs#L184) , the offset is not applied on the initial render (because the view size is unknown) but is applied on all future renders.

I think this affects both views with `position:absolute` and `position: relative` and probably breaks all transforms for exception of translates.

Here is a complete snippet to reproduce the issue.

```
import React from 'react';
import {
  AppRegistry,
  View,
} from 'react-native';

/*
Expected: The black line should always cross the red square !
Actual result: The black line only crosses the red square after 5 seconds pass
 */
class ReactUWP extends React.Component {
  componentWillMount() {
    setTimeout(() => this.setState({ timeout: true }), 5000);
  }
  render() {
    return (
      <View style={{ flex: 1, backgroundColor: 'pink', justifyContent: 'center', alignItems: 'center' }}>
        <View style={{
          width: 10,
          height: 100,
          backgroundColor: 'black',
          transform: [
            { rotate: (this.state && this.state.timeout) ? '46deg' : '45deg' },
          ],
        }}
        />
        <View style={{ width: 10, height: 10, backgroundColor: 'red', position: 'absolute' }} />
      </View>
    );
  }
}

AppRegistry.registerComponent('ReactUWP', () => ReactUWP);
```

**Comment by rozele** [comment] 2017-07-17 15:51
@adi1133 and @Iyzo - can you check if the PR in #1202 fixes the issue for you? @adi1133 is correct above, the default origin for the transform is the top left corner, so we applied the hack to try and make the transforms compatible with react-native. There were cases where the transform is applied before the dimensions of the view are known, which breaks the hack.

**Comment by rozele** [comment] 2017-07-17 16:40
Please re-open if the merged PR does not resolve the issue.

**Closed** 2017-07-17 16:40 UTC

**Comment by alexcoady** [comment] 2017-10-24 09:17
@rozele I'm still getting this issue using WPF, exactly as the OP explained. I'm running:
```
"react": "16.0.0-alpha.12",
"react-native": "0.48.3",
"react-native-windows": "^0.48.0-rc.4"
```
As soon as I interact with (or update the transformation via an animation, etc) the component is rendered correctly.

**Comment by rozele** [comment] 2017-11-01 16:21
cc @kevinvangelder @pre10der89 if you get a chance, can you apply the same patch to WPF that we applied to UWP?
