### ISSUE TITLE
TextInput onChangeText

### ISSUE THREAD

**Issue by sm2017** [Microsoft/react-native-windows#1370] opened 2017-09-13 05:59 UTC
### Environment

1. `react-native -v`:

> react-native-cli: 2.0.1
> react-native: 0.47.2

2. `npm ls rnpm-plugin-windows`:

> rnpm-plugin-windows@0.2.7

3. `npm ls react-native-windows`:

> react-native-windows@0.47.0-rc.5

4. `node -v`:

> v8.1.3

5. `npm -v`:

> 5.0.3

6. `yarn --version`:

> 0.27.5

Then, specify:

- Target Platform: UWP

- Target Platform Version(s):10.0.10586

- Target Device(s):Desktop

- Development Operating System:Windows 10

- Visual Studio Version:2015 

### Steps to Reproduce

Run the following code
```js
<TextInput style={{width: 350, height: 50}} onChangeText={(text) => {console.log('TextInput onChange Run:', text)}} />
```

### Expected Behavior

`onChangeText` must run when text is changed not on mounting component

### Actual Behavior

If you run application , and never change the text , `onChangeText` is runned when component mounted , for Android and iOS it is okay

![image](https://user-images.githubusercontent.com/19644997/30361848-6be8fa52-986e-11e7-878e-8a8184f9c41e.png)

### Reproducible Demo

N/A

**Comment by rozele** [comment] 2017-09-25 20:05
@sm2017 closing as a dupe of https://github.com/Microsoft/react-native-windows/issues/907, but will take a look this week.

**Closed by rozele** 2017-09-25 20:05 UTC
Labels: duplicate

**Comment by sm2017** [comment] 2017-10-07 06:52
@rozele Just for reminding

**Comment by victorileaf** [comment] 2017-10-31 07:33
@rozele any updates please?

**Comment by victorileaf** [comment] 2017-11-13 12:05
@rozele @kevinvangelder can we expect a bug fix soon?

**Comment by kevinvangelder** [comment] 2017-11-13 19:49
@victorileaf This isn't currently a priority in the project I'm working on, but I may be able to see if I can reproduce the issue if I get any free time.

**Comment by victorileaf** [comment] 2017-12-05 06:27
@rozele is this commit merged to the master?
i'm still able to reproduce this issue in "react-native-windows": "^0.50.0-rc.2"
