### ISSUE TITLE
react-native run-windows command is failing at build step

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#3263] opened 2019-09-26 22:54 UTC
Per @marlenecota  this has started occurring with msbuild version update to 16.3.0.46305. This is causing the CLI to not work anymore. 

Workaround is to build the project in VS instead of msbuild, run `yarn start` and run the project from VS.

**Comment by licanhua** [comment] 2019-09-26 23:00
The error is like this:
F:\repo\react-native-windows\node_modules\.folly\folly-2019.08.12.00\folly\portability\Builtins.h(44,25): error C2373: '__builtin_clz': redefinition; different type modifiers (compiling source file CustomViewManager.cpp) [F:\repo\react-native-windows\packages\react-native-windows-extended\windows\react-native-windows-extended.vcxproj]

**Comment by marlenecota** [comment] 2019-09-30 20:47
Fixed by #3279

**Closed by marlenecota** 2019-09-30 20:47 UTC
Labels: Area: CLI, bug, must-have, vnext

**Comment by Joshua-David** [comment] 2019-11-18 18:40
Has this actually been resolved? I get the msbuild error when running `react-native run-windows`

My react native windows version is: ^0.60.0-vnext.71

**Comment by acoates-ms** [comment] 2019-11-18 20:11
Can you try running `react-native run-windows --logging` to see if that provides more information on what is failing?

**Comment by Joshua-David** [comment] 2019-11-19 11:53
I get:
 ```
i Verbose: ON
 √ Found NuGet Binary
Searching for MSBuild version 16.0
Searching for MSBuild version 15.0
Searching for MSBuild version 14.0
Searching for MSBuild version 12.0
Searching for MSBuild version 4.0
 × Failed to restore the NuGet packages: Error: MSBuild tools not found. Make sure all required components have been installed (e.g. v141 support)
```

**Comment by Joshua-David** [comment] 2019-11-19 15:12
Note: I am able to get this to run via the visual studio instructions (after degrading my version of node to 10.16.3), but I'd prefer to run via the single command

**Comment by AddictArts** [comment] 2019-11-20 21:58
@Joshua-David seems like an Windows SDK and path issue to find a version of MSBuild and tools. However, you may still run into what I did, the below permission issue?
Cheers
```
 √ Starting the React-Native Server
 √ Removing old version of the app
 Set-ItemProperty : Requested registry access is not allowed.
At C:\box\react\native\rnwinVnextConsuming\node_modules\react-native-windows\local-cli\runWindows\utils\WindowsStoreAppUtils.ps1:91 char:5
+     Set-ItemProperty -Path $RegistryKeyPath -Name AllowDevelopmentWit ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...\AppModelUnlock:String) [Set-ItemProperty], SecurityException
    + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.SetItemPropertyCommand

√ Enabling Developer Mode
 Found package: C:\box\react\native\rnwinVnextConsuming\windows\AppPackages\rnwinVnextConsuming\rnwinVnextConsuming_1.0.0.0_Win32_Debug_Test\rnwinVnextConsuming_1.0.0.0_Win32_Debug.appx
Found certificate: C:\box\react\native\rnwinVnextConsuming\windows\AppPackages\rnwinVnextConsuming\rnwinVnextConsuming_1.0.0.0_Win32_Debug_Test\rnwinVnextConsuming_1.0.0.0_Win32_Debug.cer

Before installing this app, you need to do the following:
        - Install the signing certificate
You must provide administrator credentials to proceed.  Please run this script without the -Force parameter or from an elevated PowerShell window.
√ Installing new version of the app
 × Failed to deploy: Fail to check the installed app, maybe developer mode is off on Windows
```

**Comment by AddictArts** [comment] 2019-11-20 23:04
After installing the cert manually (may not be needed) and running from an admin PowerShell / CMD it worked and viola, so this does not appear to be an issue now.

**Comment by adnaanbheda** [comment] 2019-12-07 09:57
√ Found NuGet Binary
 × Failed to restore the NuGet packages: Error: MSBuild tools not found. Make sure all required components have been installed (e.g. v141 support)


Repaired the whole Build tools suite and I still get this error.

**Comment by jjgh** [comment] 2020-02-20 09:52
Same error here (Windows 10, Node v13.9.0):
```
PS D:\dev\nodejs\my-app> react-native run-windows
 √ Downloading NuGet Binary
 √ Found NuGet Binary
 × Failed to restore the NuGet packages: Error: MSBuild tools not found. Make sure all required components have been installed (e.g. v141 support)
```

**Comment by uhteddy** [comment] 2020-03-01 20:17
Bumping this as I am having the same issue.

**Comment by VPelt** [comment] 2020-03-04 14:39
For me the problem was the vswhere query being executed. In particular this one
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -version 2.0 -property installationPath -products * -requires Microsoft.VisualStudio.ComponentGroup.UWP.VC

returned no value

After i instealled universal windows platform development INCLUDING the c++ build tools optional dependency (based on the documentation found here https://devblogs.microsoft.com/cppblog/finding-the-visual-c-compiler-tools-in-visual-studio-2017/ )
It worked

**Comment by festim-deari** [comment] 2020-03-06 08:31
I have the same issue. 
I tried it with both the stable 0.60.0 and the beta version 0.61.5. 
Got both times the same error:
 × Failed to restore the NuGet packages: Error: MSBuild tools not found. Make sure all required components have been installed (e.g. v141 support)

**Comment by Kiyozz** [comment] 2020-03-06 11:09
Same

- SDK Installed
- Node 10.15.1
- yarn 1.22.0

1. `react-native init <Project> --version ^0.60.0`
2. `cd <Project>`
3. `yarn add rnpm-plugin-windows`
4. `react-native windows`
5. `react-native run-windows`

```
 i Build configuration: Debug
 i Build platform: x86
Running MSBuild with args /clp:NoSummary;NoItemAndPropertyList;Verbosity=normal /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never /p:PlatformToolset=v141 /p:VisualStudioVersion=15.0 /bl
 × Building Solution: Utilisation�:          100,0    Utilisation moyenne�: 100,0...
 × Build failed with message undefined. Check your build configuration.
```

**Comment by WQvist** [comment] 2020-03-14 18:41
Same problem here.

**Comment by Unforgiven-wanda** [comment] 2020-03-15 10:06
Same issue here, why is this closed when so many people report the same problem?

**Comment by smilealdway** [comment] 2020-03-18 05:27
> Same
> 
>     * SDK Installed
> 
>     * Node 10.15.1
> 
>     * yarn 1.22.0
> 
> 
>     1. `react-native init <Project> --version ^0.60.0`
> 
>     2. `cd <Project>`
> 
>     3. `yarn add rnpm-plugin-windows`
> 
>     4. `react-native windows`
> 
>     5. `react-native run-windows`
> 
> 
> ```
>  i Build configuration: Debug
>  i Build platform: x86
> Running MSBuild with args /clp:NoSummary;NoItemAndPropertyList;Verbosity=normal /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never /p:PlatformToolset=v141 /p:VisualStudioVersion=15.0 /bl
>  × Building Solution: Utilisation�:          100,0    Utilisation moyenne�: 100,0...
>  × Build failed with message undefined. Check your build configuration.
> ```

I am facing exact same issue.

**Comment by handlerda** [comment] 2020-03-18 17:37
Same issue as everyone else.

`$ react-native run-windows --logging
 i Verbose: ON
 √ Found NuGet Binary
Searching for MSBuild version 16.0
Searching for MSBuild version 15.0
Searching for MSBuild version 14.0
Searching for MSBuild version 12.0
Searching for MSBuild version 4.0
 × Failed to restore the NuGet packages: Error: MSBuild tools not found. Make sure all required components have been installed (e.g. v141 `

**Comment by alariej** [comment] 2020-03-22 11:16
Same here, with both stable and beta. I've added MSBuild to the path in the environment variables, but it doesn't solve the problem. I've also installed the v141 tools via VS2019, no luck there as well.

```
 √ Found NuGet Binary
 × Failed to restore the NuGet packages: Error: MSBuild tools not found. Make sure all required components have been installed (e.g. v141 support)
```

**Comment by alariej** [comment] 2020-03-22 17:17
OK, solved for me. I had forgotten this point in the system requirements:

`Enable the optional C++ (v141) Universal Windows Platform tools`

This option is not available in the individual components of the Visual Studio Installer, but sort of hidden on the right side under Installation details -> Universal Windows Platform development -> Optional.

**Comment by kotpal** [comment] 2020-04-16 07:43
Can someone with moderate rights just clean up irrelevant information? I followed each and every step - including the one above that says it solved for them - but no go so far. 

Still running into the same problem:

> √ Found NuGet Binary
> Searching for MSBuild version 16.0
> Searching for MSBuild version 15.0
> Searching for MSBuild version 14.0
> Searching for MSBuild version 12.0
> Searching for MSBuild version 4.0
>  × Failed to restore the NuGet packages: Error: MSBuild tools not found. Make sure all required components have been installed (e.g. v141 support)

What is the magic sauce to get "npx react-native run-windows" to work? How can we expect people to keep troubleshooting - when all they want is to just run-windows and get on with their lives?

**Comment by asklar** [comment] 2020-04-16 10:26
> Can someone with moderate rights just clean up irrelevant information? I followed each and every step - including the one above that says it solved for them - but no go so far.
> 
> Still running into the same problem:
> 
> > √ Found NuGet Binary
> > Searching for MSBuild version 16.0
> > Searching for MSBuild version 15.0
> > Searching for MSBuild version 14.0
> > Searching for MSBuild version 12.0
> > Searching for MSBuild version 4.0
> > × Failed to restore the NuGet packages: Error: MSBuild tools not found. Make sure all required components have been installed (e.g. v141 support)
> 
> What is the magic sauce to get "npx react-native run-windows" to work? How can we expect people to keep troubleshooting - when all they want is to just run-windows and get on with their lives?

@kotpal If you're seeing the prompt that we searched for version 16, 15, 14, etc. then you're running an older version of react-native, which won't have the fixes that we're talking about. My guess is that because you're running this with npx, you'll only pick up whatever latest official version of the package is made public to npmjs. So until we cut a new version and post it on npm, you won't see these fixes. If you need these fixes then the only way is to clone the RNW repo locally and use yarn/node instead of npx in the command line, since npx will just download the latest official version from npm.

**Comment by uhteddy** [comment] 2020-04-22 14:01
I was able to find a solution to the following error:
```× Failed to restore the NuGet packages: Error: MSBuild tools not found. Make sure all required components have been installed (e.g. v141 support)```

I used @alariej 's solution but because it took me a while to find it I decided to do a step by step solution with pictures.

# Open Visual Studio Installer and press Modify on your studio version
![image](https://user-images.githubusercontent.com/54421295/79989650-1c136400-847e-11ea-9096-0dc9e4ad10f4.png)

# First make sure that `Univeral Windows Platform development` is enabled (of course)
![image](https://user-images.githubusercontent.com/54421295/79990572-3732a380-847f-11ea-846f-2db4b6976edb.png)

# Close Individual Components and open up the `Universal Windows Platform development` panel which is highlighted below
![image](https://user-images.githubusercontent.com/54421295/79990764-6fd27d00-847f-11ea-8f32-6878a1247b15.png)

# Enable the two highlighted options and press modify to update
![image](https://user-images.githubusercontent.com/54421295/79990926-a60ffc80-847f-11ea-8e71-895f9981bfb0.png)

# Once complete
Once you complete this process you could be able to run
```
npx react-native run-windows
```

Hope this helped.

**Comment by liudonghua123** [comment] 2020-04-22 14:19
@uhteddy Thanks for the detail instructions. It works for me. Recommend update the docs about this.

**Comment by linkstrifer** [comment] 2020-05-08 02:24
> I was able to find a solution to the following error:
> `× Failed to restore the NuGet packages: Error: MSBuild tools not found. Make sure all required components have been installed (e.g. v141 support)`
> 
> I used @alariej 's solution but because it took me a while to find it I decided to do a step by step solution with pictures.
> 
> # Open Visual Studio Installer and press Modify on your studio version
> ![image](https://user-images.githubusercontent.com/54421295/79989650-1c136400-847e-11ea-9096-0dc9e4ad10f4.png)
> 
> # First make sure that `Univeral Windows Platform development` is enabled (of course)
> ![image](https://user-images.githubusercontent.com/54421295/79990572-3732a380-847f-11ea-846f-2db4b6976edb.png)
> 
> # Close Individual Components and open up the `Universal Windows Platform development` panel which is highlighted below
> ![image](https://user-images.githubusercontent.com/54421295/79990764-6fd27d00-847f-11ea-8f32-6878a1247b15.png)
> 
> # Enable the two highlighted options and press modify to update
> ![image](https://user-images.githubusercontent.com/54421295/79990926-a60ffc80-847f-11ea-8e71-895f9981bfb0.png)
> 
> # Once complete
> Once you complete this process you could be able to run
> 
> ```
> npx react-native run-windows
> ```
> 
> Hope this helped.

This worked for me, awesome, this should be in the docs...

**Comment by magnushammar** [comment] 2020-05-13 17:26
THANK YOU @uhteddy .. I was on the Individual components tab and for some reason Universal v141 tools are not visible there, so I thought that... OK, old instructions... v142 it is...

![image](https://user-images.githubusercontent.com/4369221/81844538-85ebce80-954f-11ea-9e9b-0a6573600b79.png)

**Comment by widersky** [comment] 2020-05-21 05:48
Same issue here on 0.62.0 preview 7. I've installed C++ platform tools (v141 and v142) and nothing. Visual studio 2019 on board.

Command line output:

```
npx react-native run-windows --logging
 i Verbose: ON
 √ Found NuGet Binary
Using Nuget: C:\Users\adria\AppData\Local\Temp\nuget.4.9.2.exe
Searching for MSBuild version 16.0
Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
Found vswhere.
VS path:
Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
Found vswhere.
VS version:
Looking for MSBuilt at: MSBuild\Current\Bin\MSBuild.exe
 × Failed to restore the NuGet packages: Error: MSBuild tools not found. Make sure all required components have been installed
```

**Comment by Kiyozz** [comment] 2020-05-21 06:36
I make it work with linkstrifer’s solution, but before, I uninstall everything from Visual Studio Installer

**Comment by asklar** [comment] 2020-05-21 08:28
FYI if you're using what's in master (or once we ship 0.62 :) ) you'll be able to run the script in `\vnext\scripts\rnw-dependencies.ps1` to check or install dependencies

**Comment by constructor-s** [comment] 2020-05-24 17:44
> 
> 
> Same issue here on 0.62.0 preview 7. I've installed C++ platform tools (v141 and v142) and nothing. Visual studio 2019 on board.
> 
> Command line output:
> 
> ```
> npx react-native run-windows --logging
>  i Verbose: ON
>  √ Found NuGet Binary
> Using Nuget: C:\Users\adria\AppData\Local\Temp\nuget.4.9.2.exe
> Searching for MSBuild version 16.0
> Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
> Found vswhere.
> VS path:
> Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
> Found vswhere.
> VS version:
> Looking for MSBuilt at: MSBuild\Current\Bin\MSBuild.exe
>  × Failed to restore the NuGet packages: Error: MSBuild tools not found. Make sure all required components have been installed
> ```

Same/similar issue. With `0.62.0-preview.8` I am having #4954 which leads to this current issue. 

```json
  "dependencies": {
    "react": "16.11.0",
    "react-native": "^0.62.0-0",
    "react-native-windows": "^0.62.0-preview.8"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/cli": "^4.9.0",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.11.0"
  }
```

```
>npx react-native run-windows --verbose --logging --info
 i Verbose: ON

  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 9.29 GB / 15.74 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @react-native-community/cli: ^4.9.0 => 4.9.0
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.0-0 => 0.62.2
    react-native-windows: ^0.62.0-preview.8 => 0.62.0-preview.8
  Installed UWP SDKs:
    10.0.18362.0
```

```
>npx react-native run-windows
 √ Found NuGet Binary
 √ Found MSBuild v16.0 at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin (16.6.30114.105)
⠋ Restoring NuGet packages C:\Users\USERNAME\AppData\Local\Temp\nuget.4.9.2.exe
 √ Restoring NuGet packages
 √ Found MSBuild v16.0 at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin (16.6.30114.105)
 √ Found Solution: C:/PATH-TO-PROJECT/windows/rn.sln
 i Build configuration: Debug
 i Build platform: x86
 × Building Solution: ReactImage.obj : fatal error LNK1103: debugging information corrupt; recompile module [C:\U...
 × Build failed with message ReactImage.obj : fatal error LNK1103: debugging information corrupt; recompile module [C:\PATH-TO-PROJECT\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]. Check your build configuration.
See C:\Users\USERNAME\AppData\Local\Temp\msbuild_9900.err
```

**Comment by louistsaitszho** [comment] 2020-05-31 00:06
**PSA**: 

Looks like there are some reorganization, and the thing you need to select in the installer is now `C++ Universal Windows Platform tools`

**Comment by andraz-at** [comment] 2020-05-31 18:40
In the latest package I needed to **manually find and check MSBuild** package.

Then it installed and stopped throwing the error.

**Comment by andraz-at** [comment] 2020-05-31 18:46
And started throwing this new error after partial build:
`ReactImage.obj : fatal error LNK1103: debugging information corrupt; recompile module`

Should I open a new issue?

**Comment by asklar** [comment] 2020-05-31 19:46
> And started throwing this new error after partial build:
> `ReactImage.obj : fatal error LNK1103: debugging information corrupt; recompile module`
> 
> Should I open a new issue?

@andraz-at :
This is a known issue with VS 16.6, it's not specific to RNW:
https://developercommunity.visualstudio.com/content/problem/1042212/vs-166-compilation-fails-after-update.html

**Comment by longmans** [comment] 2020-06-01 06:43
> > And started throwing this new error after partial build:
> > `ReactImage.obj : fatal error LNK1103: debugging information corrupt; recompile module`
> > Should I open a new issue?
> 
> @andraz-at :
> This is a known issue with VS 16.6, it's not specific to RNW:
> https://developercommunity.visualstudio.com/content/problem/1042212/vs-166-compilation-fails-after-update.html

downgrade would be help?

> > And started throwing this new error after partial build:
> > `ReactImage.obj : fatal error LNK1103: debugging information corrupt; recompile module`
> > Should I open a new issue?
> 
> @andraz-at :
> This is a known issue with VS 16.6, it's not specific to RNW:
> https://developercommunity.visualstudio.com/content/problem/1042212/vs-166-compilation-fails-after-update.html

so downgrade would be help?

**Comment by longmans** [comment] 2020-06-01 06:44
> > And started throwing this new error after partial build:
> > `ReactImage.obj : fatal error LNK1103: debugging information corrupt; recompile module`
> > Should I open a new issue?
> 
> @andraz-at :
> This is a known issue with VS 16.6, it's not specific to RNW:
> https://developercommunity.visualstudio.com/content/problem/1042212/vs-166-compilation-fails-after-update.html

so downgrade would be help?

**Comment by asklar** [comment] 2020-06-01 06:54
> > > And started throwing this new error after partial build:
> > > `ReactImage.obj : fatal error LNK1103: debugging information corrupt; recompile module`
> > > Should I open a new issue?
> > 
> > 
> > @andraz-at :
> > This is a known issue with VS 16.6, it's not specific to RNW:
> > https://developercommunity.visualstudio.com/content/problem/1042212/vs-166-compilation-fails-after-update.html
> 
> so downgrade would be help?

@longmans yes the options are to do one of the following:
- downgrading to 16.5 would work (although 16.5 has a different bug regarding signing certificates for all UWP apps, which we've worked around - see #4958), or
- use RNW from master which has a workaround we've added (#4962), or
- we're going to be backport the workaround to 0.62 (and maybe 0.61 too?), or
- cherry-pick the fix to #4962 to your own fork if you're in a hurry.

**Comment by Alkanores** [comment] 2020-06-04 15:28
> Same
> 
> * SDK Installed
> * Node 10.15.1
> * yarn 1.22.0
> 
> 1. `react-native init <Project> --version ^0.60.0`
> 2. `cd <Project>`
> 3. `yarn add rnpm-plugin-windows`
> 4. `react-native windows`
> 5. `react-native run-windows`
> 
> ```
>  i Build configuration: Debug
>  i Build platform: x86
> Running MSBuild with args /clp:NoSummary;NoItemAndPropertyList;Verbosity=normal /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never /p:PlatformToolset=v141 /p:VisualStudioVersion=15.0 /bl
>  × Building Solution: Utilisation�:          100,0    Utilisation moyenne�: 100,0...
>  × Build failed with message undefined. Check your build configuration.
> ```

Same issue.
* SDK Installed
* Node 12.18.0
* yarn: 1.22.0
* Build platform: x86
* MSBuild Version: 16.0

Errors in --logging mode:
1. error : Failed to open certificate(translate from russian): projectname_TemporaryKey.pfx.
2. error : Required object not found(translate from russian)  [C:\Users\username\testrn\projectname\windows\projectname\projectname.vcxproj].

**Comment by asklar** [comment] 2020-06-04 18:41
> > Same
> > 
> > * SDK Installed
> > * Node 10.15.1
> > * yarn 1.22.0
> > 
> > 
> > 1. `react-native init <Project> --version ^0.60.0`
> > 2. `cd <Project>`
> > 3. `yarn add rnpm-plugin-windows`
> > 4. `react-native windows`
> > 5. `react-native run-windows`
> > 
> > ```
> >  i Build configuration: Debug
> >  i Build platform: x86
> > Running MSBuild with args /clp:NoSummary;NoItemAndPropertyList;Verbosity=normal /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never /p:PlatformToolset=v141 /p:VisualStudioVersion=15.0 /bl
> >  × Building Solution: Utilisation�:          100,0    Utilisation moyenne�: 100,0...
> >  × Build failed with message undefined. Check your build configuration.
> > ```
> 
> Same issue.
> 
> * Node 12.18.0
> * yarn: 1.22.0
> * Build platform: x86
> * MSBuild Version: 16.0
> 
> Errors in --logging mode:
> 
> 1. error : Failed to open certificate(translate from russian): projectname_TemporaryKey.pfx.
> 2. error : Required object not found(translate from russian)  [C:\Users\username\testrn\projectname\windows\projectname\projectname.vcxproj].

Looks like you're running VS2019 against an old version of RNW (0.60). Can you upgrade to RNW 0.62? Or alternatively, use VS2017 if you need to stick with RNW 0.60

**Comment by Alkanores** [comment] 2020-06-05 07:07
@asklar 
How can I check RNW version?

**Comment by asklar** [comment] 2020-06-05 07:11
@Alkanores it's in the command line you provided above: `react-native init <Project> --version ^0.60.0`
It should also be in your `package.json` in your project.

**Comment by Alkanores** [comment] 2020-06-05 09:11
@asklar 
This fields in my package.json:
"react-native": "0.61.5",
"react-native-windows": "^0.61.0-0"

**Comment by asklar** [comment] 2020-06-05 10:05
@Alkanores I'm pretty sure you're running into a regression that was introduced into Visual Studio in version 16.5 and is present in 16.6 still. 

Can you confirm what version of VS you're on?

`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -version 16 -property catalog_productDisplayVersion`

I added a workaround for the time being and backported it to 0.61 here, but it may not yet be available for you to consume. See #5100 . @NickGerleman  can answer how/when this will be available for 0.61

**Comment by Alkanores** [comment] 2020-06-05 11:08
@asklar 
C:\Users\redfo>"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -version 16 -property catalog_productDisplayVersion
**16.5.2**

**Comment by Alkanores** [comment] 2020-06-06 16:26
@asklar 
I need to create RN project with version 0.61(not 0.61.5) to fix this error, right?

**Comment by willerpp** [comment] 2020-06-17 16:57
thank you @uhteddy for your detailed post, it works for me.

**Comment by asklar** [comment] 2020-06-17 21:39
Here is the VS bug for the LNK1103 / LNK4209 error introduced in VS 16.6 :
https://developercommunity.visualstudio.com/content/problem/1042212/vs-166-compilation-fails-after-update.html
https://developercommunity.visualstudio.com/content/problem/1042211/lots-of-lnk4209-warnings-after-the-latest-update.html?childToView=1082676#comment-1082676

**Comment by AlenToma** [comment] 2022-07-14 03:19
Nothing worked for me, I hade installed vs 2022 and included `C++ platform tools`.

This is what I did in addition to install `C++ platform tools`.
Search for `MSBuild` in individual installations and install it. Then add the msBuild Path to system variable `Path` in my case it was `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\`

then run `react-native run-windows` it should work now.

**Comment by luthfianto** [comment] 2022-08-24 20:07
Nothing worked for me.

- Ran that one powershell script as admin
- Do what @uhteddy did (modify VS installation with UWP, C++ v141, C++ v142) 

Still end up with this:

```
npx react-native run-windows --logging
 i Verbose: ON
Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
 ‼ No public VS release found
 i Trying pre-release VS
Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
 × Could not find MSBuild with VCTools for Visual Studio 16.7 or later. Make sure all required components have been installed
Command failed with error NoMSBuild: C
```

**Comment by asklar** [comment] 2022-08-24 20:21
@luthfianto Looks like you are using the "BuildTools" edition of Visual Studio, which may not contain all the necessary components. Does this repro for you with Community or another edition?

**Comment by luthfianto** [comment] 2022-08-24 20:25
@asklar thank you for spotting the error

**Comment by luthfianto** [comment] 2022-08-24 20:31
@asklar I had another error after typing `y`
![image](https://user-images.githubusercontent.com/1331389/186517398-e9126e66-46fc-45b3-8af6-9e636fcc11d4.png)

**Comment by asklar** [comment] 2022-08-24 20:33
Can you try manually removing the BuildTools edition first (should be possible in the Visual Studio installer)

**Comment by luthfianto** [comment] 2022-08-24 20:34
@asklar yes, currently still on progress

**Comment by luthfianto** [comment] 2022-08-24 20:34
@asklar yes, already removed

**Comment by luthfianto** [comment] 2022-08-24 20:41
@asklar since I have error with the CLI, should I install the VS2019 community (and MSVC and UWP) via the VS Installer instead?

**Comment by luthfianto** [comment] 2022-08-24 21:03
I solved my problems by:
- uninstalled the VS2019 build tools via installer
- installed VS2019 Community via installer
- running this powershell command https://microsoft.github.io/react-native-windows/docs/rnw-dependencies

**Comment by chrisglein** [comment] 2022-12-05 22:14
> Same here, the system is completely useless, I tried everything:
> 
> npx react-native run-windows ‼ No public VS release found i Trying pre-release VS × Could not find MSBuild with VCTools for Visual Studio 16.7 or later. Make sure all required components have been installed Command failed. Re-run the command with --logging for more information.

The original issue here is a few years old, and even the resolution is a few months old. It'd be helpful to get a fresh issue that includes the environment information requested by the template.

**Comment by robozb** [comment] 2022-12-06 05:30
Dear @chrisglein,

I will share the system info, but until then, would you be so kind to link me, what was the solution to the above issue?

Thanks: Bela
