### ISSUE TITLE
Support HTML printing on react-native-print

### ISSUE THREAD

**Issue by emanuelmartin** [microsoft/react-native-windows#7969] opened 2021-06-08 02:46 UTC
# Proposal: Support HTML printing on react-native-print

## Summary
It should be great to print from HTML, not only for PDF, on react native windows.

## Motivation
It's crucial to support printing not only PDF, but HTML, since it's the way to print variable content in forms.

**Comment by asklar** [comment] 2021-06-08 04:03
Duplicate of christopherdro/react-native-print#132

**Comment by asklar** [comment] 2021-06-08 04:07
See also #7723

**Comment by chrisglein** [comment] 2021-06-10 18:19
Closing this issue as we have the request covered through the issues above.

**Closed by chrisglein** 2021-06-10 18:19 UTC
Labels: Area: Native Modules, Needs: Triage :mag:, enhancement
