### ISSUE TITLE
Playground and app template should Dispose properly on app shutdown

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#1148] opened 2017-06-13 19:21 UTC
Playground and app template need to call DisposeAsync() on ReactPage from the dispatcher thread in their OnDestroy() lifecycle handler to avoid various issues at app shutdown time.

**Comment by rozele** [comment] 2019-02-26 04:50
Likely dupe of #1470

**Closed by rozele** 2019-02-26 04:50 UTC
