### ISSUE TITLE
How to build .exe file

### ISSUE THREAD

**Issue by chzappsinc** [microsoft/react-native-windows#10451] opened 2022-08-26 13:44 UTC
### Problem Description

How to build .exe file for external share

### Steps To Reproduce

I am new to react-native-windows please help us, Avoid if I am wrong!..

### CLI version

8.0.6

### Environment

```markdown
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 5.51 GB / 15.73 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-Tiramisu | Google APIs Intel x86 Atom_64
      Android NDK: 22.1.7171670
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0, 10.0.20348.0, 10.0.22000.0, 10.0.22621.0
  IDEs:
    Android Studio: AI-212.5712.43.2112.8815526
    Visual Studio: 16.11.32802.440 (Visual Studio Community 2019), 17.3.32819.101 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.15 - C:\Program Files\Eclipse Adoptium\jdk-11.0.15.10-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.5 => 0.69.5
    react-native-windows: 0.69.6 => 0.69.6
```

### Target Platform Version

10.0.15063

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Release

**Comment by chrisglein** [comment] 2022-08-26 16:32
Duplicate of #8614

**Comment by chrisglein** [comment] 2022-08-26 16:32
You should be able to find more information in the linked duplicate bug.

**Closed by chrisglein** 2022-08-26 16:32 UTC
Labels: bug, Needs: Triage :mag:
