### ISSUE TITLE
We should maintain selection when changing TextInput text

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5687] opened 2020-08-11 10:54 UTC
Setting the `text` property on TextInput will move the cursor to the beginning of the TextInput field. This differs from Android and iOS, with iOS recently fixing a bug with it moving to the end of the input https://github.com/facebook/react-native/commit/0ef63d0cacdb3f72fc3e996f73b499b3a7c6aa31

TextInputExample has "rewrite" examples, for replacing banned characters, where the act of moving selection to the beginning of the text field is undesired.

Need to make sure to correctly handle selection changed events, cases where text lengths don't match, etc.

**Comment by chrisglein** [comment] 2021-01-04 19:15
Duplicate of #6786

**Closed by chrisglein** 2021-01-04 19:15 UTC
Labels: Area: TextInput, bug
